export type AuditApplication = {
  /** Generated by the browser once per audit attempt; used for lead idempotency. */
  requestId: string;
  name: string;
  businessName: string;
  email: string;
  phone?: string;
  website?: string;
  industry?: string;
  teamSize?: string;
  challenge: string;
  affectedArea: string;
  currentProcess: string;
  manualWork: string;
  failureImpact: string;
  tools?: string;
  frequency: string;
  desiredOutcome: string;
  priority: string;
  readiness: string;
  foundingInterest: string;
  source?: string;
  campaign?: string;
  landingPage?: string;
};
