import { calculatePriority, classifyPriority, PILLARS } from "~/lib/audit-scoring";
import type { ArchitectureDiagram, AuditReport, BusinessProfile, EvidenceClass, Finding, Opportunity, RoadmapPhase } from "~/types/audit";

type Page = { url: string; html: string; text: string };
type Signal = { key: string; evidence: EvidenceClass; statement: string; source?: string };
const MAX_BYTES = 750_000;

function text(html: string) { return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&nbsp;|&#160;/gi, " ").replace(/&amp;/gi, "&").replace(/\s+/g, " ").trim(); }
function title(html: string) { return (html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] ?? "").replace(/<[^>]+>/g, "").trim(); }
function hostname(input: string) { const clean = input.includes("://") ? input : `https://${input}`; const url = new URL(clean); if (!["http:", "https:"].includes(url.protocol) || !url.hostname.includes(".")) throw new Error("Please enter a public website address."); return url; }
async function get(url: string): Promise<Page | null> { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 9000); try { const response = await fetch(url, { signal: controller.signal, redirect: "follow", headers: { "User-Agent": "EllisOpportunityAudit/1.0 (+https://ellisaistudio.com/audit)" } }); if (!response.ok || !response.headers.get("content-type")?.includes("text/html")) return null; const html = (await response.text()).slice(0, MAX_BYTES); return { url: response.url, html, text: text(html) }; } catch { return null; } finally { clearTimeout(timer); } }
function source(pages: readonly Page[], expression: RegExp) { return pages.find((page) => expression.test(page.html))?.url; }
function confidence(evidence: readonly EvidenceClass[]) { return evidence.includes("observed") ? "high" : evidence.includes("inferred") ? "medium" : "low" as const; }
function opportunity(input: Omit<Opportunity, "priority" | "tier" | "confidence">): Opportunity { const priority = calculatePriority(input.scores); return { ...input, priority, tier: classifyPriority(priority), confidence: confidence(input.evidence) }; }

export async function analyzeWebsite(input: string): Promise<AuditReport> {
  const base = hostname(input); const root = `${base.protocol}//${base.host}`;
  const rootPage = await get(root); if (!rootPage) throw new Error("We couldn't read that website. Check the address and try again.");
  const candidates = ["/contact", "/contact-us", "/services", "/about", "/book", "/booking"].map((path) => new URL(path, root).toString());
  const additional = (await Promise.all(candidates.map(get))).filter((page): page is Page => Boolean(page));
  const pages = [rootPage, ...additional.filter((page, index, all) => all.findIndex((other) => other.url === page.url) === index)];
  const signals: Signal[] = [];
  const observed = (key: string, statement: string, expression: RegExp) => { const page = source(pages, expression); if (page) signals.push({ key, evidence: "observed", statement, source: page }); return Boolean(page); };
  const form = observed("form", "A website enquiry form is publicly available.", /<form\b/i);
  const phone = observed("phone", "A phone enquiry path is publicly available.", /href=["']tel:/i);
  const booking = observed("booking", "A booking or scheduling path is publicly available.", /calendly|acuity|book(?:ing)?\b|schedule\b/i);
  const reviews = observed("reviews", "Public review or testimonial content is visible.", /review|testimonial|google-rating|stars/i);
  const faq = observed("faq", "Frequently asked questions or answer content is visible.", /faq|frequently asked|question/i);
  const crm = observed("crm", "A CRM or marketing-platform script is publicly visible.", /hubspot|salesforce|gohighlevel|activecampaign|pipedrive/i);
  const analytics = observed("analytics", "A web analytics tag is publicly visible.", /googletagmanager|gtag\(|google-analytics|segment\.com/i);
  const servicePages = observed("services", "Service information is publicly described on the website.", /service|what we do|our work/i);
  const name = title(rootPage.html).split(/[|–—-]/)[0].trim() || base.hostname.split(".")[0].replace(/[-_]/g, " ");
  const serviceMatches = [...rootPage.text.matchAll(/(?:services?|speciali[sz]e in|we offer)\s*(?:in|:)?\s*([^.!?]{12,150})/gi)].map((m) => m[1].trim()).slice(0, 3);
  const digitalSurface: Finding[] = signals.map(({ evidence, statement, source: findingSource }) => ({ evidence, statement, source: findingSource }));
  const opportunities: Opportunity[] = [];
  if (form || phone) opportunities.push(opportunity({ id: "lead-response", name: "Lead Response Automation", pillar: "lead-management", type: "Lead Response", scores: { impact: 88, confidence: form ? 84 : 70, fit: 88, implementationEase: 80 }, evidence: ["observed", "inferred"], observed: digitalSurface.filter((finding) => /enquiry|phone/.test(finding.statement)), friction: "New enquiries may depend on someone seeing and responding to them manually.", whyItMatters: "A fast, consistent first response can reduce avoidable waiting for both prospects and the team.", proposedSystem: [{ label: "Website or phone enquiry" }, { label: "AI qualification", emphasis: true }, { label: "CRM" }, { label: "Immediate response" }, { label: "Team notification" }], benefits: ["Faster first response", "Consistent lead handling", "Less manual triage"], discoveryQuestion: "How are new enquiries handled after they arrive, including after hours?" }));
  if (form && servicePages) opportunities.push(opportunity({ id: "smart-intake", name: "Service-Aware Intake", pillar: "conversion", type: "Lead Qualification", scores: { impact: 82, confidence: 78, fit: 87, implementationEase: 75 }, evidence: ["observed", "inferred"], observed: digitalSurface.filter((finding) => /form|Service/.test(finding.statement)), friction: "One general enquiry path may not collect the information needed for each service type.", whyItMatters: "Better context at first contact can reduce back-and-forth before a useful next step.", proposedSystem: [{ label: "Service selection" }, { label: "Conditional questions" }, { label: "Qualification summary", emphasis: true }, { label: "CRM record" }], benefits: ["More complete enquiries", "Clearer routing", "Less repetitive qualification"], discoveryQuestion: "What must your team know before an enquiry can be booked or quoted?" }));
  if (!booking && (form || phone)) opportunities.push(opportunity({ id: "scheduling", name: "Scheduling Automation", pillar: "customer-experience", type: "Scheduling", scores: { impact: 72, confidence: 65, fit: 80, implementationEase: 70 }, evidence: ["observed", "inferred"], observed: [{ evidence: "observed", statement: "Enquiry paths are visible, but no self-service booking path was observed.", source: rootPage.url }], friction: "Scheduling may require a manual exchange after a prospect is ready to speak.", whyItMatters: "Reducing handoffs can make it easier for ready prospects to take the next step.", proposedSystem: [{ label: "Qualified enquiry" }, { label: "Availability rules" }, { label: "Scheduling link" }, { label: "Confirmation" }], benefits: ["Fewer scheduling handoffs", "Clearer next steps", "Consistent confirmations"], discoveryQuestion: "Which appointments can safely be booked without a person coordinating first?" }));
  if (reviews) opportunities.push(opportunity({ id: "review-generation", name: "Review Generation Workflow", pillar: "growth", type: "Retention Automation", scores: { impact: 70, confidence: 62, fit: 78, implementationEase: 76 }, evidence: ["observed", "inferred"], observed: digitalSurface.filter((finding) => /review/.test(finding.statement)), friction: "Public proof is visible, but the post-service review request process cannot be established.", whyItMatters: "A consistent close-out workflow can make it easier to request feedback at the right moment.", proposedSystem: [{ label: "Job complete" }, { label: "Satisfaction check" }, { label: "Review request" }, { label: "Follow-up" }], benefits: ["More consistent review requests", "Better service recovery signals", "Stronger proof over time"], discoveryQuestion: "What happens after a customer’s work is completed today?" }));
  if (faq) opportunities.push(opportunity({ id: "faq-support", name: "FAQ & Customer Support", pillar: "customer-experience", type: "Customer Support", scores: { impact: 60, confidence: 72, fit: 72, implementationEase: 82 }, evidence: ["observed", "inferred"], observed: digitalSurface.filter((finding) => /question/.test(finding.statement)), friction: "Answers may be spread across pages rather than available at the moment a prospect asks.", whyItMatters: "Clear, approved answers can help prospects self-serve before contacting the team.", proposedSystem: [{ label: "Approved knowledge" }, { label: "Guided answers", emphasis: true }, { label: "Escalation to team" }], benefits: ["Fewer repeated questions", "Clearer customer guidance", "Escalation when needed"], discoveryQuestion: "Which questions does your team answer repeatedly before an enquiry converts?" }));
  if (!crm && (form || phone)) opportunities.push(opportunity({ id: "crm-integration", name: "Lead Record & Routing", pillar: "operations", type: "CRM Integration", scores: { impact: 78, confidence: 55, fit: 85, implementationEase: 62 }, evidence: ["observed", "unknown"], observed: [{ evidence: "observed", statement: "Public enquiry routes are present; the internal system that receives them is not visible.", source: rootPage.url }, { evidence: "unknown", statement: "The CRM or lead-management system used internally cannot be established." }], friction: "Customer details may need to be copied or routed manually after first contact.", whyItMatters: "One reliable record can make ownership and follow-up easier to manage.", proposedSystem: [{ label: "Enquiry capture" }, { label: "Field mapping" }, { label: "CRM record" }, { label: "Owner routing" }], benefits: ["One customer record", "Clear ownership", "Less duplicate entry"], discoveryQuestion: "Where does a new lead live today, and who becomes responsible for it?" }));
  if (analytics || form || phone) opportunities.push(opportunity({ id: "executive-intelligence", name: "Executive Intelligence", pillar: "intelligence", type: "Reporting", scores: { impact: 66, confidence: analytics ? 64 : 45, fit: 76, implementationEase: 58 }, evidence: analytics ? ["observed", "inferred"] : ["unknown"], observed: analytics ? digitalSurface.filter((finding) => /analytics/.test(finding.statement)) : [{ evidence: "unknown", statement: "Internal reporting and decision processes cannot be established from public information." }], friction: "A single view of enquiry volume, source, response and outcome may not exist.", whyItMatters: "Shared operating signals help a business learn which improvements are worth making next.", proposedSystem: [{ label: "Connected systems" }, { label: "Reporting model" }, { label: "Decision signals", emphasis: true }], benefits: ["Clearer operating visibility", "Faster decisions", "A measurable improvement loop"], discoveryQuestion: "Which lead, conversion and delivery signals do you review each week?" }));
  const sorted = opportunities.sort((a, b) => b.priority - a.priority);
  const pillarSignals = PILLARS.map((pillar) => { const found = sorted.filter((item) => item.pillar === pillar.id); const score = found.length ? Math.round(found.reduce((sum, item) => sum + item.priority, 0) / found.length) : 20; return { pillar: pillar.id, opportunityCount: found.length, opportunity: score, note: found.length ? `${found.length} opportunity${found.length === 1 ? "" : "ies"} identified from publicly observable signals.` : "No material opportunity could be established from public information." }; });
  const automationOpportunity = Math.round(sorted.length ? sorted.reduce((sum, item) => sum + item.priority, 0) / sorted.length : 20);
  const maturity = crm && analytics ? "connected" : crm || analytics ? "developing" : "foundational";
  const phases: RoadmapPhase[] = [{ number: 1, name: "Capture & Respond", intent: "Make sure enquiries are captured, understood and answered.", opportunityIds: sorted.filter((item) => ["lead-response", "smart-intake", "scheduling"].includes(item.id)).map((item) => item.id), items: ["Lead intake", "Qualification", "Immediate response"], horizon: "First" }, { number: 2, name: "Manage & Convert", intent: "Connect handoffs and follow-up around one customer record.", opportunityIds: sorted.filter((item) => ["crm-integration", "faq-support"].includes(item.id)).map((item) => item.id), items: ["CRM", "Routing", "Customer guidance"], horizon: "Next" }, { number: 3, name: "Optimize & Learn", intent: "Turn a working system into measurable operating intelligence.", opportunityIds: sorted.filter((item) => ["review-generation", "executive-intelligence"].includes(item.id)).map((item) => item.id), items: ["Reviews", "Reporting", "Decision signals"], horizon: "Then" }].filter((phase) => phase.opportunityIds.length);
  const architecture: ArchitectureDiagram = { title: "What Ellis AI Studio would build", summary: "A connected response system based on the opportunities visible from public information.", layers: [{ name: "Capture", nodes: [{ id: "website", label: "Website", kind: "source", detail: "Public enquiry paths" }] }, { name: "Qualify", nodes: [{ id: "intake", label: "Smart Intake", kind: "system", detail: "Service-aware context" }, { id: "ai", label: "AI Qualification", kind: "ai", detail: "Summarises and routes" }] }, { name: "Record", nodes: [{ id: "crm", label: "CRM", kind: "store", detail: "One customer record" }] }, { name: "Respond", nodes: [{ id: "customer", label: "Customer Response", kind: "output", detail: "Immediate acknowledgement" }, { id: "team", label: "Team Notification", kind: "output", detail: "Clear ownership" }] }, { name: "Learn", nodes: [{ id: "reporting", label: "Reporting", kind: "output", detail: "Operating signals" }] }] };
  const profile: BusinessProfile = { name, location: "Location not established from public information", category: servicePages ? "Service business" : "Business category not established", website: root, summary: `${name} appears to operate through a public website. This profile is based only on pages and public signals the audit could read.`, services: serviceMatches.length ? serviceMatches : ["Services not confidently established"], audience: "Audience not established from public information", digitalSurface, customerJourney: [{ name: "Discover", detail: "A public website is available.", evidence: "observed" }, { name: "Enquire", detail: form || phone ? "A public enquiry path is available." : "An enquiry path could not be established.", evidence: form || phone ? "observed" : "unknown" }, { name: "Respond", detail: "The internal response process is not publicly observable.", evidence: "unknown", frictionNote: form || phone ? "Response may depend on manual availability; this requires discovery validation." : undefined }, { name: "Deliver", detail: "Delivery operations are not publicly observable.", evidence: "unknown" }, { name: "Follow-up", detail: "Post-service follow-up is not publicly observable.", evidence: "unknown" }] };
  return { id: `audit-${crypto.randomUUID().slice(0, 8)}`, generatedAt: new Date().toISOString(), profile, automationOpportunity, maturity, headline: sorted[0] ? `${sorted[0].name} is the most apparent opportunity based on the public signals available.` : "The public website did not expose enough signals to identify a material automation opportunity.", pillarSignals, opportunities: sorted, roadmap: phases, architecture, unknowns: ["Internal systems and ownership", "Actual response times", "Delivery capacity and operational constraints", "Existing automations and reporting"] };
}
