import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { PublishedPostMetadata } from "~/lib/social-provider";
const root = "content/linkedin";
const schedulePath = ".data/content-schedule.json";
export type ContentItem = { id: string; title: string; topic: string; body: string; scheduledFor?: string; approved?: boolean; published?: PublishedPostMetadata; lastModified?: number };
type StoredContent = { id: string } & Partial<Omit<ContentItem, "id">>;
async function stored(): Promise<StoredContent[]> { try { return JSON.parse(await readFile(schedulePath, "utf8")); } catch { return []; } }
async function write(entries: StoredContent[]) { await mkdir(".data", { recursive: true }); await writeFile(schedulePath, JSON.stringify(entries, null, 2)); }
export async function listContent(): Promise<ContentItem[]> { const saved = await stored(); const groups = await readdir(root, { withFileTypes: true }); const items: ContentItem[] = []; for (const group of groups.filter(x => x.isDirectory())) for (const file of await readdir(join(root, group.name))) { if (!file.endsWith(".md")) continue; const raw = await readFile(join(root, group.name, file), "utf8"); const title = raw.match(/^title:\s*(.+)$/m)?.[1] ?? file; const id = group.name + "/" + file; const override = saved.find(entry => entry.id === id); items.push({ id, title, topic: group.name, body: raw, ...override }); } for (const entry of saved) if (!items.some(item => item.id === entry.id) && entry.title && entry.body) items.push({ id: entry.id, title: entry.title, topic: entry.topic ?? "draft", body: entry.body, scheduledFor: entry.scheduledFor, approved: entry.approved, published: entry.published, lastModified: entry.lastModified }); return items.sort((a,b) => (b.lastModified ?? 0) - (a.lastModified ?? 0) || a.id.localeCompare(b.id)); }
export async function saveSchedule(item: Pick<ContentItem, "id" | "scheduledFor" | "approved">) { const entries = await stored(); const existing = entries.findIndex(x => x.id === item.id); if (existing >= 0) entries[existing] = { ...entries[existing], ...item }; else entries.push(item); await write(entries); return item; }
export async function savePublishedMetadata(id: string, published: PublishedPostMetadata) { const entries = await stored(); const existing = entries.findIndex(entry => entry.id === id); if (existing >= 0) entries[existing] = { ...entries[existing], published }; else entries.push({ id, published }); await write(entries); return published; }
export async function saveContentDraft(item: Pick<ContentItem, "id" | "title" | "body">) { const entries = await stored(); const existing = entries.findIndex(entry => entry.id === item.id); const draft = { ...item, lastModified: Date.now() }; if (existing >= 0) entries[existing] = { ...entries[existing], ...draft }; else entries.push(draft); await write(entries); return draft; }
export async function createContentDraft(input: { title: string; body: string; topic?: string }) { const item: ContentItem = { id: "draft/" + crypto.randomUUID() + ".md", title: input.title, body: input.body, topic: input.topic ?? "draft", lastModified: Date.now() }; const entries = await stored(); entries.unshift(item); await write(entries); return item; }
