import { timingSafeEqual } from "node:crypto";
import { getRequestHeader, setResponseHeader } from "@tanstack/react-start/server";
import { loadLocalEnvironment } from "~/lib/local-env.server";
import { createEncryptedJsonStore, createOAuthDiagnostics, createSignedState, fingerprint, validateSignedState } from "~/lib/oauth-framework.server";

loadLocalEnvironment();

const GMAIL_SCOPES = ["https://www.googleapis.com/auth/gmail.modify", "https://www.googleapis.com/auth/gmail.compose", "https://www.googleapis.com/auth/gmail.send"];
const STORE_PATH = process.env.GMAIL_TOKEN_STORE_PATH ?? ".data/gmail.json";
const SCHEDULE_PATH = process.env.GMAIL_SCHEDULE_STORE_PATH ?? ".data/gmail-scheduled.json";
const trace = createOAuthDiagnostics("gmail", process.env.GMAIL_OAUTH_TRACE_PATH ?? ".diagnostics/gmail-oauth.log");

type Token = { accessToken: string; refreshToken: string; expiresAt: number; email: string; historyId?: string; connectedAt: number; lastSyncAt?: number };
export type GmailAttachment = { name: string; mimeType: string; dataBase64: string };
export type MailAttachment = { id?: string; name: string; mimeType: string; size?: number };
export type MailMessage = { id: string; threadId: string; from: string; to: string; subject: string; snippet: string; date: string; labelIds: string[]; unread: boolean; starred: boolean; hasAttachments: boolean; body?: string; bodyHtml?: string; bodyText?: string; attachments?: MailAttachment[] };
export type MailThread = { id: string; messages: MailMessage[]; latest: MailMessage; participants: string[]; unread: boolean; starred: boolean; labels: string[]; priority: "high" | "normal" | "low"; needsReply: boolean; meetingSignal: boolean; salesSignal: boolean; summary?: string; suggestedReply?: string };
export type GmailConnection = { accessRequired: boolean; configured: boolean; connected: boolean; email?: string; expiresAt?: number; lastSyncAt?: number; message?: string };
type ScheduledDraft = { id: string; to: string[]; subject: string; html: string; attachments: GmailAttachment[]; scheduledFor: number; createdAt: number };

function required(name: string) { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured.`); return value; }
function configured() { return ["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET", "GMAIL_OAUTH_REDIRECT_URI", "GMAIL_OAUTH_STATE_SECRET", "GMAIL_TOKEN_ENCRYPTION_KEY", "GMAIL_DASHBOARD_ACCESS_TOKEN"].every((name) => Boolean(process.env[name])); }
function cookie(name: string) { return (getRequestHeader("cookie") ?? "").split(";").map((value) => value.trim()).find((value) => value.startsWith(`${name}=`))?.slice(name.length + 1); }
function allowed() { const expected = process.env.GMAIL_DASHBOARD_ACCESS_TOKEN; const actual = cookie("ellis_gmail_dashboard"); return Boolean(expected && actual && expected.length === actual.length && timingSafeEqual(Buffer.from(expected), Buffer.from(actual))); }
function access() { if (!allowed()) throw new Error("Dashboard access is required."); }
const store = createEncryptedJsonStore<Token | undefined>({ path: STORE_PATH, encryptionSecret: () => required("GMAIL_TOKEN_ENCRYPTION_KEY"), empty: () => undefined });
const scheduleStore = createEncryptedJsonStore<ScheduledDraft[]>({ path: SCHEDULE_PATH, encryptionSecret: () => required("GMAIL_TOKEN_ENCRYPTION_KEY"), empty: () => [] });

function encoded(value: string) { return Buffer.from(value).toString("base64url"); }
function decoded(value: string) { return Buffer.from(value, "base64url").toString("utf8"); }
function decodeQuotedPrintable(value: string) { return value.replace(/=\r?\n/g, "").replace(/=([A-F\d]{2})/gi, (_match, hex: string) => String.fromCharCode(Number.parseInt(hex, 16))); }
function header(headers: Array<{ name?: string; value?: string }> | undefined, name: string) { return headers?.find((entry) => entry.name?.toLowerCase() === name.toLowerCase())?.value ?? ""; }
function htmlToText(value: string) { return value.replace(/<style[\s\S]*?<\/style>|<script[\s\S]*?<\/script>|<[^>]+>/gi, " ").replace(/\s+/g, " ").trim(); }
function isRawMime(value: string) { return /(^|\n)(mime-version:|content-type:\s*multipart\/|content-transfer-encoding:|--[A-Za-z0-9_=-]{8,})/i.test(value); }
function sanitizeEmailHtml(value: string) { return value.replace(/<!--[\s\S]*?-->/g, "").replace(/<\/?(?:script|style|iframe|object|embed|base|form)[^>]*>/gi, "").replace(/\son\w+\s*=\s*(?:\"[^\"]*\"|'[^']*'|[^\s>]+)/gi, "").replace(/\s(?:href|src)\s*=\s*([\"'])\s*javascript:[\s\S]*?\1/gi, ""); }
function escapeHeader(value: string) { return value.replace(/[\r\n]+/g, " ").trim(); }
function encodeHeader(value: string) { const clean = escapeHeader(value); return /[^\x20-\x7e]/.test(clean) ? `=?UTF-8?B?${Buffer.from(clean, "utf8").toString("base64")}?=` : clean; }
function foldBase64(value: string) { return value.match(/.{1,76}/g)?.join("\r\n") ?? ""; }
function plainTextFromHtml(value: string) { return htmlToText(value.replace(/<\s*br\s*\/?\s*>/gi, "\n").replace(/<\/(?:p|div|li|h[1-6])\s*>/gi, "\n")); }
function priorityOf(message: MailMessage) { const source = `${message.from} ${message.subject} ${message.snippet}`.toLowerCase(); if (/urgent|asap|invoice|proposal|contract|meeting|today|tomorrow|follow up|follow-up/.test(source)) return "high" as const; if (/newsletter|receipt|notification|automated/.test(source)) return "low" as const; return "normal" as const; }

export class GoogleAuthService {
  unlock(accessToken: string) { const expected = required("GMAIL_DASHBOARD_ACCESS_TOKEN"); if (accessToken.length !== expected.length || !timingSafeEqual(Buffer.from(accessToken), Buffer.from(expected))) throw new Error("Dashboard access was denied."); setResponseHeader("Set-Cookie", `ellis_gmail_dashboard=${encodeURIComponent(expected)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`); }
  authorizationUrl() { access(); if (!configured()) throw new Error("Gmail is not configured. Add the required environment variables first."); const state = createSignedState(required("GMAIL_OAUTH_STATE_SECRET")); const redirectUri = required("GMAIL_OAUTH_REDIRECT_URI"); const url = new URL("https://accounts.google.com/o/oauth2/v2/auth"); url.search = new URLSearchParams({ client_id: required("GOOGLE_OAUTH_CLIENT_ID"), redirect_uri: redirectUri, response_type: "code", scope: GMAIL_SCOPES.join(" "), access_type: "offline", prompt: "consent", include_granted_scopes: "true", state }).toString(); trace("authorization_url_generated", { redirectUri, scopes: GMAIL_SCOPES.join(" "), stateFingerprint: fingerprint(state) }); return url.toString(); }
  async finish(code: string, state: string) { access(); trace("callback_received", { hasCode: Boolean(code), hasState: Boolean(state), codeFingerprint: code ? fingerprint(code) : undefined }); validateSignedState(state, required("GMAIL_OAUTH_STATE_SECRET")); trace("state_validated", { stateFingerprint: fingerprint(state) }); trace("token_exchange_started", { endpoint: "https://oauth2.googleapis.com/token", redirectUri: required("GMAIL_OAUTH_REDIRECT_URI") }); let response: Response; try { response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: required("GOOGLE_OAUTH_CLIENT_ID"), client_secret: required("GOOGLE_OAUTH_CLIENT_SECRET"), redirect_uri: required("GMAIL_OAUTH_REDIRECT_URI"), grant_type: "authorization_code" }), signal: AbortSignal.timeout(20_000) }); } catch (error) { const reason = error instanceof Error ? error : new Error("Unknown token-exchange failure."); trace("token_exchange_network_failed", { name: reason.name, message: reason.message, stack: reason.stack?.slice(0, 800) }); throw new Error(`Google token exchange could not be reached: ${reason.message}`); } const raw = await response.text(); let body: { access_token?: string; refresh_token?: string; expires_in?: number; error?: string; error_description?: string } = {}; try { body = JSON.parse(raw); } catch { trace("token_exchange_invalid_json", { status: response.status, bodyPreview: raw.slice(0, 500) }); throw new Error("Google returned an invalid token response."); }
    trace("token_exchange_completed", { status: response.status, hasAccessToken: Boolean(body.access_token), hasRefreshToken: Boolean(body.refresh_token) });
    if (!response.ok || !body.access_token || !body.refresh_token || !body.expires_in) throw new Error(body.error_description ?? "Google did not issue a reusable Gmail token. Reconnect and approve access.");
    const profile = await this.profileFor(body.access_token); const token: Token = { accessToken: body.access_token, refreshToken: body.refresh_token, expiresAt: Date.now() + body.expires_in * 1000, email: profile.emailAddress, historyId: profile.historyId, connectedAt: Date.now(), lastSyncAt: Date.now() }; await store.save(token); trace("token_persisted", { emailFingerprint: fingerprint(token.email), expiresAt: token.expiresAt }); trace("connection_persisted", { emailFingerprint: fingerprint(token.email) }); return { email: token.email }; }
  async profileFor(accessToken: string) { trace("profile_lookup_started", { endpoint: "https://gmail.googleapis.com/gmail/v1/users/me/profile" }); let response: Response; try { response = await fetch("https://gmail.googleapis.com/gmail/v1/users/me/profile", { headers: { Authorization: `Bearer ${accessToken}` }, signal: AbortSignal.timeout(15_000) }); } catch (error) { const reason = error instanceof Error ? error : new Error("Unknown profile failure."); trace("profile_lookup_network_failed", { name: reason.name, message: reason.message, stack: reason.stack?.slice(0, 800) }); throw new Error(`Gmail profile request could not be reached: ${reason.message}`); } const raw = await response.text(); let body: { emailAddress?: string; historyId?: string; error?: { message?: string; status?: string } } = {}; try { body = JSON.parse(raw); } catch { trace("profile_lookup_invalid_json", { status: response.status, bodyPreview: raw.slice(0, 500) }); throw new Error("Gmail profile returned an invalid response."); } if (!response.ok || !body.emailAddress) { trace("profile_lookup_failed", { status: response.status, errorMessage: body.error?.message, errorStatus: body.error?.status, bodyPreview: raw.slice(0, 500) }); throw new Error(body.error?.message ?? "Gmail profile lookup failed."); } trace("profile_lookup_completed", { status: response.status, emailFingerprint: fingerprint(body.emailAddress) }); return { emailAddress: body.emailAddress, historyId: body.historyId }; }
  async active() { const token = await store.load(); if (!token) throw new Error("No Gmail account is connected."); if (token.expiresAt > Date.now() + 60_000) return token; trace("token_refresh_started"); const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: required("GOOGLE_OAUTH_CLIENT_ID"), client_secret: required("GOOGLE_OAUTH_CLIENT_SECRET"), refresh_token: token.refreshToken, grant_type: "refresh_token" }), signal: AbortSignal.timeout(20_000) }); const body = await response.json() as { access_token?: string; expires_in?: number; error_description?: string }; if (!response.ok || !body.access_token || !body.expires_in) { trace("token_refresh_failed", { status: response.status }); throw new Error(body.error_description ?? "Gmail token expired. Reconnect Gmail."); } const next = { ...token, accessToken: body.access_token, expiresAt: Date.now() + body.expires_in * 1000 }; await store.save(next); trace("refresh_completed", { expiresAt: next.expiresAt }); return next; }
  async disconnect() { access(); await store.clear(); trace("disconnect_completed"); }
  async connection(): Promise<GmailConnection> { if (!allowed()) return { accessRequired: true, configured: configured(), connected: false, message: "Dashboard access required." }; if (!configured()) return { accessRequired: false, configured: false, connected: false, message: "Add Gmail OAuth, state, encryption, and dashboard-access secrets." }; const token = await store.load(); return token ? { accessRequired: false, configured: true, connected: true, email: token.email, expiresAt: token.expiresAt, lastSyncAt: token.lastSyncAt } : { accessRequired: false, configured: true, connected: false }; }
}

export class GmailService {
  constructor(private readonly auth = new GoogleAuthService()) {}
  async request(path: string, init: RequestInit = {}) { const token = await this.auth.active(); const response = await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/${path}`, { ...init, headers: { Authorization: `Bearer ${token.accessToken}`, ...(init.headers ?? {}) }, signal: AbortSignal.timeout(20_000) }); if (!response.ok) { const raw = await response.text(); trace("gmail_api_failed", { path: path.split("?")[0], status: response.status, bodyLength: raw.length }); throw new Error(`Gmail request failed (${response.status}).`); } return response; }
  async labels() { const response = await this.request("labels"); const data = await response.json() as { labels?: Array<{ id: string; name: string; type: string; messagesUnread?: number }> }; return data.labels ?? []; }
  async thread(id: string) { const response = await this.request(`threads/${encodeURIComponent(id)}?format=full`); const data = await response.json() as GmailThreadResponse; return parseThread(data); }
  async originalMessage(id: string) { const response = await this.request(`messages/${encodeURIComponent(id)}?format=raw`); const data = await response.json() as { raw?: string }; if (!data.raw) throw new Error("Gmail did not return the original message source."); return decoded(data.raw); }
  async threads(options: { label?: string; query?: string; pageToken?: string; maxResults?: number } = {}) { const params = new URLSearchParams({ maxResults: String(options.maxResults ?? 30) }); if (options.label) params.set("labelIds", options.label); if (options.query) params.set("q", options.query); if (options.pageToken) params.set("pageToken", options.pageToken); const response = await this.request(`threads?${params}`); const data = await response.json() as { threads?: Array<{ id: string }>; nextPageToken?: string; resultSizeEstimate?: number }; const threads = await Promise.all((data.threads ?? []).map((item) => this.thread(item.id))); await this.touch(); return { threads, nextPageToken: data.nextPageToken, total: data.resultSizeEstimate ?? threads.length }; }
  async modifyThread(id: string, addLabelIds: string[] = [], removeLabelIds: string[] = []) { await this.request(`threads/${encodeURIComponent(id)}/modify`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ addLabelIds, removeLabelIds }) }); }
  async search(query: string) { return this.threads({ query, maxResults: 50 }); }
  private async touch() { const token = await store.load(); if (token) await store.save({ ...token, lastSyncAt: Date.now() }); }
}

export type OutboundMessage = { to: string[]; cc?: string[]; subject: string; html: string; attachments?: GmailAttachment[]; threadId?: string; inReplyTo?: string; references?: string[]; signatureHtml?: string };

export class DraftService {
  constructor(private readonly gmail = new GmailService()) {}
  async create(input: OutboundMessage) { const raw = buildGmailRawMessage(input); const message = { raw: encoded(raw), ...(input.threadId ? { threadId: input.threadId } : {}) }; const response = await this.gmail.request("drafts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); return response.json() as Promise<{ id: string; message: { id: string; threadId: string } }>; }
  async send(input: OutboundMessage) { const draft = await this.create(input); const response = await this.gmail.request("drafts/send", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: draft.id }) }); const sent = await response.json() as { id: string; threadId: string; labelIds?: string[] }; trace("message_sent", { messageFingerprint: fingerprint(sent.id), threadFingerprint: fingerprint(sent.threadId) }); return sent; }
  async schedule(input: ScheduledDraft) { const items = await scheduled(); items.push(input); await saveScheduled(items); trace("message_scheduled", { scheduleFingerprint: fingerprint(input.id), scheduledFor: input.scheduledFor }); return input; }
  async runDue() { const all = await scheduled(); const due = all.filter((item) => item.scheduledFor <= Date.now()); const remaining = all.filter((item) => item.scheduledFor > Date.now()); const sent: string[] = []; for (const item of due) { await this.send(item); sent.push(item.id); } await saveScheduled(remaining); return sent; }
}

export class ThreadService { constructor(private readonly gmail = new GmailService()) {} async inbox(label?: string, query?: string) { return this.gmail.threads({ label, query }); } async detail(id: string) { return this.gmail.thread(id); } async archive(id: string) { return this.gmail.modifyThread(id, [], ["INBOX"]); } async star(id: string, starred: boolean) { return this.gmail.modifyThread(id, starred ? ["STARRED"] : [], starred ? [] : ["STARRED"]); } }

export class SearchService { constructor(private readonly gmail = new GmailService()) {} async search(query: string) { const translated = await plutoQuery(query); trace("search_translated", { queryLength: query.length, gmailQuery: translated }); return this.gmail.search(translated); } }
export class NotificationService { summarize(threads: MailThread[]) { const unread = threads.filter((thread) => thread.unread); return { unread: unread.length, waitingReplies: unread.filter((thread) => thread.needsReply).length, meetings: unread.filter((thread) => thread.meetingSignal).length, important: unread.filter((thread) => thread.priority === "high").slice(0, 5) }; } }
export class PlutoEmailService {
  async analyze(thread: MailThread) { const existing = thread.summary; if (existing) return { summary: existing, suggestedReply: thread.suggestedReply ?? "" }; const key = process.env.OPENAI_API_KEY; if (!key) return heuristic(thread); const prompt = `Return JSON only with summary and suggestedReply. Analyze this email thread for an Ellis AI Studio operator. Be concise, factual, and professional. Identify a clear next action. Thread:\n${thread.messages.map((message) => `From: ${message.from}\nSubject: ${message.subject}\n${message.body ?? message.snippet}`).join("\n---\n")}`; const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini", input: prompt }), signal: AbortSignal.timeout(30_000) }); const body = await response.json() as { output_text?: string }; if (!response.ok || !body.output_text) return heuristic(thread); try { const result = JSON.parse(body.output_text) as { summary?: string; suggestedReply?: string }; return { summary: result.summary ?? "", suggestedReply: result.suggestedReply ?? "" }; } catch { return heuristic(thread); } }
}

type GmailPart = { mimeType?: string; filename?: string; headers?: Array<{ name?: string; value?: string }>; body?: { data?: string; attachmentId?: string; size?: number }; parts?: GmailPart[] };
type GmailThreadResponse = { id: string; messages?: Array<{ id: string; threadId: string; labelIds?: string[]; snippet?: string; internalDate?: string; payload?: { headers?: Array<{ name?: string; value?: string }>; mimeType?: string; body?: { data?: string }; parts?: GmailPart[] } }> };
type GmailPayload = NonNullable<NonNullable<GmailThreadResponse["messages"]>[number]["payload"]>;
function displayBody(payload: GmailPayload | undefined, snippet: string) { if (!payload) return { bodyText: snippet }; const stack = [payload as GmailPart, ...(payload.parts ?? [])]; let html = ""; let text = ""; while (stack.length) { const part = stack.shift()!; if (part.parts?.length) stack.push(...part.parts); if (!part.body?.data) continue; const transfer = header(part.headers, "Content-Transfer-Encoding").toLowerCase(); const value = transfer === "quoted-printable" ? decodeQuotedPrintable(decoded(part.body.data)) : decoded(part.body.data); if (isRawMime(value)) continue; if (part.mimeType === "text/html" && !html) html = sanitizeEmailHtml(value); if (part.mimeType === "text/plain" && !text) text = value.trim(); }
  const bodyText = htmlToText(html || text); if (!bodyText) return { bodyText: snippet }; return { bodyText, bodyHtml: html || undefined };
}
function attachmentsOf(parts: GmailPart[] | undefined, all: MailAttachment[] = []): MailAttachment[] { for (const part of parts ?? []) { if (part.parts?.length) attachmentsOf(part.parts, all); if (part.filename || part.body?.attachmentId) all.push({ id: part.body?.attachmentId, name: part.filename || "Attachment", mimeType: part.mimeType || "application/octet-stream", size: part.body?.size }); } return all; }
function parseThread(data: GmailThreadResponse): MailThread { const messages = (data.messages ?? []).map((message): MailMessage => { const payload = message.payload; const labels = message.labelIds ?? []; const content = displayBody(payload, message.snippet ?? ""); const attachments = attachmentsOf(payload?.parts); return { id: message.id, threadId: message.threadId, from: header(payload?.headers, "From"), to: header(payload?.headers, "To"), subject: header(payload?.headers, "Subject") || "(No subject)", snippet: message.snippet ?? "", date: header(payload?.headers, "Date") || new Date(Number(message.internalDate ?? Date.now())).toISOString(), labelIds: labels, unread: labels.includes("UNREAD"), starred: labels.includes("STARRED"), hasAttachments: attachments.length > 0, attachments, body: content.bodyText, ...content }; }); const latest = messages.at(-1) ?? { id: data.id, threadId: data.id, from: "", to: "", subject: "(No subject)", snippet: "", date: "", labelIds: [], unread: false, starred: false, hasAttachments: false }; const source = `${latest.subject} ${latest.snippet}`.toLowerCase(); return { id: data.id, messages, latest, participants: [...new Set(messages.flatMap((message) => [message.from, message.to]).filter(Boolean))], unread: messages.some((message) => message.unread), starred: messages.some((message) => message.starred), labels: [...new Set(messages.flatMap((message) => message.labelIds))], priority: priorityOf(latest), needsReply: latest.labelIds.includes("INBOX") && !/^(re:|fwd:)/i.test(latest.subject) && !/thank you|thanks|received/i.test(source), meetingSignal: /meeting|calendar|schedule|availability|zoom|call/.test(source), salesSignal: /proposal|quote|pricing|budget|contract|scope/.test(source) }; }
export function buildGmailRawMessage(input: OutboundMessage) { const alternative = `alt_${crypto.randomUUID().replaceAll("-", "")}`; const mixed = `mix_${crypto.randomUUID().replaceAll("-", "")}`; const html = `${input.html}${input.signatureHtml ? `<br /><br />${input.signatureHtml}` : ""}`; const text = plainTextFromHtml(html); const alternativePart = [`--${alternative}`, "Content-Type: text/plain; charset=UTF-8", "Content-Transfer-Encoding: base64", "", foldBase64(Buffer.from(text, "utf8").toString("base64")), "", `--${alternative}`, "Content-Type: text/html; charset=UTF-8", "Content-Transfer-Encoding: base64", "", foldBase64(Buffer.from(html, "utf8").toString("base64")), "", `--${alternative}--`].join("\r\n"); const headers = [`To: ${input.to.map(escapeHeader).join(", ")}`, input.cc?.length ? `Cc: ${input.cc.map(escapeHeader).join(", ")}` : "", `Subject: ${encodeHeader(input.subject)}`, input.inReplyTo ? `In-Reply-To: ${escapeHeader(input.inReplyTo)}` : "", input.references?.length ? `References: ${input.references.map(escapeHeader).join(" ")}` : "", "MIME-Version: 1.0"];
  if (!(input.attachments?.length)) return [...headers, `Content-Type: multipart/alternative; boundary="${alternative}"`, "", alternativePart].filter(Boolean).join("\r\n");
  const attachmentParts = input.attachments.map((attachment) => [`--${mixed}`, `Content-Type: ${escapeHeader(attachment.mimeType)}; name="${escapeHeader(attachment.name)}"`, "Content-Transfer-Encoding: base64", `Content-Disposition: attachment; filename="${escapeHeader(attachment.name)}"`, "", foldBase64(attachment.dataBase64.replace(/\s/g, "")), ""].join("\r\n")); return [...headers, `Content-Type: multipart/mixed; boundary="${mixed}"`, "", `--${mixed}`, `Content-Type: multipart/alternative; boundary="${alternative}"`, "", alternativePart, ...attachmentParts, `--${mixed}--`].filter(Boolean).join("\r\n"); }
async function scheduled(): Promise<ScheduledDraft[]> { return scheduleStore.load(); }
async function saveScheduled(items: ScheduledDraft[]) { await scheduleStore.save(items); }
function heuristic(thread: MailThread) { return { summary: `${thread.latest.from || "A contact"} wrote about “${thread.latest.subject}”. ${thread.latest.snippet}`.trim(), suggestedReply: thread.needsReply ? `Hi,\n\nThanks for reaching out about ${thread.latest.subject}. I’ve reviewed your note and will follow up with the next step shortly.\n\nBest,\nEllis AI Studio` : "" }; }
async function plutoQuery(query: string) { const key = process.env.OPENAI_API_KEY; if (!key) return query; const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini", input: `Convert this natural-language request into a Gmail search query only. Preserve names, companies, and dates. Request: ${query}` }), signal: AbortSignal.timeout(15_000) }); const body = await response.json() as { output_text?: string }; return response.ok && body.output_text ? body.output_text.trim().replace(/^['"]|['"]$/g, "") : query; }

export const googleAuthService = new GoogleAuthService();
export const gmailService = new GmailService();
export const threadService = new ThreadService();
export const draftService = new DraftService();
export const searchService = new SearchService();
export const notificationService = new NotificationService();
export const plutoEmailService = new PlutoEmailService();
