import { getRequestHeader } from "@tanstack/react-start/server";
import { loadLocalEnvironment } from "~/lib/local-env.server";
import { createEncryptedJsonStore, createSignedState, validateSignedState } from "~/lib/oauth-framework.server";
import { listContent } from "~/lib/content-library.server";
import { readFile, rename, writeFile } from "node:fs/promises";
import { mkdir } from "node:fs/promises";

loadLocalEnvironment();

const tokenPath = process.env.GOOGLE_CALENDAR_TOKEN_STORE_PATH ?? ".data/google-calendar.json";
const syncPath = ".data/google-calendar-sync.json";
const scope = "https://www.googleapis.com/auth/calendar.events";
type Token = { accessToken: string; refreshToken: string; expiresAt: number; email?: string };
type SyncStore = Record<string, string>;
const tokenStore = createEncryptedJsonStore<Token | undefined>({ path: tokenPath, encryptionSecret: () => required("GOOGLE_CALENDAR_TOKEN_ENCRYPTION_KEY"), empty: () => undefined });

function required(name: string) { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured.`); return value; }
function configured() { return ["GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET", "GOOGLE_CALENDAR_OAUTH_REDIRECT_URI", "GOOGLE_OAUTH_STATE_SECRET", "GOOGLE_CALENDAR_TOKEN_ENCRYPTION_KEY"].every((name) => Boolean(process.env[name])); }
function localDevelopment() { return process.env.NODE_ENV !== "production"; }
function allowed() { if (localDevelopment()) return true; const expected = process.env.GOOGLE_CALENDAR_DASHBOARD_ACCESS_TOKEN; const cookie = (getRequestHeader("cookie") ?? "").split(";").map((part) => part.trim()).find((part) => part.startsWith("ellis_calendar_dashboard="))?.slice("ellis_calendar_dashboard=".length); return Boolean(expected && cookie === expected); }
function access() { if (!allowed()) throw new Error("Dashboard access is required."); }
async function syncStore(): Promise<SyncStore> { try { return JSON.parse(await readFile(syncPath, "utf8")) as SyncStore; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return {}; throw error; } }
async function saveSync(value: SyncStore) { await mkdir(".data", { recursive: true }); const temporary = `${syncPath}.${crypto.randomUUID()}.tmp`; await writeFile(temporary, JSON.stringify(value, null, 2), { mode: 0o600 }); await rename(temporary, syncPath); }

export async function connection() { if (!configured()) return { configured: false, connected: false, message: "Google Calendar configuration is incomplete." }; const token = await tokenStore.load(); return { configured: true, connected: Boolean(token), email: token?.email, expiresAt: token?.expiresAt }; }
export function authorizationUrl() { access(); if (!configured()) throw new Error("Google Calendar configuration is incomplete."); const url = new URL("https://accounts.google.com/o/oauth2/v2/auth"); url.search = new URLSearchParams({ client_id: required("GOOGLE_OAUTH_CLIENT_ID"), redirect_uri: required("GOOGLE_CALENDAR_OAUTH_REDIRECT_URI"), response_type: "code", scope, access_type: "offline", prompt: "consent", state: createSignedState(required("GOOGLE_OAUTH_STATE_SECRET")) }).toString(); return url.toString(); }
export async function completeAuthorization(code: string, state: string) { access(); validateSignedState(state, required("GOOGLE_OAUTH_STATE_SECRET")); const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: required("GOOGLE_OAUTH_CLIENT_ID"), client_secret: required("GOOGLE_OAUTH_CLIENT_SECRET"), redirect_uri: required("GOOGLE_CALENDAR_OAUTH_REDIRECT_URI"), grant_type: "authorization_code" }) }); const data = await response.json() as { access_token?: string; refresh_token?: string; expires_in?: number; error_description?: string }; if (!response.ok || !data.access_token || !data.refresh_token || !data.expires_in) throw new Error(data.error_description ?? "Google Calendar authorization failed."); const profile = await fetch("https://www.googleapis.com/oauth2/v3/userinfo", { headers: { Authorization: `Bearer ${data.access_token}` } }); const profileData = await profile.json() as { email?: string }; await tokenStore.save({ accessToken: data.access_token, refreshToken: data.refresh_token, expiresAt: Date.now() + data.expires_in * 1000, email: profileData.email }); return { email: profileData.email }; }
async function active() { const token = await tokenStore.load(); if (!token) throw new Error("Connect Google Calendar first."); if (token.expiresAt > Date.now() + 60_000) return token; const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: required("GOOGLE_OAUTH_CLIENT_ID"), client_secret: required("GOOGLE_OAUTH_CLIENT_SECRET"), refresh_token: token.refreshToken, grant_type: "refresh_token" }) }); const data = await response.json() as { access_token?: string; expires_in?: number; error_description?: string }; if (!response.ok || !data.access_token || !data.expires_in) throw new Error(data.error_description ?? "Google Calendar token refresh failed."); const refreshed = { ...token, accessToken: data.access_token, expiresAt: Date.now() + data.expires_in * 1000 }; await tokenStore.save(refreshed); return refreshed; }
export async function syncContentCalendar() { access(); const token = await active(); const content = (await listContent()).filter((item) => item.topic === "linkedin" && item.scheduledFor && !item.published); const synced = await syncStore(); let created = 0; for (const item of content) { if (synced[item.id]) continue; const start = new Date(item.scheduledFor!); const end = new Date(start.getTime() + 15 * 60_000); const response = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events", { method: "POST", headers: { Authorization: `Bearer ${token.accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ summary: `LinkedIn: ${item.title}`, description: `${item.body}\n\nManaged in Ellis AI Studio Content OS.`, start: { dateTime: start.toISOString(), timeZone: "America/Los_Angeles" }, end: { dateTime: end.toISOString(), timeZone: "America/Los_Angeles" }, extendedProperties: { private: { contentOsId: item.id } } }) }); const event = await response.json() as { id?: string; error?: { message?: string } }; if (!response.ok || !event.id) throw new Error(event.error?.message ?? "Google Calendar event creation failed."); synced[item.id] = event.id; created++; } await saveSync(synced); return { created, existing: content.length - created, total: content.length }; }
