import { createEncryptedJsonStore } from "~/lib/oauth-framework.server";

const tokenPath = process.env.GOOGLE_CALENDAR_TOKEN_STORE_PATH ?? ".data/google-calendar.json";
type Token = { accessToken: string; refreshToken: string; expiresAt: number; email?: string; formsEnabled?: boolean };
const required = (name: string) => { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured.`); return value; };
const store = createEncryptedJsonStore<Token | undefined>({ path: tokenPath, encryptionSecret: () => required("GOOGLE_CALENDAR_TOKEN_ENCRYPTION_KEY"), empty: () => undefined });
async function active() { const current = await store.load(); if (!current) throw new Error("Connect Google Workspace before creating the assessment."); if (current.expiresAt > Date.now() + 60_000) return current; const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: required("GOOGLE_OAUTH_CLIENT_ID"), client_secret: required("GOOGLE_OAUTH_CLIENT_SECRET"), refresh_token: current.refreshToken, grant_type: "refresh_token" }) }); const data = await response.json() as { access_token?: string; expires_in?: number; error_description?: string }; if (!response.ok || !data.access_token || !data.expires_in) throw new Error(data.error_description ?? "Google Workspace token refresh failed."); const next = { ...current, accessToken: data.access_token, expiresAt: Date.now() + data.expires_in * 1000 }; await store.save(next); return next; }
type Kind = "short" | "long" | "dropdown" | "checkbox" | "radio";
type Question = { title: string; description?: string; required?: boolean; kind: Kind; choices?: string[] };
const q = (title: string, kind: Kind, options: Omit<Partial<Question>, "title" | "kind"> = {}): Question => ({ title, kind, ...options });
const sections: Array<{ title: string; description?: string; questions: Question[] }> = [
  { title: "Business Information", questions: [q("Full Name", "short", { required: true }), q("Business Name", "short", { required: true }), q("Job Title", "dropdown", { choices: ["Owner", "CEO", "President", "Founder", "Operations Manager", "Marketing Manager", "Sales Manager", "IT Manager", "Department Head", "Other"] }), q("Email", "short", { required: true }), q("Phone Number", "short"), q("Number of Employees", "dropdown", { choices: ["Just Me", "2-5", "6-10", "11-25", "26-50", "51-100", "101-250", "250+"] }), q("Approximate Annual Revenue", "dropdown", { choices: ["Startup / Pre-Revenue", "Under $100k", "$100k-$500k", "$500k-$1M", "$1M-$5M", "$5M-$10M", "$10M+"] }), q("Who is the primary decision-maker for this project?", "dropdown", { choices: ["Myself", "Business Partner", "Executive Team", "Board", "Department Manager", "Other"] }), q("Besides yourself, who else will be involved in approving this project?", "long")] },
  { title: "Business Presence", description: "Provide links that help us understand your business, including websites, social profiles, listings, customer portals, booking systems, directories, and public-facing profiles.", questions: [q("Business Profile URL", "short"), q("Additional Business Profile URLs", "long", { description: "Add one URL per line." })] },
  { title: "About Your Business", questions: [q("Tell us about your business.", "long", { required: true }), q("Tell us about yourself.", "long")] },
  { title: "Business Assessment", questions: [q("Which area of your business would benefit the most from improvement?", "dropdown", { choices: ["Marketing", "Lead Generation", "Sales", "Customer Service", "Operations", "Employee Productivity", "Finance & Reporting", "Technology", "Human Resources", "Inventory Management", "Compliance", "Other"] }), q("Please describe the challenge in detail.", "long", { description: "What is happening today? How is it affecting your business? What would happen if nothing changed?", required: true })] },
  { title: "Current Infrastructure", questions: [q("Which systems does your business currently use?", "checkbox", { choices: ["Website", "CRM", "Email Marketing", "Scheduling", "Accounting", "Project Management", "Customer Support", "E-Commerce", "Inventory", "Automation Software", "AI Tools", "Internal Knowledge Base", "APIs / Integrations", "Other"] }), q("Which software do you currently use?", "long", { description: "Examples: Salesforce, HubSpot, QuickBooks, Google Workspace, Microsoft 365, Shopify, Monday.com, ClickUp, Notion, etc." })] },
  { title: "Future Goals", questions: [q("If we met again one year from today, what would success look like?", "long", { required: true }), q("What would a successful solution accomplish within the next 6-12 months?", "long")] },
  { title: "Investment", questions: [q("What investment range have you allocated for solving this challenge?", "radio", { choices: ["Still Exploring", "Under $500", "$500-$2,000", "$2,000-$5,000", "$5,000-$10,000", "$10,000-$25,000", "$25,000+", "I'm not sure - I need a recommendation."] })] },
  { title: "Timeline", questions: [q("When would you like to begin?", "radio", { choices: ["Immediately", "Within 30 Days", "1-3 Months", "3-6 Months", "6-12 Months", "Just Gathering Information"] })] },
  { title: "Final Question", questions: [q("If you could automate one thing in your business tomorrow, what would it be?", "long", { required: true })] },
];
function createQuestionItem(question: Question) { const item: { title: string; description?: string; questionItem: { question: Record<string, unknown> } } = { title: question.title, description: question.description, questionItem: { question: { required: Boolean(question.required) } } }; if (question.kind === "short" || question.kind === "long") item.questionItem.question.textQuestion = { paragraph: question.kind === "long" }; else item.questionItem.question.choiceQuestion = { type: question.kind === "dropdown" ? "DROP_DOWN" : question.kind === "checkbox" ? "CHECKBOX" : "RADIO", options: (question.choices ?? []).map(value => ({ value })) }; return item; }
export async function connection() { const token = await store.load(); return { connected: Boolean(token?.formsEnabled), email: token?.email }; }
export async function createInfrastructureAssessment() { const token = await active(); const call = async (url: string, init: RequestInit) => { const response = await fetch(url, { ...init, headers: { Authorization: `Bearer ${token.accessToken}`, "Content-Type": "application/json" } }); const body = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String((body.error as { message?: string } | undefined)?.message ?? "Google Forms request failed.")); return body; }; const title = "Ellis AI Studio - AI Infrastructure Assessment"; const form = await call("https://forms.googleapis.com/v1/forms", { method: "POST", body: JSON.stringify({ info: { title, documentTitle: title } }) }); const formId = String(form.formId); const requests: Array<Record<string, unknown>> = [{ updateFormInfo: { info: { description: "Estimated Time: 5-10 Minutes\n\nComplete this assessment before your consultation so our AI can begin analyzing your business infrastructure and identify opportunities before we meet." }, updateMask: "description" } }]; let index = 0; for (const section of sections) { if (index > 0) { requests.push({ createItem: { item: { title: section.title, description: section.description, pageBreakItem: {} }, location: { index } } }); index++; } for (const question of section.questions) requests.push({ createItem: { item: createQuestionItem(question), location: { index: index++ } } }); } await call(`https://forms.googleapis.com/v1/forms/${formId}:batchUpdate`, { method: "POST", body: JSON.stringify({ requests }) }); return { formId, editUrl: `https://docs.google.com/forms/d/${formId}/edit`, responderUrl: String(form.responderUri ?? `https://docs.google.com/forms/d/e/${formId}/viewform`) }; }
