import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { loadLocalEnvironment } from "~/lib/local-env.server";

loadLocalEnvironment();

const storePath = process.env.GROWTH_ENGINE_STORE_PATH ?? ".data/growth-engine.json";
export type CampaignType = "portfolio" | "demo" | "service" | "educational" | "promotion" | "case-study" | "announcement" | "brand-awareness";
export type CreativePackage = { status: "concepts_ready"; concepts: Record<string, string>; createdAt: number };
export type Campaign = { id: string; pageUrl: string; title: string; type: CampaignType; summary: string; sourceHash: string; status: "pending_approval" | "approved"; createdAt: number; content: Record<string, string>; imagePrompts: string[]; hashtags: string[]; cta: string; schedule: string[]; creative?: CreativePackage };
type Snapshot = { url: string; hash: string; title: string; text: string; updatedAt: number };
type Store = { snapshots: Snapshot[]; campaigns: Campaign[] };

async function read(): Promise<Store> { try { return JSON.parse(await readFile(storePath, "utf8")) as Store; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { snapshots: [], campaigns: [] }; throw error; } }
async function write(store: Store) { await mkdir(dirname(storePath), { recursive: true }); await writeFile(`${storePath}.tmp`, JSON.stringify(store, null, 2), { mode: 0o600 }); await rename(`${storePath}.tmp`, storePath); }
function text(html: string) { return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim(); }
function classify(url: string, title: string, body: string): CampaignType { const source = `${url} ${title} ${body}`.toLowerCase(); if (/case stud/.test(source)) return "case-study"; if (/portfolio/.test(source)) return "portfolio"; if (/demo/.test(source)) return "demo"; if (/service/.test(source)) return "service"; if (/blog|guide|learn|how to/.test(source)) return "educational"; if (/launch|announc|new /.test(source)) return "announcement"; return "brand-awareness"; }
function fallback(title: string, type: CampaignType, summary: string) { const cta = "See how Ellis builds practical growth systems."; return { summary, content: { instagram: `${title}\n\n${summary}\n\n${cta}`, facebook: `${title}\n\n${summary}\n\n${cta}`, linkedin: `${title}\n\n${summary}\n\nBuilt for clearer acquisition, stronger conversion, and more efficient operations. ${cta}`, xThread: `1/ ${title}\n\n2/ ${summary}\n\n3/ ${cta}`, threads: `${title} — ${summary} ${cta}`, tiktok: `Hook: ${title}.\nProblem: businesses need systems, not more busywork.\nValue: ${summary}\nCTA: ${cta}`, youtubeCommunity: `${title}\n\n${summary}\n\n${cta}` }, imagePrompts: [`Editorial brand image for ${title}; confident, practical business growth system; clean studio composition`, `Modern diagrammatic visual showing a ${type} growth system for ${title}; Ellis AI Studio brand tone`, `Premium social campaign image for ${title}; clear outcome, restrained typography, no generic AI imagery`], hashtags: ["#GrowthSystems", "#BusinessAutomation", "#ClientAcquisition"], cta, schedule: ["LinkedIn: Tuesday 9:00 AM local", "Instagram/Facebook: Wednesday 11:00 AM local", "X/Threads: Thursday 10:00 AM local", "TikTok/YouTube Community: Friday 12:00 PM local"] }; }
async function generate(title: string, type: CampaignType, source: string) { const key = process.env.OPENAI_API_KEY; const summary = source.slice(0, 700); if (!key) return fallback(title, type, summary); const prompt = `Return JSON only with summary, instagram, facebook, linkedin, xThread, threads, tiktok, youtubeCommunity, imagePrompts (3 strings), hashtags (array), cta, schedule (array). Ellis AI Studio designs AI-powered growth systems that help businesses acquire customers, convert leads, and operate efficiently. Be confident, specific, business-focused; avoid generic AI marketing language. Source: ${source.slice(0, 6000)}`;
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini", input: prompt }) }); const body = await response.json() as { output_text?: string; error?: { message?: string } }; if (!response.ok || !body.output_text) throw new Error(body.error?.message ?? "Campaign generation failed."); const result = JSON.parse(body.output_text) as Record<string, unknown>; return { summary: String(result.summary), content: { instagram: String(result.instagram), facebook: String(result.facebook), linkedin: String(result.linkedin), xThread: String(result.xThread), threads: String(result.threads), tiktok: String(result.tiktok), youtubeCommunity: String(result.youtubeCommunity) }, imagePrompts: Array.isArray(result.imagePrompts) ? result.imagePrompts.map(String).slice(0, 3) : [], hashtags: Array.isArray(result.hashtags) ? result.hashtags.map(String) : [], cta: String(result.cta), schedule: Array.isArray(result.schedule) ? result.schedule.map(String) : [] }; }
export async function scan(url: string) { const parsed = new URL(url); if (parsed.protocol !== "https:") throw new Error("Use a public HTTPS page URL."); const response = await fetch(parsed, { headers: { "User-Agent": "Ellis-Growth-Engine/1.0" } }); if (!response.ok) throw new Error(`Website scan failed (${response.status}).`); const html = await response.text(); const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g, " ").trim() || parsed.pathname; const body = text(html); const hash = createHash("sha256").update(`${title}\n${body}`).digest("hex"); const store = await read(); if (store.snapshots.find((item) => item.url === url)?.hash === hash) return { changed: false, campaign: store.campaigns.find((item) => item.pageUrl === url && item.sourceHash === hash) };
  const type = classify(url, title, body); const generated = await generate(title, type, body); const campaign: Campaign = { id: crypto.randomUUID(), pageUrl: url, title, type, sourceHash: hash, status: "pending_approval", createdAt: Date.now(), ...generated }; store.snapshots = [{ url, hash, title, text: body.slice(0, 12000), updatedAt: Date.now() }, ...store.snapshots.filter((item) => item.url !== url)].slice(0, 100); store.campaigns.unshift(campaign); await write(store); return { changed: true, campaign }; }
export async function dashboard() { const store = await read(); return { campaigns: store.campaigns.slice(0, 30) }; }
function creative(campaign: Campaign): CreativePackage { const base = `Premium modern minimal Ellis AI Studio visual. Campaign: ${campaign.title}. Business value: ${campaign.summary}. CTA: ${campaign.cta}. Generous negative space, editorial typography, deep ink and warm ivory, restrained accent; no robots, brains, neon circuits, or generic AI imagery.`; return { status: "concepts_ready", createdAt: Date.now(), concepts: { hero: `${base} Hero promotional graphic, 16:9.`, instagramCarousel: `${base} Instagram 5-slide carousel: problem, insight, system, proof, CTA.`, linkedInCarousel: `${base} LinkedIn executive 6-slide carousel with evidence-led hierarchy.`, facebook: `${base} Facebook promotional graphic, 1.91:1.`, story: `${base} Vertical story graphic, 9:16, one outcome and CTA.`, x: `${base} X graphic, 16:9, concise insight.`, youtubeThumbnail: `${base} YouTube Community thumbnail concept, 16:9, one clear outcome.`, ad: `${base} Paid ad concept with focused offer and CTA.`, beforeAfter: `${base} Before/after comparison layout with measured transformation.`, portfolio: `${base} Portfolio showcase layout with project context and outcome.`, caseStudy: `${base} Case study graphic with challenge, system, result.` } }; }
export async function approveAndCreateCreative(id: string) { const store = await read(); const campaign = store.campaigns.find((item) => item.id === id); if (!campaign) throw new Error("Campaign was not found."); campaign.status = "approved"; campaign.creative = creative(campaign); await write(store); return campaign; }
