import { isEllisSystemKey } from "~/lib/lead-taxonomy";
import { PROBLEM_CATEGORIES, type LeadInterpretation } from "~/types/lead";

const strings = (value: unknown, limit = 8): string[] => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").map((item) => item.trim()).filter(Boolean).slice(0, limit) : [];
export function parseLeadInterpretation(value: unknown): LeadInterpretation {
  if (!value || typeof value !== "object") throw new Error("AI interpretation was malformed."); const data = value as Record<string, unknown>;
  const category = data.primaryProblemCategory; if (typeof category !== "string" || !PROBLEM_CATEGORIES.includes(category as never)) throw new Error("AI interpretation has an invalid problem category.");
  const system = data.recommendedSystem as Record<string, unknown> | undefined; if (!system || typeof system.key !== "string" || !isEllisSystemKey(system.key) || typeof system.name !== "string" || typeof system.rationale !== "string") throw new Error("AI interpretation has an invalid system recommendation.");
  const problems = Array.isArray(data.identifiedProblems) ? data.identifiedProblems.slice(0, 5).map((item) => { const p = item as Record<string, unknown>; if (!p || typeof p.title !== "string" || typeof p.description !== "string" || !["user_confirmed", "audit_observed", "audit_inferred"].includes(String(p.evidenceType))) throw new Error("AI interpretation has invalid evidence."); return { title: p.title, description: p.description, evidence: strings(p.evidence, 5), evidenceType: p.evidenceType as "user_confirmed" | "audit_observed" | "audit_inferred" }; }) : [];
  for (const key of ["summary", "reasoningSummary"] as const) if (typeof data[key] !== "string" || !data[key].trim()) throw new Error("AI interpretation is incomplete.");
  return { summary: (data.summary as string).trim(), primaryProblemCategory: category as LeadInterpretation["primaryProblemCategory"], secondaryProblemCategories: strings(data.secondaryProblemCategories).filter((item): item is LeadInterpretation["primaryProblemCategory"] => PROBLEM_CATEGORIES.includes(item as never)), identifiedProblems: problems, recommendedSystem: { key: system.key, name: system.name.trim(), rationale: system.rationale.trim() }, intentSignals: strings(data.intentSignals), impactSignals: strings(data.impactSignals), urgencySignals: strings(data.urgencySignals), implementationSignals: strings(data.implementationSignals), uncertainty: strings(data.uncertainty), discoveryQuestions: strings(data.discoveryQuestions, 6), reasoningSummary: (data.reasoningSummary as string).trim() };
}
