import { Pool } from "pg";
import type { LeadActivity, LeadAnalysisStatus, LeadIntake, LeadInterpretation, LeadScores, PipelineStatus, RecommendedNextAction } from "~/types/lead";

let pool: Pool | undefined;
function database() { if (!pool) { const connectionString = process.env.SUPABASE_DATABASE_URL; if (!connectionString) throw new Error("SUPABASE_DATABASE_URL is not configured."); pool = new Pool({ connectionString, max: 1, idleTimeoutMillis: 5_000, connectionTimeoutMillis: 10_000 }); } return pool; }
export type StoredLead = LeadIntake & { id: string; createdAt: string; updatedAt: string; pipelineStatus: PipelineStatus; analysisStatus: LeadAnalysisStatus };
export async function createLead(input: LeadIntake): Promise<{ lead: StoredLead; duplicate: boolean }> {
  const values = [input.source, input.firstName, input.lastName, input.email, input.phone ?? null, input.businessName, input.website ?? null, input.industry ?? null, input.location ?? null, input.primaryChallenge, input.desiredOutcome, input.urgency, input.additionalContext ?? null, JSON.stringify({ businessSize: input.businessSize, approximateMonthlyLeadVolume: input.approximateMonthlyLeadVolume, currentTools: input.currentTools, currentProcess: input.currentProcess, biggestManualBottleneck: input.biggestManualBottleneck }), input.auditContext ? JSON.stringify(input.auditContext) : null, input.requestId];
  const inserted = await database().query(`insert into public.leads (source,first_name,last_name,email,phone,business_name,website,industry,location,primary_challenge,desired_outcome,urgency,additional_context,operational_context,audit_context,idempotency_key) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15::jsonb,$16) on conflict (idempotency_key) do nothing returning id,created_at,updated_at,pipeline_status,analysis_status`, values);
  if (inserted.rowCount) { const row = inserted.rows[0]; return { duplicate: false, lead: { ...input, id: row.id, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString(), pipelineStatus: row.pipeline_status, analysisStatus: row.analysis_status } }; }
  const existing = await database().query(`select id,created_at,updated_at,pipeline_status,analysis_status from public.leads where idempotency_key = $1`, [input.requestId]); if (!existing.rowCount) throw new Error("Lead could not be created."); const row = existing.rows[0]; return { duplicate: true, lead: { ...input, id: row.id, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString(), pipelineStatus: row.pipeline_status, analysisStatus: row.analysis_status } };
}
export async function updateAnalysisStatus(leadId: string, status: LeadAnalysisStatus) { await database().query(`update public.leads set analysis_status=$2, updated_at=now() where id=$1`, [leadId, status]); }
export async function addActivity(leadId: string, type: string, metadata?: Record<string, unknown>) { await database().query(`insert into public.lead_activities (lead_id,type,metadata) values ($1,$2,$3::jsonb)`, [leadId, type, metadata ? JSON.stringify(metadata) : null]); }
export async function saveAnalysis(leadId: string, interpretation: LeadInterpretation, scores: LeadScores, action: RecommendedNextAction) { await database().query(`insert into public.lead_analyses (lead_id,interpretation,recommended_system_key,recommended_next_action,problem_fit,potential_impact,urgency_score,implementation_fit,intent,opportunity_score,qualification_confidence,qualification_class) values ($1,$2::jsonb,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`, [leadId, JSON.stringify(interpretation), interpretation.recommendedSystem.key, action, scores.problemFit, scores.potentialImpact, scores.urgency, scores.implementationFit, scores.intent, scores.opportunityScore, scores.qualificationConfidence, scores.qualificationClass]); await updateAnalysisStatus(leadId, "complete"); }
export async function updatePipelineStatus(leadId: string, status: PipelineStatus) { await database().query(`update public.leads set pipeline_status=$2, updated_at=now() where id=$1`, [leadId, status]); await addActivity(leadId, "status_changed", { status }); }
export async function listLeads() { const result = await database().query(`select l.id,l.created_at,l.business_name,l.first_name,l.last_name,l.email,l.pipeline_status,l.analysis_status,a.opportunity_score,a.qualification_confidence,a.qualification_class,a.recommended_system_key from public.leads l left join lateral (select * from public.lead_analyses where lead_id=l.id order by created_at desc limit 1) a on true order by l.created_at desc limit 200`); return result.rows; }
export async function getLead(leadId: string) { const lead = await database().query(`select * from public.leads where id=$1`, [leadId]); if (!lead.rowCount) return null; const analysis = await database().query(`select * from public.lead_analyses where lead_id=$1 order by created_at desc limit 1`, [leadId]); const activities = await database().query(`select id,lead_id,type,created_at from public.lead_activities where lead_id=$1 order by created_at asc`, [leadId]); return { lead: lead.rows[0], analysis: analysis.rows[0] ?? null, activities: activities.rows.map((row): LeadActivity => ({ id: row.id, leadId: row.lead_id, type: row.type, createdAt: row.created_at.toISOString() })) }; }
