import { createHmac, randomBytes, timingSafeEqual, webcrypto } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { getRequestHeader, setResponseHeader } from "@tanstack/react-start/server";
import { loadLocalEnvironment } from "~/lib/local-env.server";
import type { SocialConnection, SocialPost, SocialProvider } from "~/lib/social-provider";
loadLocalEnvironment();
const storePath = process.env.LINKEDIN_TOKEN_STORE_PATH ?? ".data/linkedin.json";
type Token = { accessToken: string; refreshToken?: string; expiresAt: number; personUrn: string; name?: string };
function req(name: string) { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured.`); return value; }
function ready() { return ["LINKEDIN_CLIENT_ID","LINKEDIN_CLIENT_SECRET","LINKEDIN_OAUTH_REDIRECT_URI","LINKEDIN_OAUTH_STATE_SECRET","LINKEDIN_TOKEN_ENCRYPTION_KEY","LINKEDIN_DASHBOARD_ACCESS_TOKEN"].every((x) => Boolean(process.env[x])); }
function cookie(name: string) { return (getRequestHeader("cookie") ?? "").split(";").map((x) => x.trim()).find((x) => x.startsWith(`${name}=`))?.slice(name.length + 1); }
function allowed() { const e = process.env.LINKEDIN_DASHBOARD_ACCESS_TOKEN, a = cookie("ellis_linkedin_dashboard"); return Boolean(e && a && e.length === a.length && timingSafeEqual(Buffer.from(e),Buffer.from(a))); }
function access() { if (!allowed()) throw new Error("Dashboard access is required."); }
function b64(v: Uint8Array | string) { return Buffer.from(v).toString("base64url"); }
function stateSig(v: string) { return createHmac("sha256",req("LINKEDIN_OAUTH_STATE_SECRET")).update(v).digest("base64url"); }
async function key() { const d = await webcrypto.subtle.digest("SHA-256",new TextEncoder().encode(req("LINKEDIN_TOKEN_ENCRYPTION_KEY"))); return webcrypto.subtle.importKey("raw",d,"AES-GCM",false,["encrypt","decrypt"]); }
async function load(): Promise<Token|undefined> { try { const e=JSON.parse(await readFile(storePath,"utf8")); const p=await webcrypto.subtle.decrypt({name:"AES-GCM",iv:Buffer.from(e.iv,"base64url")},await key(),Buffer.from(e.ciphertext,"base64url")); return JSON.parse(new TextDecoder().decode(p)); } catch (e) { if ((e as NodeJS.ErrnoException).code === "ENOENT") return; throw new Error("The encrypted LinkedIn token store could not be read."); } }
async function save(token: Token) { const iv=randomBytes(12), c=await webcrypto.subtle.encrypt({name:"AES-GCM",iv},await key(),new TextEncoder().encode(JSON.stringify(token))); await mkdir(dirname(storePath),{recursive:true}); await writeFile(`${storePath}.tmp`,JSON.stringify({iv:b64(iv),ciphertext:b64(new Uint8Array(c))}),{mode:0o600}); await rename(`${storePath}.tmp`,storePath); }
export function unlock(accessToken: string) { const expected=req("LINKEDIN_DASHBOARD_ACCESS_TOKEN"); if(accessToken.length!==expected.length||!timingSafeEqual(Buffer.from(accessToken),Buffer.from(expected))) throw new Error("Dashboard access was denied."); setResponseHeader("Set-Cookie",`ellis_linkedin_dashboard=${encodeURIComponent(expected)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`); }
export function authorizationUrl() { access(); if(!ready()) throw new Error("LinkedIn is not configured."); const payload=b64(JSON.stringify({nonce:b64(randomBytes(16)),expiresAt:Date.now()+600000})), state=`${payload}.${stateSig(payload)}`, url=new URL("https://www.linkedin.com/oauth/v2/authorization"); url.search=new URLSearchParams({response_type:"code",client_id:req("LINKEDIN_CLIENT_ID"),redirect_uri:req("LINKEDIN_OAUTH_REDIRECT_URI"),state,scope:"openid profile w_member_social"}).toString(); return url.toString(); }
async function tokenRequest(data: Record<string,string>) { const r=await fetch("https://www.linkedin.com/oauth/v2/accessToken",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(data)}), b=await r.json() as {access_token?:string;expires_in?:number;refresh_token?:string;error_description?:string}; if(!r.ok||!b.access_token) throw new Error(b.error_description??"LinkedIn token exchange failed."); return { accessToken: b.access_token, expiresIn: b.expires_in, refreshToken: b.refresh_token }; }
export async function completeAuthorization(code:string,state:string) { access(); const [p,s]=state.split("."); if(!code||!p||!s||s.length!==stateSig(p).length||!timingSafeEqual(Buffer.from(s),Buffer.from(stateSig(p)))) throw new Error("LinkedIn OAuth state validation failed."); const parsed=JSON.parse(Buffer.from(p,"base64url").toString()) as {expiresAt?:number}; if(!parsed.expiresAt||parsed.expiresAt<Date.now()) throw new Error("LinkedIn OAuth state expired."); const b=await tokenRequest({grant_type:"authorization_code",code,redirect_uri:req("LINKEDIN_OAUTH_REDIRECT_URI"),client_id:req("LINKEDIN_CLIENT_ID"),client_secret:req("LINKEDIN_CLIENT_SECRET")}); const me=await fetch("https://api.linkedin.com/v2/userinfo",{headers:{Authorization:`Bearer ${b.accessToken}`}}); const user=await me.json() as {sub?:string;name?:string}; if(!me.ok||!user.sub) throw new Error("LinkedIn profile lookup failed."); await save({accessToken:b.accessToken,refreshToken:b.refreshToken,expiresAt:Date.now()+Number(b.expiresIn??0)*1000,personUrn:`urn:li:person:${user.sub}`,name:user.name}); }
async function active() { const t=await load(); if(!t) throw new Error("No LinkedIn account is connected."); if(t.expiresAt<=Date.now()+60000) { if(!t.refreshToken) throw new Error("LinkedIn token expired. Reconnect LinkedIn."); const b=await tokenRequest({grant_type:"refresh_token",refresh_token:t.refreshToken,client_id:req("LINKEDIN_CLIENT_ID"),client_secret:req("LINKEDIN_CLIENT_SECRET")}); t.accessToken=b.accessToken;t.refreshToken=b.refreshToken??t.refreshToken;t.expiresAt=Date.now()+Number(b.expiresIn??0)*1000;await save(t); } return t; }
export async function dashboard(): Promise<SocialConnection & {configured:boolean}> { if(!allowed()) return {provider:"linkedin",connected:false,configured:ready(),message:"Dashboard access required."}; if(!ready()) return {provider:"linkedin",connected:false,configured:false,message:"Add LinkedIn deployment secrets."}; const t=await load(); return {provider:"linkedin",connected:Boolean(t),configured:true,displayName:t?.name,expiresAt:t?.expiresAt}; }
export async function publish(post: SocialPost) { access(); const t=await active(); if(post.image) throw new Error("LinkedIn image publishing requires an upload asset flow; connect an approved LinkedIn image upload provider before publishing images."); const r=await fetch("https://api.linkedin.com/v2/ugcPosts",{method:"POST",headers:{Authorization:`Bearer ${t.accessToken}`,"Content-Type":"application/json","X-Restli-Protocol-Version":"2.0.0"},body:JSON.stringify({author:t.personUrn,lifecycleState:"PUBLISHED",specificContent:{"com.linkedin.ugc.ShareContent":{shareCommentary:{text:post.text},shareMediaCategory:"NONE"}},visibility:{"com.linkedin.ugc.MemberNetworkVisibility":"PUBLIC"}})}); if(!r.ok) throw new Error(`LinkedIn publish failed (${r.status}).`); return {id:r.headers.get("x-restli-id")??"published"}; }
export const linkedinProvider: SocialProvider={connection:async()=>dashboard(),authorizationUrl,completeAuthorization,publish};
