import { timingSafeEqual } from "node:crypto";
import { getRequestHeader, setResponseHeader } from "@tanstack/react-start/server";
import { loadLocalEnvironment } from "~/lib/local-env.server";
import { createEncryptedJsonStore, createOAuthDiagnostics, createSignedState, fingerprint, validateSignedState } from "~/lib/oauth-framework.server";
import type { SocialConnection, SocialPost, SocialProvider } from "~/lib/social-provider";

loadLocalEnvironment();
const storePath = process.env.LINKEDIN_TOKEN_STORE_PATH ?? ".data/linkedin.json";
type Token = { accessToken: string; refreshToken?: string; expiresAt: number; personUrn: string; name?: string };
type CallbackResult = { ok: true } | { ok: false; error: string };

const trace = createOAuthDiagnostics("linkedin", process.env.LINKEDIN_OAUTH_TRACE_PATH ?? ".diagnostics/linkedin-oauth.log");
function req(name: string) { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured.`); return value; }
function ready() { return ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET", "LINKEDIN_OAUTH_REDIRECT_URI", "LINKEDIN_OAUTH_STATE_SECRET", "LINKEDIN_TOKEN_ENCRYPTION_KEY", "LINKEDIN_DASHBOARD_ACCESS_TOKEN"].every((name) => Boolean(process.env[name])); }
function cookie(name: string) { return (getRequestHeader("cookie") ?? "").split(";").map((part) => part.trim()).find((part) => part.startsWith(`${name}=`))?.slice(name.length + 1); }
function allowed() { const expected = process.env.LINKEDIN_DASHBOARD_ACCESS_TOKEN; const actual = cookie("ellis_linkedin_dashboard"); return Boolean(expected && actual && expected.length === actual.length && timingSafeEqual(Buffer.from(expected), Buffer.from(actual))); }
function access() { if (!allowed()) throw new Error("Dashboard access is required."); }
const store = createEncryptedJsonStore<Token | undefined>({ path: storePath, encryptionSecret: () => req("LINKEDIN_TOKEN_ENCRYPTION_KEY"), empty: () => undefined });
async function load() { return store.load(); }
async function save(token: Token) { await store.save(token); }

export function unlock(accessToken: string) { const expected = req("LINKEDIN_DASHBOARD_ACCESS_TOKEN"); if (accessToken.length !== expected.length || !timingSafeEqual(Buffer.from(accessToken), Buffer.from(expected))) throw new Error("Dashboard access was denied."); setResponseHeader("Set-Cookie", `ellis_linkedin_dashboard=${encodeURIComponent(expected)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`); }
export function authorizationUrl() { access(); if (!ready()) throw new Error("LinkedIn is not configured."); const state = createSignedState(req("LINKEDIN_OAUTH_STATE_SECRET")); const redirectUri = req("LINKEDIN_OAUTH_REDIRECT_URI"); const url = new URL("https://www.linkedin.com/oauth/v2/authorization"); url.search = new URLSearchParams({ response_type: "code", client_id: req("LINKEDIN_CLIENT_ID"), redirect_uri: redirectUri, state, scope: "openid profile w_member_social" }).toString(); trace("authorization_url_generated", { redirectUri, stateFingerprint: fingerprint(state), scopes: "openid profile w_member_social" }); return url.toString(); }
async function tokenRequest(data: Record<string, string>) { trace("token_exchange_started", { codeFingerprint: fingerprint(data.code ?? ""), redirectUri: data.redirect_uri }); let response: Response; try { response = await fetch("https://www.linkedin.com/oauth/v2/accessToken", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams(data), signal: AbortSignal.timeout(15_000) }); } catch (reason) { trace("token_exchange_network_failed", { message: reason instanceof Error ? reason.message : "unknown" }); throw new Error("LinkedIn token exchange could not be reached."); } const raw = await response.text(); let body: { access_token?: string; expires_in?: number; refresh_token?: string; error?: string; error_description?: string } = {}; try { body = JSON.parse(raw); } catch { trace("token_exchange_invalid_json", { status: response.status, bodyLength: raw.length }); throw new Error("LinkedIn returned an invalid token response."); } trace("token_exchange_response", { status: response.status, hasAccessToken: Boolean(body.access_token), error: body.error, errorDescription: body.error_description }); if (!response.ok || !body.access_token) throw new Error(body.error_description ?? body.error ?? "LinkedIn token exchange failed."); return { accessToken: body.access_token, expiresIn: body.expires_in, refreshToken: body.refresh_token }; }
export async function completeAuthorization(code: string, state: string) { trace("callback_received", { hasCode: Boolean(code), codeFingerprint: code ? fingerprint(code) : undefined, hasState: Boolean(state), stateFingerprint: state ? fingerprint(state) : undefined }); access(); if (!code) throw new Error("LinkedIn did not return an authorization code."); try { validateSignedState(state, req("LINKEDIN_OAUTH_STATE_SECRET")); } catch (error) { trace("callback_failed", { error: error instanceof Error ? error.message : "state validation failed" }); throw error; } trace("state_validated", { stateFingerprint: fingerprint(state) }); const token = await tokenRequest({ grant_type: "authorization_code", code, redirect_uri: req("LINKEDIN_OAUTH_REDIRECT_URI"), client_id: req("LINKEDIN_CLIENT_ID"), client_secret: req("LINKEDIN_CLIENT_SECRET") }); trace("profile_lookup_started"); let response: Response; try { response = await fetch("https://api.linkedin.com/v2/userinfo", { headers: { Authorization: `Bearer ${token.accessToken}` }, signal: AbortSignal.timeout(15_000) }); } catch (reason) { trace("callback_failed", { error: reason instanceof Error ? reason.message : "profile lookup failed" }); throw new Error("LinkedIn profile lookup could not be reached."); } const raw = await response.text(); let user: { sub?: string; name?: string }; try { user = JSON.parse(raw); } catch { throw new Error("LinkedIn returned an invalid profile response."); } trace("profile_lookup_completed", { status: response.status, hasSubject: Boolean(user.sub) }); if (!response.ok || !user.sub) throw new Error("LinkedIn profile lookup failed."); const expiresAt = Date.now() + Number(token.expiresIn ?? 0) * 1000; await save({ accessToken: token.accessToken, refreshToken: token.refreshToken, expiresAt, personUrn: `urn:li:person:${user.sub}`, name: user.name }); trace("token_persisted", { expiresAt }); trace("connection_persisted", { expiresAt }); }
export async function finishCallback(code: string, state: string): Promise<CallbackResult> { try { await completeAuthorization(code, state); trace("callback_completed"); return { ok: true }; } catch (reason) { const error = reason instanceof Error ? reason.message : "LinkedIn connection failed."; trace("callback_failed", { error }); return { ok: false, error }; } }
export async function disconnect() { access(); await store.clear(); trace("disconnect_completed"); }
async function active() { const token = await load(); if (!token) throw new Error("No LinkedIn account is connected."); if (token.expiresAt <= Date.now() + 60_000) { if (!token.refreshToken) throw new Error("LinkedIn token expired. Reconnect LinkedIn."); const refreshed = await tokenRequest({ grant_type: "refresh_token", refresh_token: token.refreshToken, client_id: req("LINKEDIN_CLIENT_ID"), client_secret: req("LINKEDIN_CLIENT_SECRET") }); token.accessToken = refreshed.accessToken; token.refreshToken = refreshed.refreshToken ?? token.refreshToken; token.expiresAt = Date.now() + Number(refreshed.expiresIn ?? 0) * 1000; await save(token); } return token; }
export async function dashboard(): Promise<SocialConnection & { configured: boolean }> { if (!allowed()) return { provider: "linkedin", connected: false, configured: ready(), message: "Dashboard access required." }; if (!ready()) return { provider: "linkedin", connected: false, configured: false, message: "Add LinkedIn deployment secrets." }; const token = await load(); return { provider: "linkedin", connected: Boolean(token), configured: true, displayName: token?.name, expiresAt: token?.expiresAt }; }
export async function publish(post: SocialPost) { access(); const token = await active(); if (post.image) throw new Error("LinkedIn image publishing requires an upload asset flow; connect an approved LinkedIn image upload provider before publishing images."); const response = await fetch("https://api.linkedin.com/v2/ugcPosts", { method: "POST", headers: { Authorization: `Bearer ${token.accessToken}`, "Content-Type": "application/json", "X-Restli-Protocol-Version": "2.0.0" }, body: JSON.stringify({ author: token.personUrn, lifecycleState: "PUBLISHED", specificContent: { "com.linkedin.ugc.ShareContent": { shareCommentary: { text: post.text }, shareMediaCategory: "NONE" } }, visibility: { "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC" } }) }); if (!response.ok) throw new Error(`LinkedIn publish failed (${response.status}).`); return { id: response.headers.get("x-restli-id") ?? "published" }; }
export const linkedinProvider: SocialProvider = { connection: async () => dashboard(), authorizationUrl, completeAuthorization, publish, disconnect, refreshToken: async () => { access(); await active(); trace("refresh_completed"); } };
