import { createHash, createHmac, randomBytes, timingSafeEqual, webcrypto } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { getRequestHeader, setResponseHeader } from "@tanstack/react-start/server";
import { loadLocalEnvironment } from "~/lib/local-env.server";

loadLocalEnvironment();

const STORE_PATH = process.env.META_TOKEN_STORE_PATH ?? ".data/meta-publishing.json";
const VERSION = process.env.META_GRAPH_API_VERSION ?? "v24.0";
const SCOPES = ["pages_show_list", "pages_read_engagement", "pages_manage_posts", "instagram_basic", "instagram_content_publish"].join(",");
type Account = { id: string; name: string; accessToken: string; instagramId?: string; instagramUsername?: string };
type Media = { url?: string; dataUrl?: string; filename?: string; mimeType?: string };
export type MetaPost = { id: string; caption: string; media: Media[]; targets: Array<"facebook" | "instagram">; status: "draft" | "scheduled" | "published" | "failed"; scheduledFor?: number; createdAt: number; publishedAt?: number; results?: string[]; error?: string; retryCount?: number; lastRetriedAt?: number; lastRetryReason?: string; campaignId?: string };
type Store = { token?: { accessToken: string; expiresAt: number }; accounts: Account[]; selected?: { pageId: string; instagramId?: string }; posts: MetaPost[] };
export type MetaDashboard = { accessRequired: boolean; configured: boolean; connected: boolean; message?: string; accounts: Array<Omit<Account, "accessToken">>; selected?: { pageId: string; instagramId?: string }; posts: MetaPost[] };

function required(name: string) { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured.`); return value; }
const REQUIRED_OAUTH_ENVIRONMENT = ["META_APP_ID", "META_APP_SECRET", "META_OAUTH_REDIRECT_URI", "META_OAUTH_STATE_SECRET", "META_TOKEN_ENCRYPTION_KEY", "META_DASHBOARD_ACCESS_TOKEN"] as const;
function configured() { return REQUIRED_OAUTH_ENVIRONMENT.every((name) => Boolean(process.env[name])); }
function cookie(name: string) { return (getRequestHeader("cookie") ?? "").split(";").map((item) => item.trim()).find((item) => item.startsWith(`${name}=`))?.slice(name.length + 1); }
function allowed() { const expected = process.env.META_DASHBOARD_ACCESS_TOKEN; const actual = cookie("ellis_meta_dashboard"); return Boolean(expected && actual && expected.length === actual.length && timingSafeEqual(Buffer.from(expected), Buffer.from(actual))); }
function requireAccess() { if (!allowed()) throw new Error("Dashboard access is required."); }
export function unlockDashboard(accessToken: string) { const expected = required("META_DASHBOARD_ACCESS_TOKEN"); if (accessToken.length !== expected.length || !timingSafeEqual(Buffer.from(accessToken), Buffer.from(expected))) throw new Error("Dashboard access was denied."); const secure = process.env.NODE_ENV === "production" ? "; Secure" : ""; setResponseHeader("Set-Cookie", `ellis_meta_dashboard=${encodeURIComponent(expected)}; HttpOnly; SameSite=Lax; Path=/${secure}; Max-Age=28800`); }
function b64(value: Uint8Array | string) { return Buffer.from(value).toString("base64url"); }
function sign(value: string) { return createHmac("sha256", required("META_OAUTH_STATE_SECRET")).update(value).digest("base64url"); }
function trace(event: string, data: Record<string, string | number | boolean | undefined> = {}) { console.info("[meta-oauth]", JSON.stringify({ event, at: new Date().toISOString(), ...data })); }
function fingerprint(value: string) { return createHash("sha256").update(value).digest("base64url").slice(0, 12); }
function redirectUri() { const value = required("META_OAUTH_REDIRECT_URI"); const uri = new URL(value); if (uri.pathname !== "/dashboard/meta-callback" || uri.search || uri.hash || (uri.protocol !== "https:" && !(uri.protocol === "http:" && ["localhost", "127.0.0.1"].includes(uri.hostname)))) throw new Error("META_OAUTH_REDIRECT_URI must end exactly in /dashboard/meta-callback and use HTTPS (except local HTTP)."); return uri.toString(); }
async function key() { const digest = await webcrypto.subtle.digest("SHA-256", new TextEncoder().encode(required("META_TOKEN_ENCRYPTION_KEY"))); return webcrypto.subtle.importKey("raw", digest, "AES-GCM", false, ["encrypt", "decrypt"]); }
async function read(): Promise<Store> { try { const item = JSON.parse(await readFile(STORE_PATH, "utf8")) as { iv: string; ciphertext: string }; const plain = await webcrypto.subtle.decrypt({ name: "AES-GCM", iv: Buffer.from(item.iv, "base64url") }, await key(), Buffer.from(item.ciphertext, "base64url")); return JSON.parse(new TextDecoder().decode(plain)) as Store; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { accounts: [], posts: [] }; throw new Error("The encrypted Meta publishing store could not be read."); } }
async function write(store: Store) { const iv = randomBytes(12); const ciphertext = await webcrypto.subtle.encrypt({ name: "AES-GCM", iv }, await key(), new TextEncoder().encode(JSON.stringify(store))); await mkdir(dirname(STORE_PATH), { recursive: true }); await writeFile(`${STORE_PATH}.tmp`, JSON.stringify({ iv: b64(iv), ciphertext: b64(new Uint8Array(ciphertext)) }), { mode: 0o600 }); await rename(`${STORE_PATH}.tmp`, STORE_PATH); }
function graph(path: string) { return `https://graph.facebook.com/${VERSION}/${path.replace(/^\//, "")}`; }
async function graphJson(path: string, init: RequestInit = {}) { const response = await fetch(graph(path), init); const body = await response.json() as { error?: { message?: string; code?: number; error_subcode?: number }; [key: string]: unknown }; trace("graph_response", { path: path.split("?")[0], status: response.status, ok: response.ok }); if (!response.ok || body.error) { const error = body.error; const hint = error?.code === 190 ? " Reconnect Meta because the access token expired or was revoked." : ""; trace("graph_error", { path: path.split("?")[0], code: error?.code, subcode: error?.error_subcode }); throw new Error(`${error?.message ?? `Meta Graph API request failed (${response.status}).`}${hint}`); } return body; }
async function refreshLongLivedToken(store: Store) { if (!store.token) throw new Error("No Meta account is connected."); if (store.token.expiresAt > Date.now() + 7 * 86_400_000) return; const exchange = await graphJson("oauth/access_token?" + new URLSearchParams({ grant_type: "fb_exchange_token", client_id: required("META_APP_ID"), client_secret: required("META_APP_SECRET"), fb_exchange_token: store.token.accessToken })); const accessToken = String(exchange.access_token ?? ""); if (!accessToken) throw new Error("Meta token refresh failed. Reconnect Meta."); store.token = { accessToken, expiresAt: Date.now() + Number(exchange.expires_in ?? 5_184_000) * 1000 }; await write(store); }
export function authorizationUrl() { requireAccess(); if (!configured()) throw new Error("Meta OAuth is not configured. Add the required META deployment secrets first."); const payload = b64(JSON.stringify({ nonce: b64(randomBytes(16)), expiresAt: Date.now() + 600_000 })); const state = `${payload}.${sign(payload)}`; const callback = redirectUri(); const url = new URL("https://www.facebook.com/" + VERSION + "/dialog/oauth"); url.search = new URLSearchParams({ client_id: required("META_APP_ID"), redirect_uri: callback, state, response_type: "code", scope: SCOPES }).toString(); trace("authorization_url_generated", { redirectUri: callback, stateFingerprint: fingerprint(state), scopes: SCOPES, businessLogin: false }); return url.toString(); }
export async function completeAuthorization(code: string, state: string) { requireAccess(); const [payload, signature] = state.split("."); if (!payload || !signature || signature.length !== sign(payload).length || !timingSafeEqual(Buffer.from(signature), Buffer.from(sign(payload)))) throw new Error("OAuth state validation failed."); const decoded = JSON.parse(Buffer.from(payload, "base64url").toString()) as { expiresAt?: number }; if (!decoded.expiresAt || decoded.expiresAt < Date.now()) throw new Error("OAuth state expired. Start the connection again."); const short = await graphJson("oauth/access_token?" + new URLSearchParams({ client_id: required("META_APP_ID"), client_secret: required("META_APP_SECRET"), redirect_uri: required("META_OAUTH_REDIRECT_URI"), code })); const long = await graphJson("oauth/access_token?" + new URLSearchParams({ grant_type: "fb_exchange_token", client_id: required("META_APP_ID"), client_secret: required("META_APP_SECRET"), fb_exchange_token: String(short.access_token) })); const token = String(long.access_token ?? ""); if (!token) throw new Error("Meta did not return an access token."); const pages = await graphJson("me/accounts?fields=id,name,access_token,instagram_business_account{id,username}&access_token=" + encodeURIComponent(token)) as { data?: Array<{ id: string; name: string; access_token: string; instagram_business_account?: { id: string; username?: string } }> }; const store = await read(); store.token = { accessToken: token, expiresAt: Date.now() + Number(long.expires_in ?? 5_184_000) * 1000 }; store.accounts = (pages.data ?? []).map((page) => ({ id: page.id, name: page.name, accessToken: page.access_token, instagramId: page.instagram_business_account?.id, instagramUsername: page.instagram_business_account?.username })); store.selected = undefined; await write(store); }
export async function dashboard(): Promise<MetaDashboard> { if (!allowed()) return { accessRequired: true, configured: configured(), connected: false, accounts: [], posts: [] }; if (!configured()) return { accessRequired: false, configured: false, connected: false, message: "Add Meta OAuth, state, encryption, and dashboard access secrets to enable publishing.", accounts: [], posts: [] }; const store = await read(); return { accessRequired: false, configured: true, connected: Boolean(store.token), accounts: store.accounts.map(({ accessToken: _, ...account }) => account), selected: store.selected, posts: store.posts.slice(0, 50) }; }
export async function selectAccount(pageId: string, instagramId?: string) { requireAccess(); const store = await read(); const account = store.accounts.find((item) => item.id === pageId); if (!account || (instagramId && account.instagramId !== instagramId)) throw new Error("Select an account returned by Meta."); store.selected = { pageId, instagramId }; await write(store); }
export async function generateCaption(prompt: string) { requireAccess(); const apiKey = required("OPENAI_API_KEY"); const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini", input: `Write one concise, practical social caption for Ellis AI Studio. Avoid hype and unsupported claims. Include a gentle CTA. Topic: ${prompt}` }) }); const body = await response.json() as { output_text?: string; error?: { message?: string } }; if (!response.ok || !body.output_text) throw new Error(body.error?.message ?? "AI caption generation failed."); return body.output_text.trim(); }
export async function savePost(input: { id?: string; caption: string; media: Media[]; targets: Array<"facebook" | "instagram">; scheduledFor?: number }) { requireAccess(); if (!input.caption.trim() || !input.targets.length) throw new Error("A caption and at least one publishing destination are required."); const store = await read(); const post: MetaPost = { id: input.id ?? crypto.randomUUID(), caption: input.caption.trim(), media: input.media, targets: input.targets, status: input.scheduledFor && input.scheduledFor > Date.now() ? "scheduled" : "draft", scheduledFor: input.scheduledFor, createdAt: Date.now() }; const index = store.posts.findIndex((item) => item.id === post.id); if (index >= 0) store.posts[index] = { ...store.posts[index], ...post, status: post.status, error: undefined }; else store.posts.unshift(post); await write(store); return post; }
async function publishFacebook(post: MetaPost, account: Account) { const endpoint = post.media.some((media) => media.mimeType?.startsWith("video/")) ? `${account.id}/videos` : `${account.id}/photos`; const form = new FormData(); form.set("caption", post.caption); form.set("access_token", account.accessToken); const first = post.media[0]; if (first?.dataUrl) { const [header, data] = first.dataUrl.split(",", 2); if (!data) throw new Error("The uploaded file could not be read."); form.set("source", new Blob([Buffer.from(data, "base64")], { type: first.mimeType ?? header.match(/data:([^;]+)/)?.[1] ?? "application/octet-stream" }), first.filename ?? "upload"); } else if (first?.url) form.set("url", first.url); else throw new Error("Facebook publishing requires a selected file or public media URL."); const result = await graphJson(endpoint, { method: "POST", body: form }); return String(result.id ?? result.post_id ?? "Facebook post created"); }
async function publishInstagram(post: MetaPost, account: Account) { if (!account.instagramId) throw new Error("The selected Page has no linked Instagram Business account."); const media = post.media[0]; if (!media?.url || !/^https:\/\//.test(media.url)) throw new Error("Instagram publishing requires a public HTTPS media URL. Upload the file to your approved public media host first."); const accessToken = required("INSTAGRAM_ACCESS_TOKEN"); const params = new URLSearchParams({ access_token: accessToken, caption: post.caption, [media.mimeType?.startsWith("video/") ? "video_url" : "image_url"]: media.url, ...(media.mimeType?.startsWith("video/") ? { media_type: "REELS" } : {}) }); const container = await graphJson(`${account.instagramId}/media`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: params }); const containerId = String(container.id ?? ""); if (!containerId) throw new Error("Instagram did not create a media container."); const published = await graphJson(`${account.instagramId}/media_publish`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ creation_id: containerId, access_token: accessToken }) }); return String(published.id ?? "Instagram post created"); }
export async function publishPost(id: string) { requireAccess(); const store = await read(); const post = store.posts.find((item) => item.id === id); const account = store.accounts.find((item) => item.id === store.selected?.pageId); if (!post || !account) throw new Error("Choose a connected Facebook Page before publishing."); try { await refreshLongLivedToken(store); const results: string[] = []; if (post.targets.includes("facebook")) results.push(`Facebook: ${await publishFacebook(post, account)}`); if (post.targets.includes("instagram")) results.push(`Instagram: ${await publishInstagram(post, account)}`); post.status = "published"; post.publishedAt = Date.now(); post.results = results; post.error = undefined; } catch (error) { post.status = "failed"; post.error = error instanceof Error ? error.message : "Publishing failed."; } await write(store); return post; }
export async function processScheduledPosts() { requireAccess(); const store = await read(); const due = store.posts.filter((post) => post.status === "scheduled" && post.scheduledFor && post.scheduledFor <= Date.now()); const results = []; for (const post of due) results.push(await publishPost(post.id)); return results; }

export type MetaAnalytics = { postId: string; campaignId?: string; collectedAt: number; platform: "facebook" | "instagram"; reach?: number; impressions?: number; engagement?: number; reactions?: number; comments?: number; shares?: number; clicks?: number; videoViews?: number; unavailable?: string[] };
type AnalyticsStore = Store & { analytics?: MetaAnalytics[] };
const MAX_RETRIES = 3;

export async function retryFailedPost(id: string, reason: string) {
  requireAccess();
  const store = await read() as AnalyticsStore;
  const post = store.posts.find((item) => item.id === id);
  if (!post || post.status !== "failed") throw new Error("Only failed posts can be retried.");
  if ((post.retryCount ?? 0) >= MAX_RETRIES) throw new Error(`Retry limit reached (${MAX_RETRIES}). Reconnect Meta or correct the post before trying again.`);
  post.retryCount = (post.retryCount ?? 0) + 1;
  post.lastRetriedAt = Date.now();
  post.lastRetryReason = reason.trim() || "Manual retry";
  await write(store);
  return publishPost(id);
}

function metric(values: unknown, names: string[]) { const items = values as Array<{ name?: string; values?: Array<{ value?: number }> }> | undefined; return items?.find((item) => names.includes(item.name ?? ""))?.values?.[0]?.value; }
export async function collectAnalytics(id: string): Promise<MetaAnalytics[]> {
  requireAccess();
  const store = await read() as AnalyticsStore;
  const post = store.posts.find((item) => item.id === id);
  const account = store.accounts.find((item) => item.id === store.selected?.pageId);
  if (!post || post.status !== "published" || !account) throw new Error("Publish a post from a selected account before collecting analytics.");
  const output: MetaAnalytics[] = [];
  for (const platform of post.targets) {
    const result = post.results?.find((item) => item.toLowerCase().startsWith(platform));
    const externalId = result?.split(":").slice(1).join(":").trim();
    const record: MetaAnalytics = { postId: post.id, campaignId: post.campaignId, platform, collectedAt: Date.now(), unavailable: [] };
    if (!externalId) { record.unavailable?.push("External post ID was not returned by Meta."); output.push(record); continue; }
    try {
      if (platform === "facebook") {
        const data = await graphJson(`${externalId}/insights?metric=post_impressions,post_impressions_unique,post_engaged_users,post_clicks`) as { data?: unknown };
        record.impressions = metric(data.data, ["post_impressions"]); record.reach = metric(data.data, ["post_impressions_unique"]); record.engagement = metric(data.data, ["post_engaged_users"]); record.clicks = metric(data.data, ["post_clicks"]);
      } else {
        const data = await graphJson(`${externalId}/insights?metric=reach,impressions,accounts_engaged,total_interactions,likes,comments,shares,saved,video_views`) as { data?: unknown };
        record.reach = metric(data.data, ["reach"]); record.impressions = metric(data.data, ["impressions"]); record.engagement = metric(data.data, ["accounts_engaged", "total_interactions"]); record.reactions = metric(data.data, ["likes"]); record.comments = metric(data.data, ["comments"]); record.shares = metric(data.data, ["shares"]); record.videoViews = metric(data.data, ["video_views"]);
      }
    } catch (error) { record.unavailable?.push(error instanceof Error ? error.message : "Meta did not return metrics for this post."); }
    output.push(record);
  }
  store.analytics = [...output, ...(store.analytics ?? []).filter((item) => item.postId !== id)].slice(0, 500);
  await write(store);
  return output;
}
export async function analyticsForDashboard() { requireAccess(); const store = await read() as AnalyticsStore; return store.analytics ?? []; }

export type FacebookContent = { hook: string; body: string; cta: string; hashtags: string[]; imageIdea: string; readingTime: string; postingTime: string; caption: string };
export async function generateFacebookContent(input: { category: string; tone: string; topic?: string }): Promise<FacebookContent> {
  requireAccess();
  const apiKey = required("OPENAI_API_KEY");
  const categories = ["Educational", "Behind the Scenes", "Case Study", "Business Tips", "AI Myth Busting", "Client Results", "Founder Story", "Industry Trends", "Promotional Offer", "Engagement Question"];
  if (!categories.includes(input.category)) throw new Error("Choose a supported Facebook content category.");
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini", input: `Return JSON only: hook, body, cta, hashtags (array), imageIdea, readingTime, postingTime. Write a Facebook post for Ellis AI Studio. Category: ${input.category}. Tone: ${input.tone}. Topic: ${input.topic || "Choose the most useful Ellis growth-systems topic"}. Brand voice: professional, confident, modern, educational, results-focused, never overly salesy. Ellis designs AI-powered growth systems that help businesses acquire customers, convert leads, and operate efficiently. Do not use archived friction terminology.` }) });
  const result = await response.json() as { output_text?: string; error?: { message?: string } }; if (!response.ok || !result.output_text) throw new Error(result.error?.message ?? "Facebook content generation failed.");
  const content = JSON.parse(result.output_text) as Omit<FacebookContent, "caption">; if (!content.hook || !content.body || !content.cta || !Array.isArray(content.hashtags)) throw new Error("Generated content did not meet the Facebook draft contract.");
  return { ...content, hashtags: content.hashtags.map(String), caption: `${content.hook}\n\n${content.body}\n\n${content.cta}\n\n${content.hashtags.map(String).join(" ")}` };
}
