import { Client } from "pg";
import { readFile } from "node:fs/promises";

type TaskStatus = "queued" | "running" | "awaiting_approval" | "blocked" | "complete" | "failed";
async function databaseUrl() { const source = await readFile(".env", "utf8"); const value = source.split(/\r?\n/).map((line) => line.match(/^SUPABASE_DATABASE_URL=(.*)$/)?.[1]).find(Boolean); if (!value) throw new Error("Supabase database access is not configured."); return value; }
async function query<T>(work: (client: Client) => Promise<T>) { const client = new Client({ connectionString: await databaseUrl(), ssl: { rejectUnauthorized: false } }); await client.connect(); try { return await work(client); } finally { await client.end(); } }

const agents = [
  { id: "prospecting", name: "Prospecting Agent", icon: "O", purpose: "Discovers, audits, deduplicates, and qualifies businesses.", tools: ["Prospect Intelligence", "Google Maps"], location: "Growth Operations", method: "Searches public business data, audits websites, then deduplicates and scores opportunities.", reason: "Creates a clean, evidence-backed prospect pipeline.", eta: "2-10 minutes per search segment" },
  { id: "outreach", name: "Outreach Agent", icon: "@", purpose: "Prepares evidence-led emails and protects follow-up rules.", tools: ["Pluto Mail", "CRM"], location: "Pluto Mail", method: "Uses verified audit findings to draft a unique message and applies follow-up safeguards.", reason: "Turns qualified opportunities into relevant conversations without mass-mailing.", eta: "Under 2 minutes per draft" },
  { id: "content", name: "Content Agent", icon: "*", purpose: "Plans distinct content and maintains the publishing calendar.", tools: ["Content OS", "LinkedIn", "Google Calendar"], location: "Content OS", method: "Builds channel-aware content, schedules it, and keeps calendar records synchronized.", reason: "Builds attention and trust consistently.", eta: "3-8 minutes per content package" },
  { id: "sales", name: "Sales Agent", icon: ">", purpose: "Organizes replies, meetings, proposals, and deal progress.", tools: ["Pipeline", "Proposals"], location: "Sales Pipeline", method: "Classifies replies, maintains deal stages, and prepares meeting or proposal materials.", reason: "Keeps qualified conversations moving toward revenue.", eta: "1-5 minutes per sales update" },
  { id: "intelligence", name: "Intelligence Agent", icon: "I", purpose: "Turns activity and revenue signals into operator decisions.", tools: ["Analytics", "Reporting"], location: "Mission Control", method: "Combines performance signals into concise operating recommendations.", reason: "Helps Pluto choose the highest-leverage next action.", eta: "1-3 minutes per analysis" },
];

export async function dashboard() { return query(async (client) => { const workspace = await client.query<{ id: string; name: string }>("select id, name from public.pluto_workspaces where slug = 'ellis-ai-studio' limit 1"); const workspaceId = workspace.rows[0]?.id; if (!workspaceId) throw new Error("Ellis AI Studio workspace is missing."); const [tasks, approvals, connections, activity, automations, workers] = await Promise.all([client.query("select id, agent, title, objective, status, priority, created_at, started_at, scheduled_for from public.pluto_tasks where workspace_id = $1 order by created_at desc limit 30", [workspaceId]), client.query("select id, action_type, summary, status, requested_at from public.pluto_approvals where workspace_id = $1 order by requested_at desc limit 12", [workspaceId]), client.query("select provider, status, last_synced_at from public.pluto_connections where workspace_id = $1 order by provider", [workspaceId]), client.query("select type, message, created_at from public.pluto_activity where workspace_id = $1 order by created_at desc limit 16", [workspaceId]), client.query("select name, agent, trigger, approval_mode, status from public.pluto_automations where workspace_id = $1 order by name", [workspaceId]), client.query("select worker_key,agent,label,queue,capabilities,status,current_task_id,last_heartbeat_at,runs,last_error from public.pluto_workers where workspace_id=$1 order by case when worker_key='pluto-dispatcher' then 0 else 1 end,label", [workspaceId])]); const agentMap = new Map(agents.map((agent) => [agent.id, agent])); const enrichedTasks = tasks.rows.map((task) => { const agent = agentMap.get(task.agent) ?? agentMap.get("intelligence")!; const stage = task.status === "queued" ? "Pluto has briefed the specialist and is waiting to start." : task.status === "running" ? "The specialist is actively working the plan below." : task.status === "awaiting_approval" ? "Pluto has completed preparation and needs your decision." : task.status === "complete" ? "The specialist finished and Pluto recorded the result." : "Pluto is monitoring this exception."; return { ...task, agentDetail: agent, delegation: { stage, where: agent.location, how: agent.method, why: agent.reason, eta: task.status === "complete" ? "Complete" : task.status === "awaiting_approval" ? "Waiting on approval" : agent.eta } }; }); return { workspace: workspace.rows[0], agents, tasks: enrichedTasks, approvals: approvals.rows, connections: connections.rows, activity: activity.rows, automations: automations.rows, workers: workers.rows }; }); }
export async function createTask(input: { agent: string; title: string; objective?: string; priority?: "low" | "normal" | "high" | "urgent" }) { return query(async (client) => { const workspace = await client.query<{ id: string }>("select id from public.pluto_workspaces where slug = 'ellis-ai-studio' limit 1"); const workspaceId = workspace.rows[0].id; const task = await client.query("insert into public.pluto_tasks (workspace_id, agent, title, objective, priority, status) values ($1, $2, $3, $4, $5, 'queued') returning id, agent, title, status", [workspaceId, input.agent, input.title.trim(), input.objective?.trim() || null, input.priority ?? "normal"]); await client.query("insert into public.pluto_activity (workspace_id, task_id, type, message) values ($1, $2, 'task_created', $3)", [workspaceId, task.rows[0].id, `Pluto assigned ${input.agent}: ${input.title.trim()}`]); return task.rows[0]; }); }
export async function updateTask(id: string, status: TaskStatus) { return query(async (client) => client.query("update public.pluto_tasks set status = $2, started_at = case when $2 = 'running' then coalesce(started_at, now()) else started_at end, completed_at = case when $2 = 'complete' then now() else completed_at end, updated_at = now() where id = $1 returning id, status", [id, status])); }
export async function runSystemCheck() { return query(async (client) => { const workspace = await client.query<{ id: string }>("select id from public.pluto_workspaces where slug = 'ellis-ai-studio' limit 1"); const workspaceId = workspace.rows[0]?.id; if (!workspaceId) throw new Error("Ellis AI Studio workspace is missing."); const requiredTables = ["pluto_workspaces", "pluto_tasks", "pluto_approvals", "pluto_activity", "pluto_connections", "pluto_automations"]; const tableCheck = await client.query<{ table_name: string; present: boolean }>("select unnest($1::text[]) as table_name, to_regclass('public.' || unnest($1::text[])) is not null as present", [requiredTables]); const invalid = await client.query<{ id: string }>("select id from public.pluto_tasks where workspace_id = $1 and agent <> all($2::text[])", [workspaceId, agents.map((agent) => agent.id)]); if (invalid.rows.length) await client.query("update public.pluto_tasks set agent = 'intelligence', updated_at = now() where workspace_id = $1 and agent <> all($2::text[])", [workspaceId, agents.map((agent) => agent.id)]); const badApprovals = await client.query<{ count: number }>("select count(*)::int as count from public.pluto_approvals a left join public.pluto_tasks t on t.id = a.task_id where a.workspace_id = $1 and a.task_id is not null and t.id is null", [workspaceId]); const checks = [{ name: "Database connection", status: "passed", detail: "Mission Control can reach its Supabase control plane." }, { name: "Required tables", status: tableCheck.rows.every((row) => row.present) ? "passed" : "failed", detail: tableCheck.rows.every((row) => row.present) ? "All required control-plane tables are available." : "One or more required tables are missing." }, { name: "Task routing", status: invalid.rows.length ? "repaired" : "passed", detail: invalid.rows.length ? `Reassigned ${invalid.rows.length} invalid task assignment(s) to Intelligence for safe review.` : "Every task has a recognized specialist assignment." }, { name: "Approval integrity", status: badApprovals.rows[0].count ? "warning" : "passed", detail: badApprovals.rows[0].count ? `${badApprovals.rows[0].count} approval record(s) have no linked task.` : "Approval records are internally consistent." }]; await client.query("insert into public.pluto_activity(workspace_id, type, message, metadata) values($1, 'system_check', $2, $3::jsonb)", [workspaceId, `Pluto system check completed: ${checks.map((check) => `${check.name} ${check.status}`).join("; ")}.`, JSON.stringify({ checks, repaired: invalid.rows.length, ranAt: new Date().toISOString() })]); return { checks, repaired: invalid.rows.length }; }); }
