import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { dashboard as intelligenceDashboard, generateOutreach, type ProspectReport } from "~/lib/prospect-intelligence.server";

const path = process.env.PLUTO_PROSPECTING_V3_STORE_PATH ?? ".data/pluto-prospecting-v3.json";
export type Evidence = { finding: string; sourceUrl: string; observedAt: number; confidence: "observed" | "inferred" };
export type CampaignStatus = "draft" | "awaiting_approval" | "approved" | "paused" | "complete";
export type Campaign = { id: string; name: string; prospectIds: string[]; status: CampaignStatus; createdAt: number; approvedAt?: number; pausedReason?: string; sentProspectIds?: string[]; sendFailures?: Array<{ prospectId: string; reason: string }>; delivery: { queued: number; sent: number; delivered: number; opened: number; clicked: number; replied: number; bounced: number; meetings: number; proposals: number; won: number; lost: number; revenue: number } };
type Store = { campaigns: Campaign[] };
async function read(): Promise<Store> { try { return JSON.parse(await readFile(path, "utf8")) as Store; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { campaigns: [] }; throw error; } }
async function write(value: Store) { await mkdir(dirname(path), { recursive: true }); await writeFile(`${path}.tmp`, JSON.stringify(value, null, 2), { mode: 0o600 }); await rename(`${path}.tmp`, path); }
function evidenceFor(prospect: ProspectReport): Evidence[] { return (prospect.findings ?? prospect.weaknesses).map((finding) => ({ finding, sourceUrl: prospect.website, observedAt: prospect.createdAt, confidence: /detected|visible|present|common/i.test(finding) ? "observed" : "inferred" })); }
export async function researchProfile(id: string) { const { reports } = await intelligenceDashboard(); const prospect = reports.find((item) => item.id === id); if (!prospect) throw new Error("Prospect not found."); return { prospect, evidence: evidenceFor(prospect), scores: { websiteQuality: 100 - prospect.score, seo: prospect.seoScore ?? null, mobile: prospect.mobileScore ?? null, automationReadiness: prospect.infrastructureScore ?? null, aiReadiness: prospect.aiReadinessScore ?? null, opportunity: prospect.score }, recommendations: prospect.services }; }
export async function prepareFirstCampaign(input: { name?: string; limit?: number }) { const { reports } = await intelligenceDashboard(); const store = await read(); const previouslyQueued = new Set(store.campaigns.flatMap((campaign) => campaign.prospectIds)); const candidates = reports.filter((item) => item.email && item.stage !== "opted_out" && item.stage !== "lost" && !previouslyQueued.has(item.id)).sort((a, b) => b.score - a.score).slice(0, Math.min(input.limit ?? 100, 100)); if (!candidates.length) throw new Error("No eligible prospects with publicly observed email addresses are available."); const campaign: Campaign = { id: crypto.randomUUID(), name: input.name?.trim() || "National prospecting pilot", prospectIds: candidates.map((item) => item.id), status: "draft", createdAt: Date.now(), delivery: { queued: 0, sent: 0, delivered: 0, opened: 0, clicked: 0, replied: 0, bounced: 0, meetings: 0, proposals: 0, won: 0, lost: 0, revenue: 0 } }; store.campaigns.unshift(campaign); await write(store); return { campaign, prospects: candidates.map((item) => ({ id: item.id, businessName: item.businessName, email: item.email, evidence: evidenceFor(item) })) }; }
export async function generateCampaignDrafts(id: string) { const store = await read(); const campaign = store.campaigns.find((item) => item.id === id); if (!campaign) throw new Error("Campaign not found."); if (campaign.status !== "draft") throw new Error("Campaign drafts can only be prepared before approval."); const { reports } = await intelligenceDashboard(); const byId = new Map(reports.map((item) => [item.id, item])); const generated: string[] = []; for (const prospectId of campaign.prospectIds) { const prospect = byId.get(prospectId); if (!prospect?.email) continue; await generateOutreach(prospectId); generated.push(prospectId); } campaign.status = "awaiting_approval"; campaign.delivery.queued = generated.length; await write(store); return { campaign, generated: generated.length }; }
function emailValid(value: string | undefined) { return Boolean(value && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)); }
function html(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br />"); }
export async function approveCampaign(id: string) { const store = await read(); const campaign = store.campaigns.find((item) => item.id === id); if (!campaign) throw new Error("Campaign not found."); if (campaign.status !== "awaiting_approval" && campaign.status !== "approved") throw new Error("Generate and review drafts before approval."); const { reports } = await intelligenceDashboard(); const byId = new Map(reports.map((item) => [item.id, item])); const { draftService } = await import("~/lib/gmail.server"); campaign.status = "approved"; campaign.approvedAt = campaign.approvedAt ?? Date.now(); campaign.sentProspectIds ??= []; campaign.sendFailures ??= []; for (const prospectId of campaign.prospectIds) { if (campaign.sentProspectIds.includes(prospectId)) continue; const prospect = byId.get(prospectId); if (!prospect?.outreach || !emailValid(prospect.email)) { campaign.sendFailures.push({ prospectId, reason: "Missing a valid public email address or an approved personalized draft." }); continue; } try { await draftService.send({ to: [prospect.email], subject: prospect.outreach.subject, html: html(prospect.outreach.body) }); campaign.sentProspectIds.push(prospectId); campaign.delivery.sent++; } catch (error) { campaign.sendFailures.push({ prospectId, reason: error instanceof Error ? error.message : "Pluto Mail could not send this draft." }); } } await write(store); return campaign; }
export async function extendCampaign(id: string, limit = 100) { const store = await read(); const campaign = store.campaigns.find((item) => item.id === id); if (!campaign) throw new Error("Campaign not found."); if (campaign.status !== "awaiting_approval" && campaign.status !== "draft") throw new Error("Only an unapproved campaign can be extended."); const { reports } = await intelligenceDashboard(); const usedElsewhere = new Set(store.campaigns.filter((item) => item.id !== id).flatMap((item) => item.prospectIds)); const additions = reports.filter((item) => item.email && item.stage !== "opted_out" && item.stage !== "lost" && !usedElsewhere.has(item.id) && !campaign.prospectIds.includes(item.id)).sort((a, b) => b.score - a.score).slice(0, Math.max(0, limit - campaign.prospectIds.length)); for (const prospect of additions) await generateOutreach(prospect.id); campaign.prospectIds.push(...additions.map((item) => item.id)); campaign.delivery.queued = campaign.prospectIds.length; campaign.status = "awaiting_approval"; await write(store); return { campaign, added: additions.length, total: campaign.prospectIds.length }; }
export async function recordCampaignEvent(input: { campaignId: string; event: "sent" | "delivered" | "opened" | "clicked" | "replied" | "bounced" | "meeting" | "proposal" | "won" | "lost"; revenue?: number }) { const store = await read(); const campaign = store.campaigns.find((item) => item.id === input.campaignId); if (!campaign) throw new Error("Campaign not found."); if (campaign.status !== "approved" && input.event === "sent") throw new Error("Campaign approval is required before delivery."); const key = input.event === "meeting" ? "meetings" : input.event === "proposal" ? "proposals" : input.event === "bounced" ? "bounced" : `${input.event}` as keyof Campaign["delivery"]; if (typeof campaign.delivery[key] === "number") (campaign.delivery[key] as number)++; if (input.event === "won") campaign.delivery.revenue += input.revenue ?? 0; const bounceRate = campaign.delivery.sent ? campaign.delivery.bounced / campaign.delivery.sent : 0; if (bounceRate >= .05) { campaign.status = "paused"; campaign.pausedReason = "Bounce rate reached 5%; review list quality before resuming."; } await write(store); return campaign; }
export async function executiveDashboard() { const intelligence = await intelligenceDashboard(); const store = await read(); const campaigns = store.campaigns; const totals = campaigns.reduce((all, campaign) => Object.fromEntries(Object.keys(all).map((key) => [key, all[key as keyof typeof all] + campaign.delivery[key as keyof Campaign["delivery"]]])) as Campaign["delivery"], { queued: 0, sent: 0, delivered: 0, opened: 0, clicked: 0, replied: 0, bounced: 0, meetings: 0, proposals: 0, won: 0, lost: 0, revenue: 0 }); return { intelligence: intelligence.metrics, campaigns, totals, rates: { open: totals.delivered ? +(totals.opened / totals.delivered * 100).toFixed(1) : 0, reply: totals.delivered ? +(totals.replied / totals.delivered * 100).toFixed(1) : 0 }, averageOpportunityScore: intelligence.reports.length ? Math.round(intelligence.reports.reduce((sum, item) => sum + item.score, 0) / intelligence.reports.length) : 0 }; }
