import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { loadLocalEnvironment } from "~/lib/local-env.server";
loadLocalEnvironment();

const path = process.env.PROSPECT_INTELLIGENCE_STORE_PATH ?? ".data/prospect-intelligence.json";
export type ProspectStage = "new" | "qualified" | "contacted" | "interested" | "meeting_scheduled" | "proposal_sent" | "negotiating" | "won" | "lost" | "opted_out" | "researched" | "draft_ready" | "queued" | "sent" | "replied" | "meeting";
export type ProspectReport = { id: string; businessName: string; website: string; createdAt: number; score: number; summary: string; strengths: string[]; weaknesses: string[]; improvements: string[]; services: string[]; roi: string; questions: string[]; proposal: string; demo: string; followUp: string; notes: string; history: string[]; email?: string; phone?: string; industry?: string; city?: string; state?: string; seoScore?: number; mobileScore?: number; speedScore?: number; aiReadinessScore?: number; infrastructureScore?: number; estimatedOpportunityValue?: number; findings?: string[]; priority?: "immediate" | "high" | "medium" | "low"; stage?: ProspectStage; outreach?: { subject: string; body: string; generatedAt: number; queuedAt?: number; followUpAt?: number; sentAt?: number; openedAt?: number; clickedAt?: number; repliedAt?: number; bouncedAt?: number; template?: string }; deal?: { value: number; status: "open" | "won" | "lost"; meetingAt?: number; notes?: string } };
type ScanJob = { id: string; categories: string[]; states: string[]; stateIndex: number; categoryIndex: number; pageToken?: string; scanned: number; eligible: number; goal: number; duplicates: number; status: "running" | "paused" | "complete"; updatedAt: number };
type Store = { reports: ProspectReport[]; scans?: ScanJob[] };
async function read(): Promise<Store> { try { const store = JSON.parse(await readFile(path, "utf8")) as Store; store.scans ??= []; return store; } catch (e) { if ((e as NodeJS.ErrnoException).code === "ENOENT") return { reports: [], scans: [] }; throw e; } }
async function write(store: Store) { await mkdir(dirname(path), { recursive: true }); const temporary = `${path}.${crypto.randomUUID()}.tmp`; await writeFile(temporary, JSON.stringify(store, null, 2), { mode: 0o600 }); await rename(temporary, path); }
function strip(html: string) { return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim(); }
function pick(pattern: RegExp, body: string) { return body.match(pattern)?.[0]; }
function priority(score: number): NonNullable<ProspectReport["priority"]> { return score >= 80 ? "immediate" : score >= 65 ? "high" : score >= 45 ? "medium" : "low"; }
function audit(businessName: string, website: string, html: string): ProspectReport {
  const body = strip(html); const lower = body.toLowerCase(); const source = html.toLowerCase(); const hasText = (s: string) => lower.includes(s); const hasSource = (s: string) => source.includes(s); const links = [...html.matchAll(/href=["']([^"']+)["']/gi)].map((x) => x[1]); const findings = [
    !website.startsWith("https:") && "The fetched page did not resolve over HTTPS.", !/<form\b/i.test(html) && "No contact form was detected on the fetched page.", !hasText("book") && !hasText("schedule") && "No visible booking or scheduling path was detected on the fetched page.", !hasSource("google-analytics") && !hasSource("gtag(") && !hasSource("googletagmanager") && "No common analytics tag was detected in the fetched HTML.", !/<meta[^>]+name=["']viewport["']/i.test(html) && "No mobile viewport tag was detected in the fetched HTML.", !/<meta[^>]+name=["']description["']/i.test(html) && "No meta description was detected in the fetched HTML.", !hasSource("hubspot") && !hasSource("salesforce") && !hasSource("mailchimp") && !hasText("crm") && "No common CRM or lead automation tool was detected in the fetched HTML.", links.some((link) => /^javascript:/i.test(link)) && "JavaScript-only links were detected on the fetched page."
  ].filter(Boolean) as string[];
  const seoScore = Math.max(0, 100 - (findings.some((x) => x.includes("description")) ? 24 : 0) - (/<h1\b/i.test(html) ? 0 : 18) - (hasSource("schema.org") ? 0 : 12));
  const mobileScore = /<meta[^>]+name=["']viewport["']/i.test(html) ? (/<(?:nav|menu)\b/i.test(html) ? 74 : 62) : 30;
  const infrastructureScore = Math.max(0, 100 - findings.filter((x) => /contact|booking|CRM|automation|analytics/i.test(x)).length * 18);
  const speedScore = Math.max(15, 88 - Math.min(60, Math.round(html.length / 45000) * 9) - (hasSource("preload") ? 0 : 8));
  const aiReadinessScore = Math.max(0, 100 - findings.filter((x) => /CRM|automation|analytics|chat/i.test(x)).length * 21);
  const score = Math.min(100, Math.round((100 - seoScore) * .28 + (100 - mobileScore) * .18 + (100 - infrastructureScore) * .36 + (findings.length * 6)));
  const strengths = [hasText("service") && "Services are described on the website.", (hasText("review") || hasText("testimonial")) && "Trust signals are present.", (hasText("book") || hasText("schedule")) && "A booking or scheduling path is visible."].filter(Boolean) as string[];
  const weaknesses = findings.length ? findings : ["No urgent public-evidence issue detected; review manually before outreach."];
  const email = pick(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i, body);
  const phone = pick(/(?:\+1[-.\s]?)?(?:\(?\d{3}\)?[-.\s]?)\d{3}[-.\s]?\d{4}/, body);
  return { id: crypto.randomUUID(), businessName, website, createdAt: Date.now(), score, summary: `${businessName} was reviewed from publicly accessible website content.`, strengths, weaknesses, improvements: ["Clarify the primary conversion path and CTA.", "Turn service outcomes into proof-led content.", "Create a measurable lead-follow-up system."], services: ["Website Systems", "Search Engine Optimization", "Lead Recovery System", "Business Process Automation"], roi: "Estimate after discovery using lead volume, conversion baseline, average customer value, and implementation constraints.", questions: ["What is your highest-value service and current lead source?", "Where do qualified leads drop before booking?", "What capacity can you serve next quarter?"], proposal: "Recommend a paid discovery followed by the smallest measurable growth system that addresses the primary conversion constraint.", demo: "Show a tailored Digital Presence Assessment and before/after conversion-path concept.", followUp: "Follow up 5–7 days after a personalized email if there is no response.", notes: "Automated public-web audit. Verify findings, email eligibility, and consent requirements before outreach.", history: [createHash("sha256").update(body).digest("hex").slice(0, 12)], email, phone, seoScore, mobileScore, infrastructureScore, findings, priority: priority(score), stage: score >= 45 ? "qualified" : "researched" };
}
function normalizedHost(website: string) { return new URL(website).hostname.replace(/^www\./, "").toLowerCase(); }
export async function research(input: { businessName: string; website: string }) { const response = await fetch(new URL(input.website), { headers: { "User-Agent": "Ellis-Prospect-Intelligence/1.0" } }); if (!response.ok) throw new Error(`Research failed (${response.status}).`); const item = audit(input.businessName.trim(), response.url, await response.text()); const store = await read(); store.reports = [item, ...store.reports.filter((r) => normalizedHost(r.website) !== normalizedHost(item.website))]; await write(store); return item; }
export async function reAudit(id: string) { const store = await read(); const existing = store.reports.find((report) => report.id === id); if (!existing) throw new Error("Prospect not found."); const response = await fetch(new URL(existing.website), { headers: { "User-Agent": "Ellis-Prospect-Intelligence/1.0" } }); if (!response.ok) throw new Error(`Re-audit failed (${response.status}).`); const refreshed = audit(existing.businessName, response.url, await response.text()); const updated: ProspectReport = { ...refreshed, id: existing.id, createdAt: existing.createdAt, email: existing.email ?? refreshed.email, phone: existing.phone ?? refreshed.phone, industry: existing.industry, city: existing.city, state: existing.state, stage: existing.stage, outreach: existing.outreach, deal: existing.deal, history: [...existing.history, `Re-audited ${new Date().toISOString()} using raw HTML tag checks and final redirect URL.`] }; const index = store.reports.findIndex((report) => report.id === id); store.reports[index] = updated; await write(store); return updated; }
export const US_STATES = ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"];
export async function discover(input: { query: string; location: string; limit?: number; pageToken?: string }) { const key = process.env.GOOGLE_MAPS_API_KEY; if (!key) throw new Error("Business discovery needs GOOGLE_MAPS_API_KEY in the server environment."); const response = await fetch("https://places.googleapis.com/v1/places:searchText", { method: "POST", headers: { "Content-Type": "application/json", "X-Goog-Api-Key": key, "X-Goog-FieldMask": "places.displayName,places.websiteUri,places.nationalPhoneNumber,places.types,places.formattedAddress,nextPageToken" }, body: JSON.stringify({ textQuery: `${input.query} in ${input.location}`, pageSize: Math.min(input.limit ?? 20, 20), pageToken: input.pageToken }) }); if (!response.ok) throw new Error(`Google Places search failed (${response.status}). Confirm Places API (New), billing, and key restrictions.`); const data = await response.json() as { places?: Array<{ displayName?: { text?: string }; websiteUri?: string; nationalPhoneNumber?: string; formattedAddress?: string; types?: string[] }>; nextPageToken?: string }; const store = await read(); const output: ProspectReport[] = []; let duplicates = 0; for (const candidate of data.places ?? []) { try { if (!candidate.websiteUri) continue; const normalized = new URL(candidate.websiteUri).hostname.replace(/^www\./, "").toLowerCase(); if (store.reports.some((r) => new URL(r.website).hostname.replace(/^www\./, "").toLowerCase() === normalized)) { duplicates++; continue; } const report = await research({ businessName: candidate.displayName?.text ?? normalized, website: candidate.websiteUri }); report.phone ??= candidate.nationalPhoneNumber; report.industry = candidate.types?.[0]?.replaceAll("_", " "); report.city = input.location; output.push(report); } catch { /* inaccessible sites are skipped and never fabricated */ } } return { discovered: output.length, skipped: (data.places?.length ?? 0) - output.length, duplicates, nextPageToken: data.nextPageToken, reports: output }; }
export async function startNationalScan(input: { categories: string[]; states?: string[]; goal?: number }) { const store = await read(); const job: ScanJob = { id: crypto.randomUUID(), categories: input.categories, states: input.states?.length ? input.states : US_STATES, stateIndex: 0, categoryIndex: 0, scanned: 0, eligible: 0, goal: Math.max(1, input.goal ?? 1000), duplicates: 0, status: "running", updatedAt: Date.now() }; store.scans!.unshift(job); await write(store); return job; }
export async function resumeNationalScan(id: string) {
  const initialStore = await read();
  const initialJob = initialStore.scans?.find((x) => x.id === id);
  if (!initialJob) throw new Error("Scan job not found.");
  initialJob.eligible ??= 0;
  initialJob.goal ??= 1000;
  if (initialJob.status === "complete") return initialJob;

  const state = initialJob.states[initialJob.stateIndex];
  const category = initialJob.categories[initialJob.categoryIndex];
  const batch = await discover({ query: category, location: state, pageToken: initialJob.pageToken });

  // Discovery persists each completed website audit. Reload before committing the
  // cursor so this write cannot replace those newly committed report records.
  const store = await read();
  const job = store.scans?.find((x) => x.id === id);
  if (!job) throw new Error("Scan job not found after discovery.");
  job.scanned += batch.discovered;
  job.eligible += batch.reports.filter((item) => Boolean(item.email)).length;
  job.duplicates += batch.duplicates;
  job.pageToken = batch.nextPageToken;
  if (job.eligible >= job.goal) job.status = "complete";
  else if (!job.pageToken) {
    job.categoryIndex++;
    if (job.categoryIndex >= job.categories.length) {
      job.categoryIndex = 0;
      job.stateIndex++;
    }
    if (job.stateIndex >= job.states.length) job.status = "complete";
  }
  job.updatedAt = Date.now();
  await write(store);
  return { job, batch };
}
export async function generateOutreach(id: string) { const store = await read(); const item = store.reports.find((r) => r.id === id); if (!item) throw new Error("Prospect not found."); const evidence = item.findings?.slice(0, 2) ?? item.weaknesses.slice(0, 2); const solutions = evidence.map((finding) => /booking|contact|lead/i.test(finding) ? "a clearer lead-capture and follow-up path" : /seo|description/i.test(finding) ? "a stronger SEO foundation around service and location intent" : /analytics|report/i.test(finding) ? "measurement and reporting that exposes where leads are dropping" : /crm|automation/i.test(finding) ? "connected CRM and workflow automation" : "an intelligent website and customer journey"); const packageNote = evidence.length > 1 ? "Because these opportunities are connected, we can package the work into one phased infrastructure plan and offer discounted bundled pricing rather than treating each improvement as a separate project." : "We can scope this as a focused infrastructure improvement, with discounted pricing available when it connects to a broader system plan."; item.outreach = { subject: `${item.businessName} — one idea after reviewing your online presence`, generatedAt: Date.now(), body: `Hi there,\n\nMy name is Jake Ellis, founder of Ellis AI Studio. While reviewing ${item.businessName}'s public online presence, I noticed ${evidence.map((item) => item.toLowerCase()).join(" ")}\n\nThose observations suggest a practical opportunity to improve ${solutions.join(" and ")}. Ellis AI Studio designs connected Intelligent Business Infrastructure: intelligent websites, AI agents, CRM systems, workflow automation, SEO foundations, reporting, and internal knowledge systems.\n\nThe difference is that we build these pieces to work together around how your business operates—not as isolated software projects.\n\n${packageNote}\n\nIf you reply with your biggest goal for the coming year and the operational challenge slowing you down, I’ll personally share where I believe a connected AI system could have the clearest impact. There’s no obligation.\n\nThank you,\nJake Ellis\nFounder, Ellis AI Studio\nhttps://ellisaistudio.com` }; item.stage = "draft_ready"; await write(store); return item; }
export async function updatePipeline(input: { id: string; stage?: ProspectStage; dealValue?: number; meetingAt?: number; note?: string }) { const store = await read(); const item = store.reports.find((r) => r.id === input.id); if (!item) throw new Error("Prospect not found."); if (input.stage) item.stage = input.stage; if (input.stage === "queued") { if (!item.outreach) throw new Error("Generate and review a personalized draft before queueing it."); item.outreach.queuedAt = Date.now(); item.outreach.followUpAt = Date.now() + 6 * 86400000; } if (input.dealValue !== undefined || input.stage === "won" || input.stage === "lost" || input.meetingAt) item.deal = { value: input.dealValue ?? item.deal?.value ?? 0, status: input.stage === "won" ? "won" : input.stage === "lost" ? "lost" : item.deal?.status ?? "open", meetingAt: input.meetingAt ?? item.deal?.meetingAt, notes: input.note ?? item.deal?.notes }; await write(store); return item; }
export async function dashboard() { const reports = (await read()).reports; const sent = reports.filter((r) => ["queued", "sent", "replied", "meeting", "won", "lost"].includes(r.stage ?? "")).length; const replied = reports.filter((r) => ["replied", "meeting", "won", "lost"].includes(r.stage ?? "")).length; const meetings = reports.filter((r) => r.stage === "meeting" || r.deal?.meetingAt).length; const won = reports.filter((r) => r.stage === "won"); const revenue = won.reduce((sum, r) => sum + (r.deal?.value ?? 0), 0); return { reports: reports.slice(0, 100), metrics: { researched: reports.length, qualified: reports.filter((r) => r.stage !== "researched").length, sent, replied, meetings, won: won.length, revenue, averageDeal: won.length ? revenue / won.length : 0, openRate: 0, replyRate: sent ? Math.round(replied / sent * 1000) / 10 : 0 } }; }
