import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { loadLocalEnvironment } from "~/lib/local-env.server";
loadLocalEnvironment();
const path = process.env.PROSPECT_INTELLIGENCE_STORE_PATH ?? ".data/prospect-intelligence.json";
export type ProspectReport = { id: string; businessName: string; website: string; createdAt: number; score: number; summary: string; strengths: string[]; weaknesses: string[]; improvements: string[]; services: string[]; roi: string; questions: string[]; proposal: string; demo: string; followUp: string; notes: string; history: string[] };
type Store = { reports: ProspectReport[] };
async function read(): Promise<Store> { try { return JSON.parse(await readFile(path, "utf8")) as Store; } catch (e) { if ((e as NodeJS.ErrnoException).code === "ENOENT") return { reports: [] }; throw e; } }
async function write(store: Store) { await mkdir(dirname(path), { recursive: true }); await writeFile(`${path}.tmp`, JSON.stringify(store, null, 2), { mode: 0o600 }); await rename(`${path}.tmp`, path); }
function strip(html: string) { return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim(); }
function report(businessName: string, website: string, html: string): ProspectReport { const body = strip(html); const lower = body.toLowerCase(); const has = (s: string) => lower.includes(s); const score = Math.min(100, 35 + (has("contact") ? 12 : 0) + (has("review") || has("testimonial") ? 12 : 0) + (has("book") || has("schedule") ? 14 : 0) + (has("service") ? 12 : 0) + (has("case stud") ? 8 : 0) + (has("faq") ? 7 : 0)); const strengths = [has("service") && "Services are described on the website.", (has("review") || has("testimonial")) && "Trust signals are present.", (has("book") || has("schedule")) && "A booking or scheduling path is visible."].filter(Boolean) as string[]; const weaknesses = [!has("book") && !has("schedule") && "No clear booking path detected.", !has("review") && !has("testimonial") && "Limited visible social proof.", !has("case stud") && "No case-study evidence detected.", !has("faq") && "Limited objection-handling content detected."].filter(Boolean) as string[]; return { id: crypto.randomUUID(), businessName, website, createdAt: Date.now(), score, summary: `${businessName} has a public website with ${body.slice(0, 280)}â€¦`, strengths, weaknesses, improvements: ["Clarify the primary conversion path and CTA.", "Turn service outcomes into proof-led content.", "Create a measurable lead-follow-up system."], services: ["Growth Systems", "Website Systems", "Lead Recovery System", "Business Intelligence"], roi: "Estimate after discovery using lead volume, conversion baseline, average customer value, and implementation constraints.", questions: ["What is your highest-value service and current lead source?", "Where do qualified leads drop before booking?", "What proof changes a buyerâ€™s mind?", "What capacity can you serve next quarter?"], proposal: "Recommend a paid discovery followed by the smallest measurable growth system that addresses the primary conversion constraint.", demo: "Show a tailored Digital Presence Assessment and before/after conversion-path concept.", followUp: "Send the evidence summary within one business day, ask one focused discovery question, and offer a 20-minute review.", notes: "Public website evidence only. Google, reviews, competitor, social, SEO, and technology enrichment require approved adapters.", history: [createHash("sha256").update(body).digest("hex").slice(0, 12)] }; }
export async function research(input: { businessName: string; website: string }) { const url = new URL(input.website); if (url.protocol !== "https:") throw new Error("Use a public HTTPS website."); const response = await fetch(url, { headers: { "User-Agent": "Ellis-Prospect-Intelligence/1.0" } }); if (!response.ok) throw new Error(`Research failed (${response.status}).`); const item = report(input.businessName.trim(), url.toString(), await response.text()); const store = await read(); const prior = store.reports.filter((r) => r.website === item.website); item.history = [...prior.flatMap((r) => r.history), ...item.history]; store.reports.unshift(item); await write(store); return item; }
export async function dashboard() { return { reports: (await read()).reports.slice(0, 50) }; }
