import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { RevenuePackage } from "~/lib/revenue-engine.server";
const path = process.env.VALIDATION_STORE_PATH ?? ".data/validation.json";
type Decision = "pending" | "approved" | "rejected" | "needs_revision";
export type Session = { id: string; package: RevenuePackage; createdAt: number; decisions: Record<string, Decision>; notes: Record<string, string>; scores: Record<string, number>; history: string[]; timeSavedMinutes?: number; manualEdits?: number };
type Store = { sessions: Session[] };
async function read(): Promise<Store> { try { return JSON.parse(await readFile(path, "utf8")) as Store; } catch (e) { if ((e as NodeJS.ErrnoException).code === "ENOENT") return { sessions: [] }; throw e; } }
async function write(store: Store) { await mkdir(dirname(path), { recursive: true }); await writeFile(`${path}.tmp`, JSON.stringify(store, null, 2), { mode: 0o600 }); await rename(`${path}.tmp`, path); }
const sections = ["Business Intelligence Report", "Digital Presence Assessment", "Growth Opportunity Report", "Discovery Call Brief", "Proposal Draft", "Outreach Drafts", "Follow-Up Timeline"];
export async function create(input: { businessName: string; website: string; notes?: string }) { const { create: createRevenue } = await import("~/lib/revenue-engine.server"); const packageItem = await createRevenue(input); const session: Session = { id: crypto.randomUUID(), package: packageItem, createdAt: Date.now(), decisions: Object.fromEntries(sections.map((x) => [x, "pending"])), notes: {}, scores: Object.fromEntries(["clarity", "business relevance", "personalization", "professionalism", "consistency", "brand alignment", "actionability"].map((x) => [x, 0])), history: ["Validation session created"] }; const store = await read(); store.sessions.unshift(session); await write(store); return session; }
export async function review(input: { id: string; section: string; decision: Decision; note?: string; scores?: Record<string, number>; timeSavedMinutes?: number; manualEdits?: number }) { const store = await read(); const s = store.sessions.find((x) => x.id === input.id); if (!s) throw new Error("Validation session was not found."); s.decisions[input.section] = input.decision; if (input.note) s.notes[input.section] = input.note; if (input.scores) Object.assign(s.scores, input.scores); s.timeSavedMinutes = input.timeSavedMinutes ?? s.timeSavedMinutes; s.manualEdits = input.manualEdits ?? s.manualEdits; s.history.unshift(`${input.section}: ${input.decision}`); await write(store); return s; }
export async function dashboard() { return { sessions: (await read()).sessions.slice(0, 30), sections }; }
export function markdown(s: Session) { return `# ${s.package.businessName} — Validation Packet\n\n## Business Intelligence Report\n${s.package.proposal.currentSituation}\n\n## Opportunity Score\n${s.package.reasoning}\n\n## Recommended Services\n${s.package.proposal.recommendedSystems}\n\n## Discovery Call Brief\n${String(s.package.discovery.agenda)}\n\n## Proposal Draft\n${Object.entries(s.package.proposal).map(([k,v]) => `- **${k}:** ${v}`).join("\n")}\n\n## Follow-Up Timeline\n${s.package.followUp.map((x) => `- ${x}`).join("\n")}`; }
