import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { loadLocalEnvironment } from "~/lib/local-env.server";

loadLocalEnvironment();

const storePath = process.env.CONTENT_VIDEO_STORE_PATH ?? ".data/content-video-jobs.json";
const platforms = ["instagram", "tiktok", "youtube", "facebook", "linkedin", "threads", "twitter", "pinterest", "bluesky"] as const;
export type VideoPlatform = typeof platforms[number];
export type VideoJob = { id: string; topic: string; idea?: string; script?: string; veoPrompt?: string; caption?: string; blotatoCreationId?: string; videoUrl?: string; status: "draft" | "generating" | "rendering" | "ready" | "awaiting_approval" | "publishing" | "published" | "failed"; requestedPlatforms: VideoPlatform[]; submissions: Partial<Record<VideoPlatform, string>>; publicUrls?: Partial<Record<VideoPlatform, string>>; error?: string; createdAt: string; updatedAt: string };
type Store = { jobs: VideoJob[] };

async function read(): Promise<Store> { try { return JSON.parse(await readFile(storePath, "utf8")) as Store; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { jobs: [] }; throw error; } }
async function write(store: Store) { await mkdir(dirname(storePath), { recursive: true }); const temporary = `${storePath}.${crypto.randomUUID()}.tmp`; await writeFile(temporary, JSON.stringify(store, null, 2), { mode: 0o600 }); await rename(temporary, storePath); }
async function update(id: string, patch: Partial<VideoJob>) { const store = await read(); const index = store.jobs.findIndex((job) => job.id === id); if (index < 0) throw new Error("Video job not found."); const next = { ...store.jobs[index], ...patch, updatedAt: new Date().toISOString() }; store.jobs[index] = next; await write(store); return next; }
function required(name: string) { const value = process.env[name]; if (!value) throw new Error(`${name} is required for this video operation.`); return value; }
type VideoScene = { mediaPrompt: string; voiceover: string };
type VideoPlan = { idea: string; script: string; veoPrompt: string; caption: string; scenes: [VideoScene, VideoScene, VideoScene] };
const videoPlanSchema = { type: "object", additionalProperties: false, required: ["idea", "script", "veoPrompt", "caption", "scenes"], properties: { idea: { type: "string" }, script: { type: "string" }, veoPrompt: { type: "string" }, caption: { type: "string" }, scenes: { type: "array", minItems: 3, maxItems: 3, items: { type: "object", additionalProperties: false, required: ["mediaPrompt", "voiceover"], properties: { mediaPrompt: { type: "string" }, voiceover: { type: "string" } } } } } };
function videoPlanFromModel(raw: string): VideoPlan { const result = JSON.parse(raw) as Partial<VideoPlan>; if (!result.idea || !result.script || !result.veoPrompt || !result.caption) throw new Error("Content model returned an incomplete video plan."); const suppliedScenes = Array.isArray(result.scenes) && result.scenes.length === 3 && result.scenes.every((scene) => scene?.mediaPrompt && scene.voiceover) ? result.scenes as [VideoScene, VideoScene, VideoScene] : undefined; const sentences = result.script.match(/[^.!?]+[.!?]+/g)?.map((sentence) => sentence.trim()).filter(Boolean) ?? [result.script]; const scenes = suppliedScenes ?? [{ mediaPrompt: `First 3 seconds: authentic service-business owner notices a missed inquiry and overloaded follow-up, handheld close-up, warm ivory and deep ink, no fake interface. ${result.veoPrompt}`, voiceover: sentences[0] ?? result.script }, { mediaPrompt: `Middle 8 seconds: the same real business shifts into a calm connected workflow, natural people and practical details, premium editorial motion, subtle restrained-gold accent. ${result.veoPrompt}`, voiceover: sentences.slice(1, -1).join(" ") || sentences[1] || "A connected system gives every lead a clear next step." }, { mediaPrompt: "Final 4 seconds: clean premium Ellis AI Studio end card, logo centered and fully visible on warm ivory, quiet cinematic finish, no altered lettering or extra logos.", voiceover: sentences.at(-1) ?? "Ellis AI Studio. Build the system behind your growth." }] as [VideoScene, VideoScene, VideoScene]; return { idea: result.idea, script: result.script, veoPrompt: result.veoPrompt, caption: result.caption, scenes }; }
async function plan(topic: string) {
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${required("OPENAI_API_KEY")}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-4.1-mini", text: { format: { type: "json_schema", name: "ellis_video_plan", strict: true, schema: videoPlanSchema } }, input: `Create a premium 15-second 9:16 TikTok for Ellis AI Studio about: ${topic}. Return exactly three scenes: scene 1 is a punchy 0–3 second hook showing a recognizable service-business problem; scene 2 is a 3–11 second authentic transformation in a real business setting; scene 3 is an 11–15 second quiet premium end-card transition with room for the Ellis logo. The total voiceover must be 36–44 words, conversational and clear. Visual direction: warm ivory, deep ink, restrained gold accent, editorial product-film lighting, human service-business settings, clean typography, deliberate camera movement. Avoid robots, neon sci-fi, fake dashboards, stock-photo smiles, exaggerated before/after results, and unverified claims. Each mediaPrompt must only describe the visuals for its scene; each voiceover must be concise enough for that scene. The overall script combines the three voiceovers. The caption includes a concise CTA and no more than 5 relevant hashtags.` }), signal: AbortSignal.timeout(30_000) });
  const raw = await response.text(); if (!response.ok) { const error = JSON.parse(raw) as { error?: { message?: string } }; throw new Error(error.error?.message ?? `Idea generation failed (${response.status}).`); }
  const result = JSON.parse(raw) as { output_text?: string; output?: Array<{ content?: Array<{ type?: string; text?: string }> }> };
  const output = result.output_text ?? result.output?.flatMap((item) => item.content ?? []).find((item) => item.type === "output_text")?.text; if (!output) throw new Error("Content model returned no video plan.");
  return videoPlanFromModel(output);
}
function configuredPlatforms(input?: VideoPlatform[]) { return (input?.length ? input : ["instagram", "tiktok"] as VideoPlatform[]).filter((platform): platform is VideoPlatform => platforms.includes(platform)); }
const blotatoBaseUrl = "https://backend.blotato.com/v2";
async function blotato(path: string, key: string, init?: RequestInit) { const response = await fetch(`${blotatoBaseUrl}${path}`, { ...init, headers: { "blotato-api-key": key, "Content-Type": "application/json", ...(init?.headers ?? {}) } }); const text = await response.text(); let body: Record<string, unknown> = {}; try { body = text ? JSON.parse(text) as Record<string, unknown> : {}; } catch { body = { message: text }; } if (!response.ok) throw new Error(`Blotato request failed (${response.status}): ${String(body.message ?? body.error ?? text).slice(0, 280)}`); return body; }
function targetFor(platform: VideoPlatform, options: Record<string, unknown>) { if (platform === "tiktok") return { targetType: platform, privacyLevel: "PUBLIC_TO_EVERYONE", disabledComments: false, disabledDuet: false, disabledStitch: false, isBrandedContent: false, isYourBrand: false, isAiGenerated: true, ...options }; return { targetType: platform, ...(platform === "instagram" ? { mediaType: "reel" } : {}), ...(platform === "facebook" ? { mediaType: "reel" } : {}), ...options }; }
async function accountIdFor(platform: VideoPlatform, configured: Partial<Record<VideoPlatform, string>>, key: string) { if (configured[platform]) return configured[platform]; const accounts = await blotato("/users/me/accounts", key) as { items?: Array<{ id?: string; platform?: string }> }; return accounts.items?.find((account) => account.platform === platform)?.id; }

export async function dashboard() { const jobs = (await read()).jobs.sort((a, b) => b.createdAt.localeCompare(a.createdAt)); return { jobs, configured: { openai: Boolean(process.env.OPENAI_API_KEY), blotato: Boolean(process.env.BLOTATO_API_KEY), publishMode: process.env.CONTENT_VIDEO_PUBLISH_MODE ?? "approval_required" } }; }
export async function create(input: { topic: string; platforms?: VideoPlatform[] }) { const job: VideoJob = { id: crypto.randomUUID(), topic: input.topic.trim(), status: "draft", requestedPlatforms: configuredPlatforms(input.platforms), submissions: {}, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const store = await read(); store.jobs.unshift(job); await write(store); try { const creative = await plan(job.topic); const key = required("BLOTATO_API_KEY"); const templateId = process.env.BLOTATO_VIDEO_TEMPLATE_ID ?? "/base/v2/ai-story-video/5903fe43-514d-40ee-a060-0d6628c5f8fd/v1"; const logoUrl = process.env.BLOTATO_BRAND_LOGO_URL ?? "https://ellisaistudio.com/logo/ellis-og.png"; const scenes = creative.scenes.map((scene) => ({ mediaSource: scene.mediaPrompt, script: scene.voiceover })); scenes[2] = { mediaSource: logoUrl, script: creative.scenes[2].voiceover }; const creation = await blotato("/videos/from-templates", key, { method: "POST", body: JSON.stringify({ templateId, useBrandKit: true, inputs: { scenes, enableVoiceover: true, voiceName: "Daniel (British, authoritative)", aiImageModel: "replicate/recraft-ai/recraft-v3", animateAiImages: true, captionPosition: "bottom", highlightColor: "#B68A3A", transition: "fade", aspectRatio: "9:16", trimToVoiceover: true }, prompt: `${creative.idea}\n\nEllis AI Studio brand requirements: use the Ellis Brand Kit; preserve a premium warm-ivory, deep-ink, and restrained-gold visual system; finish on the supplied Ellis eclipse logo without altering it.\n\nScript:\n${creative.script}\n\nVisual direction:\n${creative.veoPrompt}\n\nCaption:\n${creative.caption}`, render: true }) }) as { item?: { id?: string } }; if (!creation.item?.id) throw new Error("Blotato did not return a video creation ID."); return update(job.id, { ...creative, blotatoCreationId: creation.item.id, status: "rendering" }); } catch (error) { return update(job.id, { status: "failed", error: error instanceof Error ? error.message : String(error) }); } }
export async function refresh(id: string) { const store = await read(); const job = store.jobs.find((item) => item.id === id); if (!job) throw new Error("Video job not found."); if (job.status === "rendering" && job.blotatoCreationId) { const key = required("BLOTATO_API_KEY"); try { const creation = await blotato(`/videos/creations/${job.blotatoCreationId}`, key) as { status?: string; mediaUrl?: string; imageUrls?: string[]; errorMessage?: string }; if (creation.status === "creation-from-template-failed") return update(id, { status: "failed", error: creation.errorMessage ?? "Blotato video generation failed." }); const videoUrl = creation.mediaUrl ?? creation.imageUrls?.[0]; return videoUrl ? update(id, { videoUrl, status: "awaiting_approval", error: undefined }) : update(id, { status: "rendering" }); } catch (error) { return update(id, { status: "failed", error: error instanceof Error ? error.message : String(error) }); } }
  if (job.status === "publishing") { const key = required("BLOTATO_API_KEY"); const publicUrls: Partial<Record<VideoPlatform, string>> = { ...job.publicUrls }; try { for (const [platform, submissionId] of Object.entries(job.submissions) as Array<[VideoPlatform, string]>) { const result = await blotato(`/posts/${submissionId}`, key) as { status?: string; publicUrl?: string; errorMessage?: string }; if (result.status === "failed") return update(id, { status: "failed", publicUrls, error: `Blotato ${platform} publishing failed: ${result.errorMessage ?? "Unknown error"}` }); if (result.status === "published" && result.publicUrl) publicUrls[platform] = result.publicUrl; }
      const complete = Object.keys(job.submissions).every((platform) => Boolean(publicUrls[platform as VideoPlatform]));
      return update(id, { publicUrls, status: complete ? "published" : "publishing", error: undefined });
    } catch (error) { return update(id, { status: "failed", publicUrls, error: error instanceof Error ? error.message : String(error) }); }
  }
  return job; }
export async function publish(id: string, approved = false) { const store = await read(); const job = store.jobs.find((item) => item.id === id); if (!job) throw new Error("Video job not found."); if (!job.videoUrl) throw new Error("A public video URL is required before distribution."); const automatic = process.env.CONTENT_VIDEO_PUBLISH_MODE === "autonomous";
  if (!automatic && !approved) return update(id, { status: "awaiting_approval", error: "Publishing is waiting for approval. Enable Content Video Publishing autonomy or approve this job in Content Operations." });
  const accounts = JSON.parse(process.env.BLOTATO_ACCOUNT_IDS ?? "{}") as Partial<Record<VideoPlatform, string>>; const targetOptions = JSON.parse(process.env.BLOTATO_TARGET_OPTIONS ?? "{}") as Partial<Record<VideoPlatform, Record<string, unknown>>>; const key = required("BLOTATO_API_KEY"); const submissions: Partial<Record<VideoPlatform, string>> = {}; await update(id, { status: "publishing", error: undefined });
  for (const platform of job.requestedPlatforms) { try { const accountId = await accountIdFor(platform, accounts, key); if (!accountId) continue; const result = await blotato("/posts", key, { method: "POST", body: JSON.stringify({ post: { accountId, content: { text: job.caption ?? job.idea ?? job.topic, platform, mediaUrls: [job.videoUrl] }, target: targetFor(platform, targetOptions[platform] ?? {}) } }) }) as { postSubmissionId?: string }; if (!result.postSubmissionId) return update(id, { status: "failed", submissions, error: `Blotato ${platform} did not return a post submission ID.` }); submissions[platform] = result.postSubmissionId; } catch (error) { return update(id, { status: "failed", submissions, error: error instanceof Error ? error.message : String(error) }); } }
  return update(id, { submissions, status: Object.keys(submissions).length ? "publishing" : "failed", error: Object.keys(submissions).length ? undefined : "No connected Blotato accounts match the selected platforms." });
}
export async function runAutonomousVideoCycle() { const { jobs, configured } = await dashboard(); const refreshed = []; const published = []; for (const job of jobs.filter((item) => item.status === "rendering" || item.status === "publishing")) refreshed.push(await refresh(job.id)); if (configured.publishMode === "autonomous") for (const job of [...jobs, ...refreshed].filter((item) => item.status === "ready" || item.status === "awaiting_approval")) published.push(await publish(job.id)); return { rendered: refreshed.filter((job) => job.blotatoCreationId).length, published: published.length, mode: configured.publishMode }; }
