import { createHash, createHmac, randomBytes, timingSafeEqual, webcrypto } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { getRequestHeader, setResponseHeader } from "@tanstack/react-start/server";
import { loadLocalEnvironment } from "~/lib/local-env.server";
import type { SocialConnection, SocialPost, SocialProvider } from "~/lib/social-provider";
loadLocalEnvironment();
const path=process.env.X_TOKEN_STORE_PATH??".data/x.json";
type Token={accessToken:string;refreshToken?:string;expiresAt:number;userId:string;name?:string};
function req(k:string){const v=process.env[k];if(!v)throw new Error(`${k} is not configured.`);return v} function ready(){return ["X_CLIENT_ID","X_OAUTH_REDIRECT_URI","X_OAUTH_STATE_SECRET","X_TOKEN_ENCRYPTION_KEY","X_DASHBOARD_ACCESS_TOKEN"].every(k=>Boolean(process.env[k]))} function cv(n:string){return(getRequestHeader("cookie")??"").split(";").map(x=>x.trim()).find(x=>x.startsWith(`${n}=`))?.slice(n.length+1)} function access(){const e=process.env.X_DASHBOARD_ACCESS_TOKEN,a=cv("ellis_x_dashboard");if(!e||!a||e.length!==a.length||!timingSafeEqual(Buffer.from(e),Buffer.from(a)))throw new Error("Dashboard access is required.")} function b64(v:Uint8Array|string){return Buffer.from(v).toString("base64url")} function sig(v:string){return createHmac("sha256",req("X_OAUTH_STATE_SECRET")).update(v).digest("base64url")} async function key(){const d=await webcrypto.subtle.digest("SHA-256",new TextEncoder().encode(req("X_TOKEN_ENCRYPTION_KEY")));return webcrypto.subtle.importKey("raw",d,"AES-GCM",false,["encrypt","decrypt"])}
async function load():Promise<Token|undefined>{try{const e=JSON.parse(await readFile(path,"utf8"));const p=await webcrypto.subtle.decrypt({name:"AES-GCM",iv:Buffer.from(e.iv,"base64url")},await key(),Buffer.from(e.ciphertext,"base64url"));return JSON.parse(new TextDecoder().decode(p))}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return;throw new Error("The encrypted X token store could not be read.")}} async function save(t:Token){const iv=randomBytes(12),c=await webcrypto.subtle.encrypt({name:"AES-GCM",iv},await key(),new TextEncoder().encode(JSON.stringify(t)));await mkdir(dirname(path),{recursive:true});await writeFile(`${path}.tmp`,JSON.stringify({iv:b64(iv),ciphertext:b64(new Uint8Array(c))}),{mode:0o600});await rename(`${path}.tmp`,path)}
export function unlock(token:string){const e=req("X_DASHBOARD_ACCESS_TOKEN");if(token.length!==e.length||!timingSafeEqual(Buffer.from(token),Buffer.from(e)))throw new Error("Dashboard access was denied.");setResponseHeader("Set-Cookie",`ellis_x_dashboard=${encodeURIComponent(e)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`)}
export function authorizationUrl(){access();if(!ready())throw new Error("X is not configured.");const verifier=b64(randomBytes(48)),challenge=createHash("sha256").update(verifier).digest("base64url"),payload=b64(JSON.stringify({expiresAt:Date.now()+600000,nonce:b64(randomBytes(16))})),state=`${payload}.${sig(payload)}`,url=new URL("https://twitter.com/i/oauth2/authorize");setResponseHeader("Set-Cookie",`ellis_x_verifier=${verifier}; HttpOnly; SameSite=Lax; Path=/dashboard/x-callback; Max-Age=600`);url.search=new URLSearchParams({response_type:"code",client_id:req("X_CLIENT_ID"),redirect_uri:req("X_OAUTH_REDIRECT_URI"),scope:"tweet.read tweet.write users.read offline.access",state,code_challenge:challenge,code_challenge_method:"S256"}).toString();return url.toString()}
async function exchange(data:Record<string,string>){const auth=process.env.X_CLIENT_SECRET?`Basic ${Buffer.from(`${req("X_CLIENT_ID")}:${req("X_CLIENT_SECRET")}`).toString("base64")}`:undefined,r=await fetch("https://api.x.com/2/oauth2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded",...(auth?{Authorization:auth}:{})},body:new URLSearchParams(data)}),b=await r.json() as {access_token?:string;refresh_token?:string;expires_in?:number;error_description?:string};if(!r.ok||!b.access_token)throw new Error(b.error_description??"X token exchange failed.");return {accessToken:b.access_token,refreshToken:b.refresh_token,expiresIn:b.expires_in}}
export async function completeAuthorization(code:string,state:string){access();const[p,s]=state.split(".");if(!code||!p||!s||s.length!==sig(p).length||!timingSafeEqual(Buffer.from(s),Buffer.from(sig(p))))throw new Error("X OAuth state validation failed.");const d=JSON.parse(Buffer.from(p,"base64url").toString()) as {expiresAt:number};if(d.expiresAt<Date.now())throw new Error("X OAuth state expired.");const verifier=cv("ellis_x_verifier");if(!verifier)throw new Error("X PKCE verifier is missing. Start the connection again.");const b=await exchange({grant_type:"authorization_code",code,redirect_uri:req("X_OAUTH_REDIRECT_URI"),code_verifier:verifier});const me=await fetch("https://api.x.com/2/users/me",{headers:{Authorization:`Bearer ${b.accessToken}`}}),u=await me.json() as {data?:{id?:string;name?:string}};if(!me.ok||!u.data?.id)throw new Error("X profile lookup failed.");await save({accessToken:b.accessToken,refreshToken:b.refreshToken,expiresAt:Date.now()+Number(b.expiresIn??7200)*1000,userId:u.data.id,name:u.data.name});setResponseHeader("Set-Cookie","ellis_x_verifier=; HttpOnly; SameSite=Lax; Path=/dashboard/x-callback; Max-Age=0")}
async function active(){const t=await load();if(!t)throw new Error("No X account is connected.");if(t.expiresAt<Date.now()+60000){if(!t.refreshToken)throw new Error("X token expired. Reconnect X.");const b=await exchange({grant_type:"refresh_token",refresh_token:t.refreshToken,client_id:req("X_CLIENT_ID")});t.accessToken=b.accessToken;t.refreshToken=b.refreshToken??t.refreshToken;t.expiresAt=Date.now()+Number(b.expiresIn??7200)*1000;await save(t)}return t}
export async function dashboard():Promise<SocialConnection&{configured:boolean}>{if(!ready())return{provider:"x",connected:false,configured:false,message:"Add X deployment secrets."};const t=await load();return{provider:"x",connected:Boolean(t),displayName:t?.name,expiresAt:t?.expiresAt,configured:true}} export async function publish(post:SocialPost){access();if(post.image)throw new Error("X image publishing is not enabled yet.");const t=await active(),r=await fetch("https://api.x.com/2/tweets",{method:"POST",headers:{Authorization:`Bearer ${t.accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({text:post.text})}),b=await r.json() as {data?:{id?:string};detail?:string};if(!r.ok||!b.data?.id)throw new Error(b.detail??`X publish failed (${r.status}).`);return{id:b.data.id}} export const xProvider:SocialProvider={connection:async()=>dashboard(),authorizationUrl,completeAuthorization,publish,refreshToken:async()=>{access();await active()}}
