import { createFileRoute } from "@tanstack/react-router";
import { StandardPage, bookingUrl } from "~/components/growth-site";
import { jsonLd, pageHead, siteUrl } from "~/lib/seo";

const pages: Record<string, { name: string; title: string; description: string; problem: string }> = {
  "ai-websites": { name: "AI Websites", title: "AI Websites for Service Businesses", description: "Conversion-focused AI websites that help service businesses answer buyer questions and turn traffic into qualified conversations.", problem: "A generic website leaves prospects uncertain, makes proof hard to find, and sends too many visitors away without a next step." },
  "ai-lead-recovery": { name: "AI Lead Recovery", title: "AI Lead Recovery for Service Businesses", description: "Recover more of the demand you earn with automated response, routing, CRM handoffs, and follow-up systems.", problem: "When follow-up depends on manual memory and inboxes, qualified leads cool off before your team can respond." },
  "custom-crm-automation": { name: "Custom CRM Automation", title: "Custom CRM Automation Services", description: "Design CRM automation around the exact lead, sales, and service workflows your business needs to scale.", problem: "Your team is losing time moving information between tools and guessing what should happen next." },
  "custom-ai-software": { name: "Custom AI Software", title: "Custom AI Software Development for Service Businesses", description: "Custom AI software development for service businesses that need a purpose-built solution, not another disconnected tool.", problem: "Off-the-shelf software cannot reflect the decisions, data, and customer journey that make your business different." },
  "ai-integration-services": { name: "AI Integration Services", title: "AI Integration Services for Service Businesses", description: "Connect your CRM, website, communications, and operations tools into an AI-ready business system.", problem: "Disconnected systems make automation brittle and force your team to reconcile data manually." },
  "business-intelligence": { name: "Business Intelligence", title: "Business Intelligence for Service Business Growth", description: "Business intelligence systems that help service businesses turn demand, pipeline, and operational signals into action.", problem: "Without a shared view of the signals that matter, growth decisions become slow, reactive, and hard to measure." },
};

export const Route = createFileRoute("/services/$service")({ head: ({ params }) => { const page = pages[params.service] ?? pages["ai-websites"]; return { ...pageHead({ title: `${page.title} | Ellis AI Studio`, description: page.description, path: `/services/${params.service}` }), scripts: jsonLd({ "@context": "https://schema.org", "@type": "Service", name: page.name, description: page.description, provider: { "@id": `${siteUrl}/#organization` }, areaServed: "United States", url: `${siteUrl}/services/${params.service}` }) }; }, component: ServicePage });
function ServicePage() { const page = pages[Route.useParams().service] ?? pages["ai-websites"]; return <StandardPage eyebrow="Service" title={page.title} intro={page.description}><div className="about"><h2>Who this is for</h2><p>Service-business leaders who have a defined growth or operations problem and need a system that fits the way their team actually works.</p><h2>What it solves</h2><p>{page.problem}</p><h2>Why Ellis</h2><p>Ellis connects strategy, implementation, and ongoing improvement so the system is useful to the people who sell, serve, and operate your business.</p><h2>Why now</h2><p>Every manual handoff, unclear website journey, and delayed response compounds as demand grows. A focused assessment identifies the highest-leverage system to improve first.</p><a className="button" href={bookingUrl} target="_blank" rel="noreferrer">Discuss this service</a></div></StandardPage>; }
