import { createFileRoute } from "@tanstack/react-router";
import { StandardPage, bookingUrl } from "~/components/growth-site";
import { pageHead } from "~/lib/seo";
import "~/styles/infrastructure-detail.css";

type Layer = { title: string; eyebrow: string; summary: string; image: string; imageAlt: string; deliverables: string[]; approach: string[] };

const layers: Record<string, Layer> = {
  "intelligent-websites": { title: "Intelligent Websites", eyebrow: "Experience layer", summary: "A website should connect clear customer journeys to the systems that handle the next action.", image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1600&q=85", imageAlt: "Team reviewing a digital product interface", deliverables: ["Customer-journey and conversion architecture", "Responsive interface and content system", "Smart forms, routing, and CRM handoffs", "Analytics instrumentation and launch review"], approach: ["Map the decisions visitors need to make and the information they need to make them.", "Design the interface, content hierarchy, and conversion paths around those decisions.", "Connect forms and interactions to the systems that own follow-up.", "Measure behavior after launch and improve the journeys that matter most."] },
  "ai-systems": { title: "AI Systems", eyebrow: "Intelligence layer", summary: "AI is valuable when it is grounded in your knowledge, connected to real workflows, and governed by clear human oversight.", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=85", imageAlt: "Close view of an illuminated computing circuit", deliverables: ["Use-case and workflow definition", "Knowledge-source preparation and retrieval design", "Agent instructions, guardrails, and escalation paths", "Evaluation, monitoring, and team handoff"], approach: ["Select the workflow where speed, consistency, or access to knowledge creates practical leverage.", "Prepare the approved information, tools, and boundaries the system needs to operate safely.", "Build and evaluate the AI interaction against real scenarios before release.", "Monitor exceptions and improve the system with the team that owns the outcome."] },
  "automation-systems": { title: "Automation Systems", eyebrow: "Operations layer", summary: "Automation should remove repetitive handoffs while keeping ownership, visibility, and exceptions clear.", image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=85", imageAlt: "Global network visualization", deliverables: ["Workflow map and exception design", "System integrations and data mapping", "Routing, notifications, and approval logic", "Operational documentation and monitoring"], approach: ["Trace the current process from trigger to completion, including every manual handoff.", "Define the data required at each step and the owner for every exception.", "Connect the approved systems and build the automation in testable stages.", "Document, observe, and refine the workflow after it enters daily use."] },
  "custom-software": { title: "Custom Software", eyebrow: "Product layer", summary: "Purpose-built software turns a distinct internal process into a dependable product your team can operate and improve.", image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=85", imageAlt: "Developer working at a laptop", deliverables: ["Product requirements and system architecture", "Interface design and technical implementation", "Role-based workflows and integrations", "Quality assurance, deployment, and support plan"], approach: ["Translate the operating problem into a small, measurable product scope.", "Design the data model, permissions, integrations, and interface before implementation.", "Build in clear milestones with working reviews instead of a single end-stage reveal.", "Test with the people who use the workflow, then deploy with ownership and support defined."] },
  "seo-infrastructure": { title: "SEO Infrastructure", eyebrow: "Growth layer", summary: "Search performance is infrastructure: technical health, useful information, structured signals, and a repeatable improvement process.", image: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?auto=format&fit=crop&w=1600&q=85", imageAlt: "Search analytics shown on a monitor", deliverables: ["Technical, content, and search-intent assessment", "Information architecture and page-priority plan", "On-page, schema, and performance improvements", "Measurement dashboard and iteration cadence"], approach: ["Establish a baseline for technical health, current visibility, and high-value search intent.", "Prioritize the pages, content, and structural improvements that support the broader customer journey.", "Implement changes with clean tracking and clear technical standards.", "Review search and conversion evidence on a defined cadence, then improve the next layer."] },
  "business-intelligence": { title: "Business Intelligence", eyebrow: "Decision layer", summary: "Business intelligence converts disconnected operating signals into a shared view of what needs attention next.", image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=85", imageAlt: "Business analytics dashboard on a screen", deliverables: ["Metric definitions and source-of-truth design", "Data-source connection and quality checks", "Role-specific dashboards and reporting views", "Decision rhythm, alerts, and improvement backlog"], approach: ["Start with the decisions teams need to make—not a list of charts they might want.", "Define shared metrics, owners, and the data sources that can support them.", "Build focused reporting views that make exceptions and trends easy to act on.", "Create a recurring review rhythm that turns evidence into accountable next steps."] },
};

export const Route = createFileRoute("/services/$service")({
  head: ({ params }) => { const layer = layers[params.service] ?? layers["intelligent-websites"]; return pageHead({ title: `${layer.title} | Ellis AI Studio`, description: layer.summary, path: `/services/${params.service}` }); },
  component: LayerPage,
});

function LayerPage() {
  const layer = layers[Route.useParams().service] ?? layers["intelligent-websites"];
  return <StandardPage eyebrow={layer.eyebrow} title={layer.title} intro={layer.summary}><div className="infrastructure-detail"><section className="layer-process-map" aria-labelledby="implementation-sequence"><div className="layer-process-heading"><p className="eyebrow">Example implementation sequence</p><h2 id="implementation-sequence">How Ellis AI Studio completes this layer.</h2><p>A clear, accountable process from the first operating decision through ongoing improvement.</p></div><ol>{layer.approach.map((step, index) => <li key={step}><span>0{index + 1}</span><p>{step}</p></li>)}</ol></section><section className="layer-plan"><div><p className="eyebrow">What we deliver</p><h2>A complete, connected implementation.</h2><ul>{layer.deliverables.map((item) => <li key={item}>{item}</li>)}</ul></div><div><p className="eyebrow">Implementation detail</p><p className="layer-plan-note">The sequence above is adapted to the systems, owners, and operating constraints already in place at your organization. Each stage produces a visible decision, working system, or measurable improvement.</p></div></section><section className="layer-close"><p>Every infrastructure layer is designed to connect to the customer experience, operations, data, and intelligence that already exist around it.</p><a className="button" href={bookingUrl} target="_blank" rel="noreferrer">Schedule a consultation</a></section></div></StandardPage>;
}
