import { useMemo, useState } from "react";
import { Link, createFileRoute } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";
import "~/styles/content-ops-v2.css";

const load = createServerFn({ method: "GET" }).handler(async () => (await import("~/lib/content-library.server")).listContent());
const saveDraft = createServerFn({ method: "POST" }).validator((data: { id: string; title: string; body: string }) => data).handler(async ({ data }) => (await import("~/lib/content-library.server")).saveContentDraft(data));
const createDraft = createServerFn({ method: "POST" }).validator((data: { title: string; body: string; topic?: string }) => data).handler(async ({ data }) => (await import("~/lib/content-library.server")).createContentDraft(data));
type Item = Awaited<ReturnType<typeof load>>[number];
type View = "calendar" | "library" | "campaigns" | "knowledge";
type CalendarMode = "Day" | "Week" | "Month" | "Quarter";
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const dates = [21, 22, 23, 24, 25, 26, 27];
const workflow = ["Draft", "AI Review", "Human Review", "Approved", "Scheduled", "Publishing Queue", "Published", "Learning"];
const platform = (item: Item) => item.published ? "LinkedIn" : item.topic.includes("instagram") ? "Instagram" : item.topic.includes("email") ? "Email" : "LinkedIn";
const stage = (item: Item) => item.published ? "Published" : item.scheduledFor ? "Scheduled" : item.approved ? "Approved" : "Draft";

export const Route = createFileRoute("/dashboard/content-studio")({ loader: () => load(), component: ContentOS });

function ContentOS() {
  const library = Route.useLoaderData() as Item[];
  const writeDraft = useServerFn(saveDraft);
  const addDraft = useServerFn(createDraft);
  const [view, setView] = useState<View>("calendar");
  const [mode, setMode] = useState<CalendarMode>("Week");
  const [selected, setSelected] = useState<Item | null>(null);
  const [plutoOpen, setPlutoOpen] = useState(false);
  const [notice, setNotice] = useState("");
  const [search, setSearch] = useState("");
  const scheduled = useMemo(() => library.filter((item) => item.scheduledFor), [library]);
  const create = () => void addDraft({ data: { title: "Untitled content opportunity", body: "Start with the decision this content should help someone make.\n\n", topic: "strategy" } }).then(() => window.location.reload()).catch((error: Error) => setNotice(error.message));
  const save = (id: string, title: string, body: string) => void writeDraft({ data: { id, title, body } }).then(() => setNotice("Draft saved to the content library.")).catch((error: Error) => setNotice(error.message));
  return <main className="po-app">
    <aside className="po-rail" aria-label="Pluto Content OS navigation"><Link to="/" className="po-brand"><i>p</i><span><b>PLUTO</b><small>CONTENT OS</small></span></Link><button className="po-ask" onClick={() => setPlutoOpen(true)}>✦ Ask Pluto <kbd>⌘K</kbd></button><nav><button className={view === "calendar" ? "active" : ""} onClick={() => setView("calendar")}>◫ Calendar</button><button className={view === "library" ? "active" : ""} onClick={() => setView("library")}>▦ Content library</button><button className={view === "campaigns" ? "active" : ""} onClick={() => setView("campaigns")}>◎ Campaigns</button><button className={view === "knowledge" ? "active" : ""} onClick={() => setView("knowledge")}>◇ Knowledge context</button><Link to="/dashboard/social-accounts">◌ Publishing channels</Link></nav><footer><span>EA</span><div><b>Ellis AI Studio</b><small>Content organization</small></div></footer></aside>
    <section className="po-main"><header className="po-top"><div><p>PLUTO / {view.toUpperCase()}</p><h1>{view === "calendar" ? "Content calendar" : view === "library" ? "Content library" : view === "campaigns" ? "Campaign workspaces" : "Knowledge context"}</h1></div><div><button className="po-secondary" onClick={() => setPlutoOpen(true)}>✦ Pluto brief</button><button className="po-primary" onClick={create}>+ New content</button></div></header>{notice && <p className="po-notice" role="status">{notice}</p>}
      {view === "calendar" && <Calendar mode={mode} setMode={setMode} items={library} scheduled={scheduled} select={setSelected} pluto={() => setPlutoOpen(true)} />}
      {view === "library" && <Library items={library} search={search} setSearch={setSearch} select={setSelected} />}
      {view === "campaigns" && <Campaigns items={library} pluto={() => setPlutoOpen(true)} />}
      {view === "knowledge" && <Knowledge />}
    </section>
    <aside className="po-assistant"><div className="po-assistant-head"><span>✦</span><div><b>Pluto</b><small>Content operator</small></div><i>Ready</i></div><section><p>THIS WEEK</p><h2>{scheduled.length ? `${scheduled.length} scheduled content item${scheduled.length === 1 ? "" : "s"}` : "No publishing plan yet"}</h2><span>{scheduled.length ? "Review scheduled content, then Pluto will use published results to improve future timing." : "Connect publishing channels and approve a content plan before Pluto can recommend timing."}</span>{scheduled.length ? <button onClick={() => setSelected(scheduled[0])}>Review next item →</button> : <Link to="/dashboard/social-accounts">Connect channels →</Link>}</section><section><p>WORKFLOW</p><div className="po-workflow">{workflow.map((item, index) => <div key={item} className={index < 3 ? "complete" : ""}><i>{index < 3 ? "✓" : index + 1}</i><span>{item}</span></div>)}</div></section><section><p>LEARNING STATUS</p><div className="po-empty-insight"><b>Waiting for connected analytics</b><span>Pluto will only recommend times, formats, and platforms after real account data is available.</span></div></section></aside>
    {selected && <ContentDrawer item={selected} close={() => setSelected(null)} save={save} />}{plutoOpen && <Pluto close={() => setPlutoOpen(false)} scheduled={scheduled.length} />}
  </main>;
}

function Calendar({ mode, setMode, items, scheduled, select, pluto }: { mode: CalendarMode; setMode: (mode: CalendarMode) => void; items: Item[]; scheduled: Item[]; select: (item: Item) => void; pluto: () => void }) { const unscheduled = items.filter((item) => !item.scheduledFor && !item.published).slice(0, 4); return <div className="po-page"><section className="po-mission"><div><p>WEEKLY OPERATING PLAN</p><h2>{scheduled.length ? "Your schedule is assembled from approved content." : "Pluto is ready to prepare a schedule when publishing channels are connected."}</h2><span>{scheduled.length ? "Open any item to review its content, approval state, platform treatment, and publishing history." : "Timing is intentionally not guessed. Connect account analytics to enable evidence-based scheduling."}</span></div><button onClick={pluto}>Ask Pluto to plan the week →</button></section><div className="po-calendar-tools"><div>{(["Day", "Week", "Month", "Quarter"] as CalendarMode[]).map((item) => <button key={item} className={mode === item ? "active" : ""} onClick={() => setMode(item)}>{item}</button>)}</div><span>July 21–27, 2026</span></div><section className={`po-calendar ${mode.toLowerCase()}`}><header><b>GMT−07:00</b>{days.map((day, index) => <div key={day} className={index === 4 ? "today" : ""}><span>{day}</span><b>{dates[index]}</b></div>)}</header><div className="po-calendar-body">{days.map((day, index) => <div className="po-day" key={day}>{scheduled.filter((_, eventIndex) => eventIndex % 7 === index).map((item) => <button className={`po-event ${platform(item).toLowerCase()}`} key={item.id} onClick={() => select(item)}><i>{platform(item).slice(0, 1)}</i><b>{item.title}</b><span>{stage(item)} · Open to review</span></button>)}{index === 0 && unscheduled.map((item) => <button className="po-unscheduled" key={item.id} onClick={() => select(item)}><span>Unscheduled</span>{item.title}</button>)}</div>)}</div></section><section className="po-bottom-grid"><article><p>WAITING FOR APPROVAL</p><h3>{unscheduled.length ? `${unscheduled.length} content pieces need a decision` : "No content is waiting for approval"}</h3><span>{unscheduled.length ? "Open a content piece to review its strategy and move it forward." : "Create content or connect your publishing channels to begin the next planning cycle."}</span>{unscheduled[0] && <button onClick={() => select(unscheduled[0])}>Review next content →</button>}</article><article><p>PLUTO’S WEEKLY PLAN</p><h3>Autonomous planning requires connected evidence.</h3><span>When real engagement and account data are available, Pluto can propose a full weekly calendar for human approval.</span><Link to="/dashboard/social-accounts">Connect publishing channels →</Link></article></section></div>; }
function Library({ items, search, setSearch, select }: { items: Item[]; search: string; setSearch: (value: string) => void; select: (item: Item) => void }) { const visible = items.filter((item) => `${item.title} ${item.topic}`.toLowerCase().includes(search.toLowerCase())); return <div className="po-page"><div className="po-library-head"><label><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search content, campaigns, or topics" /></label><span>{visible.length} content items</span></div><section className="po-library-grid">{visible.map((item) => <button onClick={() => select(item)} key={item.id}><i>{item.topic.slice(0, 1).toUpperCase()}</i><small>{platform(item)} · {stage(item)}</small><b>{item.title}</b><span>{item.topic}</span><footer><em>{item.scheduledFor ? new Date(item.scheduledFor).toLocaleDateString() : "Not scheduled"}</em><strong>Open →</strong></footer></button>)}</section></div>; }
function Campaigns({ items, pluto }: { items: Item[]; pluto: () => void }) { return <div className="po-page"><section className="po-campaign-card"><p>ACTIVE CAMPAIGN</p><h2>Content systems for intelligent service businesses</h2><span>Build a body of work that makes Ellis easier to understand, trust, and choose.</span><div><b>Objective <small>Create durable demand</small></b><b>Audience <small>Service business operators</small></b><b>Content <small>{items.length} pieces in library</small></b></div><button onClick={pluto}>Ask Pluto for campaign plan →</button></section><section className="po-campaign-grid"><article><p>CAMPAIGN CALENDAR</p><h3>No campaign dates set</h3><span>Schedule approved content to create an evidence-led campaign timeline.</span></article><article><p>ASSETS</p><h3>No asset library connected</h3><span>Add a DAM integration before Pluto can include approved visual assets in recommendations.</span></article><article><p>PERFORMANCE</p><h3>Waiting for live publishing data</h3><span>Campaign ROI and performance appear only after connected accounts report outcomes.</span></article></section></div>; }
function Knowledge() { const groups = [["Business profile", "Who Ellis serves, services, offers, and operating model."], ["Brand voice", "Writing guidelines, POV, claims, and language to avoid."], ["Audience personas", "Buyer questions and jobs to be done."], ["Content memory", "Published work, campaign history, and performance evidence."], ["Documentation", "FAQs, internal systems, proof, and source material."]]; return <div className="po-page"><section className="po-knowledge-hero"><p>PLUTO LONG-TERM MEMORY</p><h2>Context Pluto should never make your team repeat.</h2><span>Knowledge is used automatically when Pluto recommends an angle, checks for duplication, or plans a campaign.</span></section><section className="po-knowledge-grid">{groups.map(([title, detail]) => <article key={title}><i>◇</i><h3>{title}</h3><span>{detail}</span><button>Manage context →</button></article>)}</section></div>; }
function ContentDrawer({ item, close, save }: { item: Item; close: () => void; save: (id: string, title: string, body: string) => void }) { const [title, setTitle] = useState(item.title); const [body, setBody] = useState(item.body); return <div className="po-drawer-backdrop" role="dialog" aria-modal="true" aria-label="Content editor"><section className="po-drawer"><header><div><p>CONTENT OBJECT / {stage(item).toUpperCase()}</p><b>{platform(item)} {item.scheduledFor ? `· ${new Date(item.scheduledFor).toLocaleString()}` : "· Unscheduled"}</b></div><button onClick={close} aria-label="Close editor">×</button></header><div className="po-drawer-body"><section className="po-editor"><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><div className="po-editor-tabs"><button className="active">Editor</button><button>Live preview</button><button>AI reasoning</button><button>Versions</button></div><textarea value={body} onChange={(event) => setBody(event.target.value)} aria-label="Content draft" /><footer><span>{body.trim().split(/\s+/).filter(Boolean).length} words</span><button onClick={() => save(item.id, title, body)}>Save changes</button></footer></section><aside><p>PUBLISHING CHECKLIST</p><div><i>✓</i> Business context attached</div><div><i>✓</i> Brand voice attached</div><div><i>○</i> Human review required</div><p>PLUTO’S NOTE</p><span>Pluto retains the campaign, audience, and existing content context for this piece.</span><Link to="/dashboard/social-accounts">Manage channels →</Link></aside></div></section></div>; }
function Pluto({ close, scheduled }: { close: () => void; scheduled: number }) { return <div className="po-pluto-backdrop" role="dialog" aria-modal="true" aria-label="Pluto assistant"><section className="po-pluto"><header><span>✦</span><div><p>PLUTO ASSISTANT</p><h2>Operating brief</h2></div><button onClick={close}>×</button></header><div className="po-pluto-message"><b>{scheduled ? "Your next scheduled item is ready for review." : "There is no approved, connected publishing plan for this week."}</b><span>{scheduled ? "Open it from the calendar to check the final content and publishing state." : "Connect channels before Pluto recommends a time, platform, or weekly approval plan."}</span></div><div className="po-pluto-actions">{scheduled ? <button onClick={close}>Review calendar item <span>→</span></button> : <Link to="/dashboard/social-accounts">Connect publishing channels <span>→</span></Link>}<button onClick={close}>Review content library <span>→</span></button></div><footer><input autoFocus placeholder="Ask Pluto about your content operation…" aria-label="Ask Pluto" /><kbd>↵</kbd></footer></section></div>; }
