import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";

const load = createServerFn({ method: "GET" }).handler(async () => (await import("~/lib/google-forms.server")).connection());
const connect = createServerFn({ method: "POST" }).handler(async () => ({ url: (await import("~/lib/google-calendar.server")).authorizationUrl() }));
const create = createServerFn({ method: "POST" }).handler(async () => (await import("~/lib/google-forms.server")).createInfrastructureAssessment());
export const Route = createFileRoute("/dashboard/google-forms")({ loader: () => load(), component: GoogleForms });
function GoogleForms() { const data = Route.useLoaderData(); const begin = useServerFn(connect); const make = useServerFn(create); const [message, setMessage] = useState(""); const [result, setResult] = useState<{ editUrl: string; responderUrl: string }>(); const authorize = () => void begin().then((r) => { sessionStorage.setItem("ellis_google_workspace_return", "/dashboard/google-forms"); window.location.assign(r.url); }).catch((e: Error) => setMessage(e.message)); return <main className="wrap" style={{ padding: "96px 0" }}><p className="eyebrow">Ellis AI Studio integration</p><h1>Google Forms</h1><p>Create and save the AI Infrastructure Assessment as a native Google Form in Drive.</p>{!data.connected ? <><p>Approve Google Forms creation, Drive file access, and your existing calendar connection once.</p><button className="button" onClick={authorize}>Authorize Google Workspace</button></> : <button className="button" onClick={() => void make().then((r) => { setResult(r); setMessage("Assessment created in Google Drive."); }).catch((e: Error) => setMessage(e.message))}>Create AI Infrastructure Assessment</button>}<p role="status">{message}</p>{result && <p><a href={result.editUrl} target="_blank" rel="noreferrer">Open the editable form</a>{" | "}<a href={result.responderUrl} target="_blank" rel="noreferrer">Open the respondent form</a></p>}<Link to="/dashboard/content-studio">Return to Content OS</Link></main>; }
