import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";
import type { Campaign } from "~/lib/growth-engine.server";
const load = createServerFn({ method: "GET" }).handler(async () => (await import("~/lib/growth-engine.server")).dashboard());
const scan = createServerFn({ method: "POST" }).validator((data: { url: string }) => data).handler(async ({ data }) => (await import("~/lib/growth-engine.server")).scan(data.url));
const approve = createServerFn({ method: "POST" }).validator((data: { id: string }) => data).handler(async ({ data }) => (await import("~/lib/growth-engine.server")).approveAndCreateCreative(data.id));
export const Route = createFileRoute("/dashboard/growth-engine" as never)({ loader: () => load(), component: Page });
function Page() { const data = Route.useLoaderData() as { campaigns: Campaign[] }; const fn = useServerFn(scan); const approveFn = useServerFn(approve); const [url, setUrl] = useState(""); const [message, setMessage] = useState(""); return <main className="wrap" style={{ padding: "96px 0" }}><p className="eyebrow">Internal dashboard</p><h1>Growth Engine</h1><p>Scan a public Ellis page. A changed snapshot creates an approval-ready campaign; nothing is published.</p><form onSubmit={(e) => { e.preventDefault(); void fn({ data: { url } }).then((r) => { setMessage(r.changed ? "Campaign queued for approval." : "No website change detected."); window.location.reload(); }).catch((x) => setMessage(x.message)); }}><label>Published page URL<input type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://ellisaistudio.com/portfolio" required /></label><button className="button">Detect update and build campaign</button>{message && <p role="status">{message}</p>}</form><section><h2>Approval queue</h2>{data.campaigns.map((c: Campaign) => <article key={c.id} style={{ borderTop: "1px solid #dbe3df", padding: "24px 0" }}><strong>{c.status.replace("_", " ")}</strong><h3>{c.title} · {c.type}</h3><p>{c.summary}</p>{c.status === "pending_approval" && <button className="button" onClick={() => void approveFn({ data: { id: c.id } }).then(() => window.location.reload()).catch((x) => setMessage(x.message))}>Approve and create creative package</button>}<p><b>CTA:</b> {c.cta}</p><p><b>Schedule:</b> {c.schedule.join(" · ")}</p>{Object.entries(c.content).map(([platform, copy]) => <details key={platform}><summary>{platform}</summary><p style={{ whiteSpace: "pre-wrap" }}>{copy}</p></details>)}<details><summary>Branded image prompts</summary>{c.imagePrompts.map((p: string) => <p key={p}>{p}</p>)}</details>{c.creative && <details open><summary>Creative package — concepts ready</summary>{Object.entries(c.creative.concepts).map(([type, prompt]) => <p key={type}><b>{type}:</b> {prompt}</p>)}</details>}<p>{c.hashtags.join(" ")}</p></article>)}</section></main>; }
