import { createFileRoute } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";
import { leadDashboardAllowed } from "~/lib/lead-dashboard-auth.server";
import { getLead, updatePipelineStatus } from "~/lib/lead-repository.server";
import { PIPELINE_STATUSES, type PipelineStatus } from "~/types/lead";
const load = createServerFn({ method: "GET" }).validator((data: { leadId: string }) => data).handler(async ({ data }) => leadDashboardAllowed() ? { accessRequired: false, record: await getLead(data.leadId) } : { accessRequired: true, record: null });
const updateStatus = createServerFn({ method: "POST" }).validator((data: { leadId: string; status: PipelineStatus }) => data).handler(async ({ data }) => { if (!leadDashboardAllowed()) throw new Error("Dashboard access was denied."); if (!PIPELINE_STATUSES.includes(data.status)) throw new Error("Pipeline status is invalid."); await updatePipelineStatus(data.leadId, data.status); });
export const Route = createFileRoute("/dashboard/leads/$leadId")({ loader: ({ params }) => load({ data: params }), component: Page });
function Page() { const data = Route.useLoaderData() as Awaited<ReturnType<typeof load>>; const update = useServerFn(updateStatus); if (data.accessRequired || !data.record) return <main className="wrap" style={{ padding: "96px 0" }}><h1>Lead unavailable</h1><p>Unlock the Lead Intelligence dashboard before opening a record.</p></main>; const { lead, analysis, activities } = data.record; return <main className="wrap" style={{ padding: "96px 0", maxWidth: 960 }}><p className="eyebrow">Lead Intelligence</p><h1>{lead.business_name}</h1><p>{lead.first_name} {lead.last_name} · {lead.email}</p><p>{lead.website}</p><label>Pipeline status<select value={lead.pipeline_status} onChange={(event) => void update({ data: { leadId: lead.id, status: event.target.value as PipelineStatus } }).then(() => window.location.reload())}>{PIPELINE_STATUSES.map((status) => <option value={status} key={status}>{status}</option>)}</select></label>{analysis ? <><section><h2>Opportunity intelligence</h2><p>Opportunity score: {analysis.opportunity_score}/100 · Confidence: {analysis.qualification_confidence}/100 · {analysis.qualification_class.replace("_", " ")}</p><dl><dt>Problem fit</dt><dd>{analysis.problem_fit}</dd><dt>Potential impact</dt><dd>{analysis.potential_impact}</dd><dt>Urgency</dt><dd>{analysis.urgency_score}</dd><dt>Implementation fit</dt><dd>{analysis.implementation_fit}</dd><dt>Intent</dt><dd>{analysis.intent}</dd></dl></section><section><h2>Interpretation</h2><p>{analysis.interpretation.summary}</p><p><strong>Recommended system:</strong> {analysis.recommended_system_key}</p><h3>Discovery questions</h3><ul>{analysis.interpretation.discoveryQuestions.map((question: string) => <li key={question}>{question}</li>)}</ul></section></> : <p>Analysis is {lead.analysis_status}.</p>}<section><h2>Original problem</h2><p>{lead.primary_challenge}</p><p>{lead.desired_outcome}</p></section>{lead.audit_context && <section><h2>Audit context</h2><p>Audit reference: {lead.audit_context.auditId}</p><p>Evidence is preserved as public observed or inferred context until the prospect confirms it.</p></section>}<section><h2>Activity</h2><ol>{activities.map((activity) => <li key={activity.id}>{new Date(activity.createdAt).toLocaleString()} — {activity.type}</li>)}</ol></section></main>; }
