import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";
import { leadDashboardAllowed, unlockLeadDashboard } from "~/lib/lead-dashboard-auth.server";
import { listLeads } from "~/lib/lead-repository.server";
const load = createServerFn({ method: "GET" }).handler(async () => leadDashboardAllowed() ? { accessRequired: false, leads: await listLeads() } : { accessRequired: true, leads: [] });
const unlock = createServerFn({ method: "POST" }).validator((data: { accessToken: string }) => data).handler(async ({ data }) => unlockLeadDashboard(data.accessToken));
export const Route = createFileRoute("/dashboard/leads")({ loader: () => load(), component: Page });
function Page() { const data = Route.useLoaderData() as Awaited<ReturnType<typeof load>>; const fn = useServerFn(unlock); const [token, setToken] = useState(""); const [error, setError] = useState(""); if (data.accessRequired) return <main className="wrap" style={{ padding: "96px 0", maxWidth: 640 }}><h1>Lead Intelligence</h1><p>This route is protected. Enter the server-configured dashboard access token.</p><form onSubmit={(event) => { event.preventDefault(); void fn({ data: { accessToken: token } }).then(() => window.location.reload()).catch((reason) => setError(reason.message)); }}><label>Access token<input type="password" value={token} onChange={(event) => setToken(event.target.value)} required /></label><button className="button" type="submit">Unlock dashboard</button>{error && <p role="alert">{error}</p>}</form></main>;
 return <main className="wrap" style={{ padding: "96px 0" }}><p className="eyebrow">Internal dashboard</p><h1>Lead Intelligence</h1><p>{data.leads.length} submitted leads</p><div style={{ overflowX: "auto" }}><table><thead><tr><th>Business</th><th>Contact</th><th>Opportunity</th><th>Confidence</th><th>Qualification</th><th>Pipeline</th></tr></thead><tbody>{data.leads.map((lead) => <tr key={lead.id}><td><Link to="/dashboard/leads/$leadId" params={{ leadId: lead.id }}>{lead.business_name}</Link></td><td>{lead.first_name} {lead.last_name}</td><td>{lead.opportunity_score ?? "—"}</td><td>{lead.qualification_confidence ?? "—"}</td><td>{lead.qualification_class?.replace("_", " ") ?? "Pending"}</td><td>{lead.pipeline_status}</td></tr>)}</tbody></table></div></main>; }
