import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";
const load=createServerFn({method:"GET"}).handler(async()=> (await import("~/lib/linkedin.server")).dashboard());
const unlock=createServerFn({method:"POST"}).validator((d:{accessToken:string})=>d).handler(async({data})=>(await import("~/lib/linkedin.server")).unlock(data.accessToken));
const connect=createServerFn({method:"POST"}).handler(async()=>({url:(await import("~/lib/linkedin.server")).authorizationUrl()}));
const publish=createServerFn({method:"POST"}).validator((d:{text:string})=>d).handler(async({data})=>(await import("~/lib/linkedin.server")).publish({text:data.text}));
export const Route=createFileRoute("/dashboard/linkedin")({loader:()=>load(),component:Page});
function Page(){const d=Route.useLoaderData();const u=useServerFn(unlock),c=useServerFn(connect),p=useServerFn(publish);const [token,setToken]=useState(""),[text,setText]=useState(""),[msg,setMsg]=useState("");if(d.message==="Dashboard access required.")return <main className="wrap" style={{padding:"96px 0"}}><h1>LinkedIn publishing</h1><form onSubmit={e=>{e.preventDefault();void u({data:{accessToken:token}}).then(()=>window.location.reload()).catch(x=>setMsg(x.message))}}><input type="password" value={token} onChange={e=>setToken(e.target.value)}/><button className="button">Unlock</button></form><p>{msg}</p></main>;return <main className="wrap" style={{padding:"96px 0"}}><p className="eyebrow">Social publishing</p><h1>LinkedIn</h1>{!d.configured?<p>{d.message}</p>:!d.connected?<button className="button" onClick={()=>void c().then(x=>window.location.assign(x.url)).catch(x=>setMsg(x.message))}>Connect LinkedIn</button>:<><p>Connected as {d.displayName??"LinkedIn member"}.</p><form onSubmit={e=>{e.preventDefault();void p({data:{text}}).then(x=>setMsg(`Published: ${x.id}`)).catch(x=>setMsg(x.message))}}><textarea required value={text} onChange={e=>setText(e.target.value)} rows={5}/><button className="button">Publish text post</button></form></>}<p role="status">{msg}</p></main>}
