import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";
type MetaPost = { id: string; caption: string; status: string; scheduledFor?: number; createdAt: number; results?: string[]; error?: string };
type MetaDashboard = { accessRequired: boolean; configured: boolean; connected: boolean; message?: string; accounts: Array<{ id: string; name: string; instagramId?: string; instagramUsername?: string }>; selected?: { pageId: string; instagramId?: string }; posts: MetaPost[] };
const load = createServerFn({ method: "GET" }).handler(async () => (await import("~/lib/meta-publishing.server")).dashboard());
const unlock = createServerFn({ method: "POST" }).validator((data: { accessToken: string }) => data).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).unlockDashboard(data.accessToken));
const connect = createServerFn({ method: "POST" }).handler(async () => ({ url: (await import("~/lib/meta-publishing.server")).authorizationUrl() }));
const select = createServerFn({ method: "POST" }).validator((data: { pageId: string; instagramId?: string }) => data).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).selectAccount(data.pageId, data.instagramId));
const caption = createServerFn({ method: "POST" }).validator((data: { prompt: string }) => data).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).generateCaption(data.prompt));
const save = createServerFn({ method: "POST" }).validator((data: { caption: string; media: Array<{ url?: string; dataUrl?: string; filename?: string; mimeType?: string }>; targets: Array<"facebook" | "instagram">; scheduledFor?: number }) => data).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).savePost(data));
const publish = createServerFn({ method: "POST" }).validator((data: { id: string }) => data).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).publishPost(data.id));
const due = createServerFn({ method: "POST" }).handler(async () => (await import("~/lib/meta-publishing.server")).processScheduledPosts());
export const Route = createFileRoute("/dashboard/meta")({ loader: () => load(), component: MetaDashboardPage });

function MetaDashboardPage() { const data = Route.useLoaderData(); return <main className="wrap" style={{ padding: "96px 0" }}><p className="eyebrow">Internal dashboard</p><h1>Meta publishing</h1>{data.accessRequired ? <Unlock /> : !data.configured ? <p>{data.message}</p> : !data.connected ? <Connect /> : <Workspace data={data} />}</main>; }
function Unlock() { const [accessToken, setAccessToken] = useState(""); const [error, setError] = useState(""); const fn = useServerFn(unlock); return <form onSubmit={(event) => { event.preventDefault(); void fn({ data: { accessToken } }).then(() => window.location.reload()).catch((reason) => setError(reason.message)); }}><p>This route is protected. Enter the server-configured dashboard access token.</p><input type="password" value={accessToken} onChange={(event) => setAccessToken(event.target.value)} required /><button className="button">Unlock</button>{error && <p role="alert">{error}</p>}</form>; }
function Connect() { const fn = useServerFn(connect); const [error, setError] = useState(""); const [redirecting, setRedirecting] = useState(false); async function begin() { if (redirecting) return; setRedirecting(true); try { const result = await fn(); window.location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : "Meta OAuth could not start."); setRedirecting(false); } } return <section><p>Connect the Facebook account that manages the Page and linked Instagram Business account.</p><button className="button" disabled={redirecting} onClick={() => void begin()}>{redirecting ? "Opening Meta…" : "Connect Meta"}</button>{error && <p role="alert">{error}</p>}</section>; }
function Workspace({ data }: { data: MetaDashboard }) { const choose = useServerFn(select); const runDue = useServerFn(due); const [pageId, setPageId] = useState(data.selected?.pageId ?? data.accounts[0]?.id ?? ""); const account = data.accounts.find((item) => item.id === pageId); return <><section><label>Facebook Page<select value={pageId} onChange={(event) => setPageId(event.target.value)}>{data.accounts.map((item) => <option value={item.id} key={item.id}>{item.name}{item.instagramUsername ? ` — @${item.instagramUsername}` : ""}</option>)}</select></label><button className="button" onClick={() => void choose({ data: { pageId, instagramId: account?.instagramId } }).then(() => window.location.reload())}>Use this account</button></section><Composer instagramAvailable={Boolean(account?.instagramId)} /><section style={{ marginTop: 48 }}><button className="button button-secondary" onClick={() => void runDue().then(() => window.location.reload())}>Publish due posts</button><h2>Publishing history</h2>{data.posts.length ? data.posts.map((post) => <History post={post} key={post.id} />) : <p>No drafts or publishing history yet.</p>}</section></>; }
function Composer({ instagramAvailable }: { instagramAvailable: boolean }) { const saveFn = useServerFn(save); const captionFn = useServerFn(caption); const [text, setText] = useState(""); const [prompt, setPrompt] = useState(""); const [url, setUrl] = useState(""); const [file, setFile] = useState<{ dataUrl: string; filename: string; mimeType: string }>(); const [facebook, setFacebook] = useState(true); const [instagram, setInstagram] = useState(false); const [schedule, setSchedule] = useState(""); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); try { const post = await saveFn({ data: { caption: text, media: [{ url: url || undefined, ...file }], targets: ([facebook && "facebook", instagram && "instagram"].filter(Boolean) as Array<"facebook" | "instagram">), scheduledFor: schedule ? new Date(schedule).getTime() : undefined } }); setMessage(post.status === "scheduled" ? "Scheduled draft saved." : "Draft saved."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Could not save draft."); } } return <form onSubmit={submit} style={{ display: "grid", gap: 12, maxWidth: 700, marginTop: 40 }}><h2>Create a post</h2><label>AI caption topic<input value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Example: websites that turn calls into booked jobs" /></label><button type="button" className="button button-secondary" onClick={() => void captionFn({ data: { prompt } }).then(setText).catch((reason) => setMessage(reason.message))}>Generate caption</button><label>Caption<textarea value={text} onChange={(event) => setText(event.target.value)} required rows={6} /></label><label>Public HTTPS media URL (required for Instagram)<input type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://…" /></label><label>Upload image/video for Facebook<input type="file" accept="image/*,video/*" onChange={(event) => { const selected = event.target.files?.[0]; if (!selected) return; const reader = new FileReader(); reader.onload = () => setFile({ dataUrl: String(reader.result), filename: selected.name, mimeType: selected.type }); reader.readAsDataURL(selected); }} /></label><label><input type="checkbox" checked={facebook} onChange={(event) => setFacebook(event.target.checked)} /> Facebook Page</label><label><input type="checkbox" checked={instagram} disabled={!instagramAvailable} onChange={(event) => setInstagram(event.target.checked)} /> Instagram Business{!instagramAvailable && " (link an Instagram Business account to the selected Page)"}</label><label>Schedule for later (optional)<input type="datetime-local" value={schedule} onChange={(event) => setSchedule(event.target.value)} /></label><button className="button">Save draft</button>{message && <p role="status">{message}</p>}</form>; }
function History({ post }: { post: MetaPost }) { const publishFn = useServerFn(publish); const [message, setMessage] = useState(post.error ?? ""); return <article style={{ borderTop: "1px solid #dbe3df", padding: "20px 0" }}><strong>{post.status}</strong><p>{post.caption}</p><p>{post.scheduledFor ? `Scheduled: ${new Date(post.scheduledFor).toLocaleString()}` : `Created: ${new Date(post.createdAt).toLocaleString()}`}</p>{post.results?.map((item) => <p key={item}>{item}</p>)}{post.status !== "published" && <button className="button button-secondary" onClick={() => void publishFn({ data: { id: post.id } }).then(() => window.location.reload()).catch((reason) => setMessage(reason.message))}>Publish now</button>}{message && <p role="alert">{message}</p>}</article>; }
