import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";

type Analytics = { postId: string; platform: "facebook" | "instagram"; collectedAt: number; reach?: number; impressions?: number; engagement?: number; reactions?: number; comments?: number; shares?: number; clicks?: number; videoViews?: number; unavailable?: string[] };
type Post = { id: string; caption: string; status: "draft" | "scheduled" | "published" | "failed"; scheduledFor?: number; createdAt: number; publishedAt?: number; results?: string[]; error?: string; retryCount?: number; lastRetriedAt?: number; lastRetryReason?: string };
type Dashboard = { accessRequired: boolean; configured: boolean; connected: boolean; message?: string; accounts: Array<{ id: string; name: string; instagramId?: string; instagramUsername?: string }>; selected?: { pageId: string; instagramId?: string }; posts: Post[] };

const load = createServerFn({ method: "GET" }).handler(async () => (await import("~/lib/meta-publishing.server")).dashboard());
const unlock = createServerFn({ method: "POST" }).validator((d: { accessToken: string }) => d).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).unlockDashboard(data.accessToken));
const connect = createServerFn({ method: "POST" }).handler(async () => ({ url: (await import("~/lib/meta-publishing.server")).authorizationUrl() }));
const select = createServerFn({ method: "POST" }).validator((d: { pageId: string; instagramId?: string }) => d).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).selectAccount(data.pageId, data.instagramId));
const retry = createServerFn({ method: "POST" }).validator((d: { id: string; reason: string }) => d).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).retryFailedPost(data.id, data.reason));
const collect = createServerFn({ method: "POST" }).validator((d: { id: string }) => d).handler(async ({ data }) => (await import("~/lib/meta-publishing.server")).collectAnalytics(data.id));
const analytics = createServerFn({ method: "GET" }).handler(async () => (await import("~/lib/meta-publishing.server")).analyticsForDashboard());
export const Route = createFileRoute("/dashboard/meta")({ loader: () => load(), component: Page });

function Page() { const data = Route.useLoaderData() as Dashboard; return <main className="wrap" style={{ padding: "96px 0" }}><p className="eyebrow">Internal dashboard</p><h1>Meta Publishing</h1>{data.accessRequired ? <Unlock /> : !data.configured ? <p>{data.message}</p> : !data.connected ? <Connect /> : <Workspace data={data} />}</main>; }
function Unlock() { const fn = useServerFn(unlock); const [token, setToken] = useState(""); const [error, setError] = useState(""); return <form onSubmit={(e) => { e.preventDefault(); void fn({ data: { accessToken: token } }).then(() => window.location.reload()).catch((x) => setError(x.message)); }}><p>Enter the server-configured dashboard access token.</p><input type="password" value={token} onChange={(e) => setToken(e.target.value)} required /><button className="button">Unlock</button>{error && <p role="alert">{error}</p>}</form>; }
function Connect() { const fn = useServerFn(connect); const [error, setError] = useState(""); return <section><p>Connect the Facebook account that manages the Page and linked Instagram Business account.</p><button className="button" onClick={() => void fn().then((r) => window.location.assign(r.url)).catch((x) => setError(x.message))}>Connect Meta</button>{error && <p role="alert">{error}</p>}</section>; }
function Workspace({ data }: { data: Dashboard }) { const choose = useServerFn(select); const getAnalytics = useServerFn(analytics); const [page, setPage] = useState(data.selected?.pageId ?? data.accounts[0]?.id ?? ""); const [metrics, setMetrics] = useState<Analytics[]>([]); const account = data.accounts.find((x) => x.id === page); const groups: Array<[string, Post[]]> = [["Scheduled", data.posts.filter((x) => x.status === "scheduled")], ["Drafts", data.posts.filter((x) => x.status === "draft")], ["Failed", data.posts.filter((x) => x.status === "failed")], ["Published", data.posts.filter((x) => x.status === "published")]]; return <><section><h2>Connection health</h2><p>Connected Pages: {data.accounts.length} · Selected: {account?.name ?? "None"}{account?.instagramUsername ? ` · Instagram @${account.instagramUsername}` : " · No linked Instagram Business account"}</p><label>Facebook Page<select value={page} onChange={(e) => setPage(e.target.value)}>{data.accounts.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="button" onClick={() => void choose({ data: { pageId: page, instagramId: account?.instagramId } }).then(() => window.location.reload())}>Use selected account</button><button className="button button-secondary" onClick={() => void getAnalytics().then(setMetrics)}>Refresh analytics</button></section><section style={{ marginTop: 48 }}><h2>Publishing queue</h2>{groups.map(([title, posts]) => <div key={title}><h3>{title} ({posts.length})</h3>{posts.length ? posts.map((post) => <Job key={post.id} post={post} metrics={metrics.filter((x) => x.postId === post.id)} />) : <p>No {title.toLowerCase()}.</p>}</div>)}</section></>; }
function Job({ post, metrics }: { post: Post; metrics: Analytics[] }) { const retryFn = useServerFn(retry); const collectFn = useServerFn(collect); const [message, setMessage] = useState(""); return <article style={{ borderTop: "1px solid #dbe3df", padding: "20px 0" }}><strong>{post.status}</strong><p>{post.caption}</p><p>Created: {new Date(post.createdAt).toLocaleString()}{post.scheduledFor ? ` · Scheduled: ${new Date(post.scheduledFor).toLocaleString()}` : ""}{post.publishedAt ? ` · Published: ${new Date(post.publishedAt).toLocaleString()}` : ""}</p><p>Timeline: draft → {post.status === "scheduled" ? "scheduled" : post.status === "published" ? "approved → publishing → published" : post.status === "failed" ? "publishing → failed" : "needs review"}</p>{post.error && <p role="alert"><b>Failure reason:</b> {post.error}</p>}<p>Retries: {post.retryCount ?? 0}{post.lastRetriedAt ? ` · Last retry: ${new Date(post.lastRetriedAt).toLocaleString()} (${post.lastRetryReason})` : ""}</p>{post.status === "failed" && <button className="button button-secondary" onClick={() => { const reason = window.prompt("Retry reason", "Manual review completed") ?? ""; if (reason) void retryFn({ data: { id: post.id, reason } }).then(() => window.location.reload()).catch((x) => setMessage(x.message)); }}>Retry failed job</button>}{post.status === "published" && <button className="button button-secondary" onClick={() => void collectFn({ data: { id: post.id } }).then(() => window.location.reload()).catch((x) => setMessage(x.message))}>Collect analytics</button>}{metrics.map((m) => <details key={`${m.platform}-${m.collectedAt}`}><summary>{m.platform} metrics · {new Date(m.collectedAt).toLocaleString()}</summary><p>Reach: {m.reach ?? "Unavailable"} · Impressions: {m.impressions ?? "Unavailable"} · Engagement: {m.engagement ?? "Unavailable"} · Reactions: {m.reactions ?? "Unavailable"} · Comments: {m.comments ?? "Unavailable"} · Shares: {m.shares ?? "Unavailable"} · Clicks: {m.clicks ?? "Unavailable"} · Video views: {m.videoViews ?? "Unavailable"}</p>{m.unavailable?.map((x) => <p key={x}>{x}</p>)}</details>)}{message && <p role="alert">{message}</p>}</article>; }
