import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";
import type { ProspectReport } from "~/lib/prospect-intelligence.server";
import "~/styles/prospect-engine.css";

const load = createServerFn({ method: "GET" }).handler(async () => (await import("~/lib/prospect-intelligence.server")).dashboard());
const audit = createServerFn({ method: "POST" }).validator((data: { businessName: string; website: string }) => data).handler(async ({ data }) => (await import("~/lib/prospect-intelligence.server")).research(data));
const discover = createServerFn({ method: "POST" }).validator((data: { query: string; location: string }) => data).handler(async ({ data }) => (await import("~/lib/prospect-intelligence.server")).discover(data));
const draft = createServerFn({ method: "POST" }).validator((data: { id: string }) => data).handler(async ({ data }) => (await import("~/lib/prospect-intelligence.server")).generateOutreach(data.id));
const stage = createServerFn({ method: "POST" }).validator((data: { id: string; stage: "queued" | "replied" | "meeting" | "won" | "lost" }) => data).handler(async ({ data }) => (await import("~/lib/prospect-intelligence.server")).updatePipeline(data));
export const Route = createFileRoute("/dashboard/prospects")({ loader: () => load(), component: Engine });

function Engine() {
  const data = Route.useLoaderData(); const auditFn = useServerFn(audit); const discoveryFn = useServerFn(discover); const draftFn = useServerFn(draft); const stageFn = useServerFn(stage);
  const [selected, setSelected] = useState<ProspectReport | undefined>(data.reports[0]); const [modal, setModal] = useState<"audit" | "discover" | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [form, setForm] = useState({ businessName: "", website: "", query: "dental practices", location: "Austin, TX" });
  const runAudit = async () => { setBusy(true); try { const item = await auditFn({ data: form }); setSelected(item); setModal(null); setNotice("Public website audit complete. The prospect is ranked and ready for review."); } catch (e) { setNotice(e instanceof Error ? e.message : "Audit failed."); } finally { setBusy(false); } };
  const runDiscovery = async () => { setBusy(true); try { const result = await discoveryFn({ data: form }); setSelected(result.reports[0]); setModal(null); setNotice(`${result.discovered} businesses were discovered and audited. ${result.skipped} unavailable sites were skipped.`); } catch (e) { setNotice(e instanceof Error ? e.message : "Discovery failed."); } finally { setBusy(false); } };
  const doDraft = async () => { if (!selected) return; await draftFn({ data: { id: selected.id } }); setNotice("Personalized subject line and email draft generated. Review before sending."); };
  const doStage = async (next: "queued" | "replied" | "meeting" | "won" | "lost") => { if (!selected) return; await stageFn({ data: { id: selected.id, stage: next } }); setNotice(next === "queued" ? "Queued for Pluto Mail with a 6-day follow-up." : `Sales CRM updated: ${next}.`); };
  const m = data.metrics; const cards = [[m.researched,"Businesses researched"],[m.qualified,"Qualified prospects"],[m.sent,"Emails queued / sent"],[`${m.replyRate}%`,"Reply rate"],[m.meetings,"Meetings booked"],[m.won,"Deals closed"],[`$${m.revenue.toLocaleString()}`,"Revenue generated"],[`$${m.averageDeal.toLocaleString()}`,"Average deal size"]];
  return <main className="prospect-engine"><header className="pe-top"><div className="pe-brand"><i>e</i><span><b>ELLIS AI STUDIO</b><small>GROWTH OPERATIONS</small></span></div><nav><Link to="/dashboard/content-studio">Command center</Link><Link to="/dashboard/mail">Pluto Mail</Link><a className="active" href="#pipeline">Prospects</a></nav><div className="pe-status"><span/>Discovery ready <button onClick={() => setModal("discover")}>Discover businesses</button></div></header>
    <section className="pe-hero"><div><p className="pe-kicker">NATIONAL PROSPECT ENGINE <em>•</em> PUBLIC-WEB INTELLIGENCE</p><h1>Find the gaps.<br/><i>Build the growth.</i></h1><p className="pe-sub">Discover, audit, rank, and convert businesses using verified public evidence. AI findings are prompts for human review—not claims about a business.</p><div className="pe-hero-actions"><button onClick={() => setModal("discover")}>Start discovery →</button><button onClick={() => setModal("audit")}>Audit a website</button></div></div><aside><div className="pe-gauge"><b>{data.reports.length}</b><span>LIVE<br/>RESEARCHED</span></div><p>Pipeline is evidence-led</p><strong>{m.qualified}</strong><small>qualified opportunities in CRM</small></aside></section>
    <section className="pe-metrics">{cards.map(([value,label]) => <article key={String(label)}><b>{value}</b><span>{label}</span><small>Live pipeline metric</small></article>)}</section>
    <section className="pe-content" id="pipeline"><header><div><p className="pe-kicker">PRIORITY RANKING & SALES CRM</p><h2>Work the highest-value opportunities first.</h2></div><button className="pe-add" onClick={() => setModal("audit")}>+ Add prospect</button></header>{notice && <p className="pe-notice">{notice}</p>}<div className="pe-workspace"><section className="pe-table"><div className="pe-table-head"><span>Business / location</span><span>AI audit findings</span><span>Priority</span><span>CRM stage</span></div>{data.reports.length ? data.reports.map((p) => <button className={`pe-row ${selected?.id === p.id ? "selected" : ""}`} key={p.id} onClick={() => setSelected(p)}><div><b>{p.businessName}</b><span>{p.industry ?? "Business"} · {p.city ?? "Location pending"}</span></div><div className="pe-signal"><i>SEO {p.seoScore ?? "—"}</i><i>Mobile {p.mobileScore ?? "—"}</i><i>Infra {p.infrastructureScore ?? "—"}</i></div><strong>{stars(p.priority)}<small>{p.score}/100</small></strong><em className={`stage ${(p.stage ?? "researched").replaceAll("_", "-")}`}>{(p.stage ?? "researched").replaceAll("_", " ")}</em></button>) : <div className="pe-empty">No businesses researched yet. Start a discovery run or audit a public website.</div>}</section>
      <aside className="pe-detail">{selected ? <><header><div><p className="pe-kicker">{stars(selected.priority)} {selected.priority ?? "unranked"} opportunity</p><h3>{selected.businessName}</h3><span>{selected.website}</span></div><button className="more">•••</button></header><div className="pe-score-row"><div><strong>{selected.score}</strong><span>Opportunity score</span></div><div className="pe-bars"><i>SEO <b>{selected.seoScore ?? "—"}</b></i><i>Mobile <b>{selected.mobileScore ?? "—"}</b></i><i>Infrastructure <b>{selected.infrastructureScore ?? "—"}</b></i></div></div><section className="pe-observation"><p>AI AUDIT FINDINGS</p>{(selected.findings ?? selected.weaknesses).map((f) => <b key={f}>• {f}</b>)}<small>Automatically inferred from public content. Verify before outreach.</small></section><section className="pe-contact"><p>CONTACT & OUTREACH</p><div><span>Email</span><b>{selected.email ?? "Not detected"}</b></div><div><span>Phone</span><b>{selected.phone ?? "Not detected"}</b></div><div><span>Follow-up</span><b>{selected.outreach?.followUpAt ? new Date(selected.outreach.followUpAt).toLocaleDateString() : "Not scheduled"}</b></div></section><div className="pe-detail-actions"><button onClick={() => void doDraft()}>Generate email draft</button><Link to="/dashboard/mail" onClick={() => void doStage("queued")}>Queue in Pluto Mail <span>→</span></Link></div><footer><button onClick={() => void doStage("replied")}>Mark reply</button><button onClick={() => void doStage("meeting")}>Record meeting</button><button onClick={() => void doStage("won")}>Mark won</button></footer></> : <div className="pe-empty">Select a prospect to view audit evidence.</div>}</aside></div></section>
    {modal && <div className="pe-modal-backdrop"><form className="pe-modal" onSubmit={(e) => { e.preventDefault(); void (modal === "discover" ? runDiscovery() : runAudit()); }}><header><div><p className="pe-kicker">{modal === "discover" ? "GOOGLE PLACES DISCOVERY" : "PUBLIC WEBSITE REVIEW"}</p><h2>{modal === "discover" ? "Discover businesses" : "Audit a business"}</h2></div><button type="button" onClick={() => setModal(null)}>×</button></header><p>{modal === "discover" ? "Search a configured public directory, then audit each accessible website. Requires a Google Maps API key." : "Inspect a public website for evidence-backed growth opportunities."}</p>{modal === "discover" ? <><label>Industry or business type<input value={form.query} onChange={(e) => setForm({...form,query:e.target.value})} required /></label><label>City, state or region<input value={form.location} onChange={(e) => setForm({...form,location:e.target.value})} required /></label></> : <><label>Business name<input value={form.businessName} onChange={(e) => setForm({...form,businessName:e.target.value})} required /></label><label>Public website<input type="url" value={form.website} onChange={(e) => setForm({...form,website:e.target.value})} required placeholder="https://example.com" /></label></>}<button disabled={busy}>{busy ? "Processing public evidence…" : modal === "discover" ? "Discover and audit →" : "Run AI audit →"}</button></form></div>}
  </main>;
}
function stars(priority?: ProspectReport["priority"]) { return priority === "immediate" ? "★★★★★" : priority === "high" ? "★★★★" : priority === "medium" ? "★★★" : "★★"; }
