import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn, useServerFn } from "@tanstack/react-start";
import type { Session } from "~/lib/validation.server";
const load = createServerFn({ method: "GET" }).handler(async () => (await import("~/lib/validation.server")).dashboard());
const create = createServerFn({ method: "POST" }).validator((d: { businessName: string; website: string; notes?: string }) => d).handler(async ({ data }) => (await import("~/lib/validation.server")).create(data));
const review = createServerFn({ method: "POST" }).validator((d: { id: string; section: string; decision: "approved" | "rejected" | "needs_revision"; note?: string }) => d).handler(async ({ data }) => (await import("~/lib/validation.server")).review(data));
const exportMd = createServerFn({ method: "POST" }).validator((d: { id: string }) => d).handler(async ({ data }) => { const { sessions } = await (await import("~/lib/validation.server")).dashboard(); const s = sessions.find((x) => x.id === data.id); if (!s) throw new Error("Validation session was not found."); return (await import("~/lib/validation.server")).markdown(s); });
export const Route = createFileRoute("/dashboard/validation")({ loader: () => load(), component: Page });
function Page() { const data = Route.useLoaderData() as { sessions: Session[]; sections: string[] }; const createFn = useServerFn(create); const reviewFn = useServerFn(review); const exportFn = useServerFn(exportMd); const [name,setName]=useState(""); const [url,setUrl]=useState(""); const [notes,setNotes]=useState(""); const [message,setMessage]=useState(""); return <main className="wrap" style={{padding:"96px 0"}}><p className="eyebrow">Internal dashboard</p><h1>Platform Validation</h1><p>Review-only: no outreach or proposal delivery is authorized here.</p><form onSubmit={(e)=>{e.preventDefault();void createFn({data:{businessName:name,website:url,notes}}).then(()=>window.location.reload()).catch(x=>setMessage(x.message));}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Business name" required/><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="Website URL" required/><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional notes"/><button className="button">Create validation session</button>{message&&<p>{message}</p>}</form>{data.sessions.map(s=><article key={s.id} style={{borderTop:"1px solid #dbe3df",padding:"24px 0"}}><h2>{s.package.businessName}</h2><p>Opportunity: {s.package.reasoning}</p><p>Quality scores: {Object.entries(s.scores).map(([k,v])=>`${k} ${v}/5`).join(" · ")}</p>{data.sections.map(section=><p key={section}><b>{section}:</b> {s.decisions[section]} <button onClick={()=>void reviewFn({data:{id:s.id,section,decision:"approved"}}).then(()=>window.location.reload())}>Approve</button> <button onClick={()=>void reviewFn({data:{id:s.id,section,decision:"needs_revision"}}).then(()=>window.location.reload())}>Needs revision</button></p>)}<button className="button button-secondary" onClick={()=>void exportFn({data:{id:s.id}}).then(x=>navigator.clipboard.writeText(x).then(()=>setMessage("Markdown packet copied.")))}>Export Markdown</button><details><summary>History and notes</summary>{s.history.map(x=><p key={x}>{x}</p>)}{Object.entries(s.notes).map(([k,v])=><p key={k}>{k}: {v}</p>)}</details></article>)}</main>; }
