import { useMemo, useState, type Dispatch, type ReactNode, type SetStateAction } from "react";

const navigation = ["Dashboard", "Deliverables", "Business Connections", "Documents", "Meetings", "Messages", "Invoices", "Settings"] as const;
type WorkspaceSection = (typeof navigation)[number];

const deliverables = [
  ["Website", "In review", "Jul 16", "v2.4"], ["Automation", "In progress", "Jul 14", "v1.2"],
  ["SEO", "In progress", "Jul 12", "v1.0"], ["Lead System", "Ready for review", "Jul 11", "v1.8"],
  ["CRM", "Planned", "Jul 09", "—"], ["AI Assistant", "Planned", "Jul 08", "—"],
  ["Documentation", "In progress", "Jul 15", "v1.1"],
] as const;

const accessRequests = [
  ["Google Analytics", "To establish the current conversion baseline and measure improvement.", "Reporting and configured properties", "No billing, users, or account settings", "2 business days"],
  ["Google Search Console", "To identify search visibility and technical issues affecting demand.", "Search performance and indexing data", "No website publishing controls", "2 business days"],
  ["Google Workspace", "To coordinate implementation meetings and approved communication workflows.", "Only the shared project calendar and approved mailbox", "No personal files or unrelated email", "1 business day"],
  ["Cloudflare", "To prepare performance, security, and domain changes for approval.", "DNS and site performance settings", "No billing or account ownership changes", "3 business days"],
  ["Google Business Profile", "To improve local visibility and reporting.", "Business profile performance", "No ownership transfer or billing", "2 business days"],
  ["HubSpot", "To connect lead routing and lifecycle reporting.", "Approved pipelines and contact properties", "No account ownership or billing", "3 business days"],
  ["Stripe", "To measure approved conversion and payment events.", "Read-only payment reporting", "No payouts, refunds, or account changes", "2 business days"],
] as const;

const timeline = [
  ["Discovery", "Complete", "Jul 8"], ["Research", "Complete", "Jul 14"], ["Strategy", "Current", "Jul 21"],
  ["Implementation", "Upcoming", "Jul 28"], ["QA", "Upcoming", "Aug 11"], ["Launch", "Upcoming", "Aug 18"], ["Optimization", "Upcoming", "Ongoing"],
] as const;

const documents = [
  ["Service Agreement", "Contract", "Jul 03"], ["July Invoice", "Invoice", "Jul 01"], ["Friction Audit — Draft", "Audit report", "Jul 14"], ["Strategy Session Notes", "Meeting notes", "Jul 16"], ["Lead System Training", "Video", "Jul 16"],
] as const;

export function ClientWorkspace() {
  const [active, setActive] = useState<WorkspaceSection>("Dashboard");
  const [requests, setRequests] = useState<Record<string, "Pending" | "Approved" | "Declined">>({});
  const [documentFilter, setDocumentFilter] = useState("All");
  const [menuOpen, setMenuOpen] = useState(false);
  const filteredDocuments = useMemo(() => documentFilter === "All" ? documents : documents.filter(([, kind]) => kind === documentFilter), [documentFilter]);

  return <div className="workspace-shell">
    <aside className={`workspace-sidebar ${menuOpen ? "is-open" : ""}`}>
      <a href="/" className="workspace-brand"><span>ELLIS</span><small>AI STUDIO</small></a>
      <div className="workspace-client"><span className="workspace-avatar">JE</span><div><b>Ellis AI Studio</b><small>Client workspace</small></div></div>
      <nav aria-label="Client workspace navigation">{navigation.map((item) => <button key={item} className={active === item ? "is-active" : ""} onClick={() => { setActive(item); setMenuOpen(false); }}><span>{navSymbol(item)}</span>{item}{item === "Messages" ? <em>2</em> : null}</button>)}</nav>
      <div className="workspace-sidebar-foot"><p>Need a hand?</p><a href="mailto:hello@ellisaistudio.com">Contact Ellis AI Studio <span>→</span></a></div>
    </aside>

    <main className="workspace-main">
      <header className="workspace-topbar"><button className="workspace-menu" aria-label="Toggle navigation" onClick={() => setMenuOpen((open) => !open)}>☰</button><div><p className="workspace-kicker">Client workspace</p><h1>{active}</h1></div><div className="workspace-top-actions"><button className="workspace-search" aria-label="Search">⌕ <span>Search workspace</span></button><button className="workspace-notice" aria-label="Notifications">◌<i /></button><button className="workspace-profile"><span>JE</span><b>Jake Ellis</b></button></div></header>
      {active === "Dashboard" ? <Dashboard /> : null}
      {active === "Deliverables" ? <Deliverables /> : null}
      {active === "Business Connections" ? <Connections requests={requests} setRequests={setRequests} /> : null}
      {active === "Documents" ? <Documents filter={documentFilter} setFilter={setDocumentFilter} rows={filteredDocuments} /> : null}
      {active === "Meetings" ? <Meetings /> : null}
      {active === "Messages" ? <Messages /> : null}
      {active === "Invoices" ? <Billing /> : null}
      {active === "Settings" ? <Settings /> : null}
    </main>
  </div>;
}

function Dashboard() { return <div className="workspace-content">
  <section className="workspace-welcome"><div><p className="workspace-kicker">Tuesday, July 18</p><h2>Welcome back, Jake.</h2><p>Your strategy is taking shape. Here’s the work that needs your attention this week.</p></div><button className="button button-dark">View project plan <span className="arrow">→</span></button></section>
  <section className="workspace-metrics"><Metric label="Current project" value="Growth Systems" detail="Strategy phase" /><Metric label="Project status" value="On track" detail="42% complete" tone="good" /><Metric label="Next milestone" value="Strategy approval" detail="Due Jul 21" /><Metric label="Upcoming meeting" value="Jul 21 · 2:00 PM" detail="Google Meet" /></section>
  <section className="workspace-grid workspace-grid-main"><div className="workspace-panel workspace-timeline"><PanelHeading title="Project timeline" action="View plan" /><div>{timeline.map(([name, status, date], index) => <div className={`timeline-row ${status === "Current" ? "is-current" : status === "Complete" ? "is-complete" : ""}`} key={name}><span className="timeline-dot">{status === "Complete" ? "✓" : index + 1}</span><div><b>{name}</b><small>{status === "Current" ? "In progress now" : status}</small></div><time>{date}</time></div>)}</div></div><div className="workspace-panel workspace-meeting-card"><PanelHeading title="Next meeting" /><p className="workspace-kicker">Strategy session</p><h3>Growth systems review</h3><p>Monday, July 21 <br />2:00 PM — 3:00 PM PDT</p><div className="workspace-meeting-actions"><button className="button button-dark">Join Google Meet <span className="arrow">→</span></button><button className="workspace-text-button">View agenda</button></div></div></section>
  <section className="workspace-grid workspace-grid-secondary"><div className="workspace-panel"><PanelHeading title="Latest deliverables" action="See all" /><div className="workspace-deliverable-list">{deliverables.slice(0, 3).map(([name, status, date]) => <div key={name}><span className="deliverable-icon">{name.slice(0, 1)}</span><div><b>{name}</b><small>{status} · Updated {date}</small></div><button aria-label={`Preview ${name}`}>↗</button></div>)}</div></div><div className="workspace-panel"><PanelHeading title="Outstanding actions" /><ul className="workspace-actions"><li><span>01</span><div><b>Approve strategy direction</b><small>Needed before implementation begins.</small></div><button>Review</button></li><li><span>02</span><div><b>Provide Google Analytics access</b><small>Requested today · takes about two minutes.</small></div><button>Open</button></li></ul></div><div className="workspace-panel"><PanelHeading title="Recent activity" /><ul className="workspace-activity"><li><span>●</span><p><b>Strategy presentation</b> was updated.<small>Today, 9:42 AM</small></p></li><li><span>●</span><p>Ellis AI Studio added <b>two action items</b>.<small>Yesterday, 4:16 PM</small></p></li><li><span>●</span><p>Your Friction Audit is <b>ready for review</b>.<small>Jul 14, 11:02 AM</small></p></li></ul></div></section>
</div>; }

function Projects() { const projects = [{ name: "Growth Systems", status: "On track", phase: "Strategy", progress: 42, start: "Jul 08", target: "Aug 18", open: 4, complete: 7 }, { name: "Website foundation", status: "Upcoming", phase: "Implementation", progress: 0, start: "Aug 04", target: "Aug 25", open: 0, complete: 0 }]; return <div className="workspace-content"><section className="workspace-welcome compact"><div><p className="workspace-kicker">Your engagements</p><h2>Projects</h2><p>Clear progress, ownership, and next steps across every approved workstream.</p></div><span className="workspace-muted-note">Multiple projects are ready when your scope expands.</span></section><section className="workspace-deliverable-grid">{projects.map((project) => <article key={project.name}><div className="deliverable-card-top"><span>{project.name.slice(0, 1)}</span><em className={project.status === "On track" ? "paid" : "pending"}>{project.status}</em></div><p className="workspace-kicker">Current phase · {project.phase}</p><h3>{project.name}</h3><small>Start {project.start} · Target {project.target}</small><div className="workspace-project-card-progress"><b>{project.progress}% complete</b><i><em style={{ width: `${project.progress}%` }} /></i></div><p className="workspace-project-card-meta">Ellis AI Studio team · {project.open} open tasks · {project.complete} completed</p></article>)}</section></div>; }

function Deliverables() { const [preview, setPreview] = useState<string | null>(null); return <div className="workspace-content"><section className="workspace-welcome compact"><div><p className="workspace-kicker">Project library</p><h2>Deliverables</h2><p>Every active system, asset, and supporting document in one place.</p></div><button className="workspace-filter">All deliverables <span>⌄</span></button></section>{preview ? <section className="workspace-panel workspace-preview"><div><p className="workspace-kicker">Preview</p><h3>{preview}</h3><p>This secure preview area is ready to receive a file from future storage integration.</p></div><button onClick={() => setPreview(null)}>Close</button></section> : null}<section className="workspace-deliverable-grid">{deliverables.map(([name, status, date, version]) => <article key={name}><div className="deliverable-card-top"><span>{name.slice(0, 1)}</span><button aria-label={`More options for ${name}`}>•••</button></div><p className="workspace-kicker">{status}</p><h3>{name}</h3><small>Updated {date} · {version} · Ellis AI Studio</small><div><button onClick={() => setPreview(name)}>Preview</button><button>Download</button><button>History</button></div></article>)}</section></div>; }

void Projects;

function Connections({ requests, setRequests }: { requests: Record<string, "Pending" | "Approved" | "Declined">; setRequests: Dispatch<SetStateAction<Record<string, "Pending" | "Approved" | "Declined">>> }) { return <div className="workspace-content"><section className="workspace-welcome compact"><div><p className="workspace-kicker">Integrations</p><h2>Connections</h2><p>Only connect the tools needed for the work currently in motion. Every request explains its purpose and scope.</p></div><span className="workspace-muted-note">Your data stays yours.</span></section><div className="workspace-access-list">{accessRequests.map(([name, why, canSee, cannotSee, expected]) => { const status = requests[name] ?? "Pending"; return <article key={name}><div className="access-title"><span>{name.slice(0, 1)}</span><div><h3>{name}</h3><p>{why}</p></div><em className={status.toLowerCase()}>{status}</em></div><div className="access-details"><p><b>Permission scope</b>{canSee}</p><p><b>What we cannot see</b>{cannotSee}</p><p><b>Last updated</b>Requested today · {expected}</p></div>{status === "Pending" ? <div className="access-actions"><button className="button button-dark" onClick={() => setRequests((value) => ({ ...value, [name]: "Approved" }))}>Approve connection <span className="arrow">→</span></button><button onClick={() => setRequests((value) => ({ ...value, [name]: "Declined" }))}>Decline</button></div> : <div className="access-response">{status === "Approved" ? "Connected — Ellis AI Studio can now proceed with the approved scope. Reconnect is available when an integration expires." : "This connection was declined. You can reconnect it later from this workspace."}</div>}</article>; })}</div></div>; }

function Documents({ filter, setFilter, rows }: { filter: string; setFilter: (filter: string) => void; rows: readonly (readonly [string, string, string])[] }) { const filters = ["All", "Contract", "Invoice", "Audit report", "Meeting notes", "Video"]; return <div className="workspace-content"><section className="workspace-welcome compact"><div><p className="workspace-kicker">Reference library</p><h2>Documents</h2><p>Contracts, audit materials, training, and decisions — always easy to find.</p></div><button className="workspace-search workspace-document-search">⌕ Search documents</button></section><div className="workspace-filter-row">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "is-active" : ""}>{item}</button>)}</div><section className="workspace-panel workspace-document-list">{rows.map(([name, kind, date]) => <div key={name}><span>{kind.slice(0, 1)}</span><div><b>{name}</b><small>{kind} · Updated {date}</small></div><button>Download</button><button aria-label={`More options for ${name}`}>•••</button></div>)}</section></div>; }

function Meetings() { return <SimplePage eyebrow="Collaboration" title="Meetings" description="A clear record of every working session, decision, and next step."><section className="workspace-grid workspace-grid-secondary"><div className="workspace-panel workspace-meeting-card"><PanelHeading title="Upcoming" /><p className="workspace-kicker">Monday, July 21 · 2:00 PM PDT</p><h3>Growth systems review</h3><p>Review the strategic direction before implementation begins.</p><button className="button button-dark">Join Google Meet <span className="arrow">→</span></button></div><div className="workspace-panel"><PanelHeading title="Past sessions" action="View all" /><ul className="workspace-activity"><li><span>01</span><p><b>Friction Audit review</b><small>Jul 16 · Recording & notes available</small></p></li><li><span>02</span><p><b>Discovery session</b><small>Jul 08 · Action items complete</small></p></li></ul></div></section></SimplePage>; }

function Messages() { return <SimplePage eyebrow="Direct line" title="Messages" description="Keep project communication, files, and decisions in one calm, shared thread."><section className="workspace-panel workspace-message-layout"><aside><b>Project conversation</b><small>2 unread</small><p className="is-selected">Growth Systems <span>9:42 AM</span></p><p>Announcements <span>Jul 15</span></p></aside><div><div className="message-heading"><div><p className="workspace-kicker">Growth Systems</p><h3>Project conversation</h3></div><button>•••</button></div><div className="message-thread"><p><span>EA</span><b>Ellis AI Studio</b><small>Today, 9:42 AM</small><br />We’ve updated the strategy presentation with the revised response-time plan. It’s ready for your review.</p><p className="from-client"><span>JE</span><b>Jake Ellis</b><small>Today, 10:08 AM</small><br />Thank you — I’ll review it before our session.</p></div><div className="message-compose"><input placeholder="Write a message…" /><button>Send <span>→</span></button></div></div></section></SimplePage>; }

function Billing() { return <SimplePage eyebrow="Billing" title="Billing" description="Invoices, receipts, and payment status for your Ellis AI Studio engagement."><section className="workspace-metrics"><Metric label="Paid" value="$4,500" detail="Current engagement" tone="good" /><Metric label="Outstanding" value="$0" detail="Nothing due today" tone="good" /><Metric label="Upcoming payment" value="Aug 01" detail="Implementation milestone" /><Metric label="Receipts" value="2 available" detail="Download anytime" /></section><section className="workspace-panel workspace-document-list"><div><span>J</span><div><b>July 2026 — Growth Systems</b><small>Invoice · Paid Jul 03 · Receipt available</small></div><em className="paid">Paid</em><button>Download</button></div><div><span>J</span><div><b>August 2026 — Implementation</b><small>Upcoming payment · Due Aug 01</small></div><em className="pending">Upcoming</em><button>View</button></div></section></SimplePage>; }

function Settings() { return <SimplePage eyebrow="Workspace preferences" title="Settings" description="Manage contact preferences and how Ellis AI Studio communicates with your team."><section className="workspace-settings"><div className="workspace-panel"><PanelHeading title="Primary contact" /><label>Name<input defaultValue="Jake Ellis" /></label><label>Email<input defaultValue="jake@ellisaistudio.com" /></label><button className="button button-dark">Save changes</button></div><div className="workspace-panel"><PanelHeading title="Notifications" /><label className="workspace-toggle"><input type="checkbox" defaultChecked /><span />Meeting reminders</label><label className="workspace-toggle"><input type="checkbox" defaultChecked /><span />Deliverable updates</label><label className="workspace-toggle"><input type="checkbox" defaultChecked /><span />Action items</label></div></section></SimplePage>; }

function SimplePage({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) { return <div className="workspace-content"><section className="workspace-welcome compact"><div><p className="workspace-kicker">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div></section>{children}</div>; }
function Metric({ label, value, detail, tone }: { label: string; value: string; detail: string; tone?: string }) { return <article><p>{label}</p><b className={tone}>{value}</b><small>{detail}</small></article>; }
function PanelHeading({ title, action }: { title: string; action?: string }) { return <div className="workspace-panel-heading"><h3>{title}</h3>{action ? <button>{action} <span>→</span></button> : null}</div>; }
function navSymbol(item: WorkspaceSection) { return ({ Dashboard: "◫", Deliverables: "◇", "Business Connections": "⊕", Documents: "▤", Meetings: "◷", Messages: "◌", Invoices: "$", Settings: "⚙" })[item]; }
