import { useEffect, useMemo, useState, type ReactNode } from "react";

import profile from "~/data/mock-client-conversion.json";
import { clientPlatform } from "~/lib/client-platform";
import { getClientBusinessInsights, refreshClientBusinessInsights, type ClientBusinessInsights } from "~/server/client-business-insights";

const input = { companyName: profile.businessName, websiteUrl: profile.websiteUrl, contactName: profile.clientName, email: profile.clientEmail, serviceArea: "Primary service area", primaryService: "Growth systems implementation" };
export type InsightView = "dashboard" | "intelligence" | "audit" | "opportunities" | "reports";

export function ClientBusinessInsightsPanel({ view }: { view: InsightView }) {
  const [insights, setInsights] = useState<ClientBusinessInsights | null>(null);
  const [state, setState] = useState<"loading" | "idle" | "running" | "error">("loading");
  useEffect(() => { void loadSaved(); }, []);
  async function loadSaved() { try { setInsights(await getClientBusinessInsights({ data: input })); setState("idle"); } catch { setState("error"); } }
  async function refresh() { try { setState("running"); setInsights(await refreshClientBusinessInsights({ data: input })); setState("idle"); } catch { setState("error"); } }
  if (state === "loading") return <InsightShell title={view === "dashboard" ? "Business Growth Dashboard" : "Business Intelligence"} description="Preparing your executive business overview."><InsightLoading /></InsightShell>;
  if (!insights) return <EmptyReview state={state} onAnalyze={refresh} />;
  if (view === "dashboard") return <OperatingDashboard insights={insights} onRefresh={refresh} running={state === "running"} />;
  if (view === "audit") return <AuditView insights={insights} onRefresh={refresh} running={state === "running"} />;
  if (view === "opportunities") return <OpportunityView insights={insights} onRefresh={refresh} running={state === "running"} />;
  if (view === "reports") return <ReportsView insights={insights} />;
  return <IntelligenceView insights={insights} onRefresh={refresh} running={state === "running"} />;
}

function OperatingDashboard({ insights, onRefresh, running }: ViewProps) { const highest = insights.pillars.slice().sort((a, b) => a.score - b.score)[0]; return <InsightShell title="Business Health Summary" description="An executive view of business performance, focused priorities, and the work Ellis AI Studio is actively advancing." actions={<InsightActions onRefresh={onRefresh} running={running} />}><section className="operating-hero"><div><p className="workspace-kicker">Overall health</p><strong>{insights.metrics.businessHealth}<small>/100</small></strong><p>Current business health score</p></div><dl><div><dt>Highest priority</dt><dd>{highest?.name ?? "Executive review"}</dd></div><div><dt>Biggest opportunity</dt><dd>{insights.opportunities[0] ?? "Growth systems"}</dd></div><div><dt>Monthly opportunity</dt><dd>{insights.metrics.monthlyOpportunity}</dd></div><div><dt>Last analysis</dt><dd>{formatDate(insights.updatedAt)}</dd></div></dl></section><section className="workspace-metrics operating-kpis"><Metric label="Overall Business Health" value={`${insights.metrics.businessHealth}/100`} detail="Executive score" /><Metric label="Overall Friction Score" value={`${insights.metrics.overallFriction}/100`} detail="Opportunity to improve" /><Metric label="Revenue Opportunities" value={insights.metrics.revenueOpportunities} detail="Prioritized initiatives" /><Metric label="Revenue At Risk" value={insights.metrics.revenueAtRisk} detail="Current modeled exposure" /><Metric label="Revenue Recovered" value={insights.metrics.revenueRecovered} detail="Implementation progress" /><Metric label="Lead Response Score" value={`${insights.metrics.leadResponse}/100`} detail="Response readiness" /><Metric label="Website Performance" value={`${insights.metrics.websitePerformance}/100`} detail="Conversion readiness" /><Metric label="Research Freshness" value={insights.metrics.researchFreshness} detail="Latest executive review" /><Metric label="Automation Status" value={insights.metrics.automationStatus} detail="Implementation monitoring" /></section><section className="delivery-center"><div className="delivery-center-heading"><p className="workspace-kicker">Delivery center</p><h3>What Ellis AI Studio is actively improving</h3></div><div className="workspace-grid workspace-grid-secondary"><InsightList title="Current focus" items={insights.recommendations.slice(0, 3).map((item) => item.title)} empty="Your current focus will appear here." /><InsightList title="Next action" items={insights.recommendations.slice(0, 2).map((item) => item.action)} empty="No action is currently required." /><article className="workspace-panel insight-update"><p className="workspace-kicker">Project delivery</p><h3>Strategy → Implementation</h3><p>Progress, deliverables, documents, and meetings are kept separate from your business intelligence.</p></article></div></section></InsightShell>; }

function IntelligenceView({ insights, onRefresh, running }: ViewProps) { return <InsightShell title="Business Intelligence" description={insights.summary} actions={<InsightActions onRefresh={onRefresh} running={running} />}><section className="workspace-metrics insight-metrics"><Metric label="Business type" value="Service business" detail="Executive classification" /><Metric label="Website health" value={`${insights.metrics.websitePerformance}/100`} detail="Conversion readiness" /><Metric label="Lead generation" value={`${insights.metrics.leadResponse}/100`} detail="Readiness assessment" /><Metric label="Brand consistency" value={insights.metrics.websitePerformance ? "Assessed" : "Pending Analysis"} detail="Public-facing review" /><Metric label="Business health" value={`${insights.metrics.businessHealth}/100`} detail="Current executive score" /><Metric label="Confidence" value={`${insights.confidence}%`} detail="Current review confidence" /><Metric label="Market position" value={insights.marketPosition} detail="Executive assessment" /><Metric label="Last updated" value={formatDate(insights.updatedAt)} detail={insights.metrics.researchFreshness} /></section><section className="intelligence-grid"><InsightList title="Business overview" items={insights.overview} empty="Pending Analysis" /><InsightList title="Website summary" items={insights.websiteSummary} empty="Pending Analysis" /><InsightList title="Strengths" items={insights.strengths} empty="Pending Analysis" /><InsightList title="Weaknesses" items={insights.weaknesses} empty="Pending Analysis" /><InsightList title="Improvement opportunities" items={insights.opportunities} empty="Pending Analysis" /><InsightList title="Threats" items={insights.threats} empty="Pending Analysis" /><InsightList title="Competitive insights" items={insights.competitiveInsights} empty="Pending Analysis" /><InsightList title="Latest research" items={insights.latestResearch} empty="Pending Analysis" /></section></InsightShell>; }

function AuditView({ insights, onRefresh, running }: ViewProps) { return <InsightShell title="Friction Audit" description={`The Ellis Friction Framework reviews seven connected growth systems: ${clientPlatform.pillars.join(", ")}.`} actions={<InsightActions onRefresh={onRefresh} running={running} />}><section className="audit-scorecards">{insights.pillars.map((pillar) => <article key={pillar.name}><header><p>{pillar.name}</p><span className={`priority-${pillar.priority.toLowerCase()}`}>{pillar.priority}</span></header><strong>{pillar.score}<small>/100</small></strong><i><em style={{ width: `${pillar.score}%` }} /></i><dl><div><dt>Severity</dt><dd>{pillar.priority}</dd></div><div><dt>Revenue impact</dt><dd>{pillar.impact}</dd></div><div><dt>Difficulty</dt><dd>{pillar.difficulty}</dd></div><div><dt>Progress</dt><dd>{pillar.progress}</dd></div></dl><p>{pillar.recommendation}</p></article>)}</section></InsightShell>; }

function OpportunityView({ insights, onRefresh, running }: ViewProps) { return <InsightShell title="Growth Opportunities" description="Prioritized by expected return, implementation readiness, and the work required to capture the opportunity." actions={<InsightActions onRefresh={onRefresh} running={running} />}><section className="insight-recommendations">{insights.recommendations.map((recommendation, index) => <article key={recommendation.title}><span>0{index + 1}</span><div><p className="workspace-kicker">{recommendation.priority} priority · {recommendation.status}</p><h3>{recommendation.title}</h3><p>{recommendation.action}</p></div><dl><div><dt>Estimated revenue</dt><dd>{recommendation.revenue}</dd></div><div><dt>Difficulty</dt><dd>{recommendation.difficulty}</dd></div><div><dt>Time to implement</dt><dd>{recommendation.timeToImplement}</dd></div><div><dt>Expected ROI</dt><dd>{recommendation.roi}</dd></div></dl></article>)}</section></InsightShell>; }

function ReportsView({ insights }: { insights: ClientBusinessInsights }) { const reports = useMemo(() => ["Business Overview", "Growth Plan", "Friction Audit", "Implementation Roadmap", "Monthly Executive Summary"], []); return <InsightShell title="Executive Reports" description="Client-ready reports with a polished, PDF-ready format for clear decisions and accountable execution."><section className="workspace-deliverable-grid insight-reports">{reports.map((report) => <article key={report}><div className="deliverable-card-top"><span>{report.slice(0, 1)}</span><em className="paid">Ready</em></div><p className="workspace-kicker">Executive report</p><h3>{report}</h3><small>Prepared {formatDate(insights.updatedAt)} · Ellis AI Studio</small><div><button>Preview</button><button>Download PDF</button></div></article>)}</section></InsightShell>; }

function EmptyReview({ state, onAnalyze }: { state: string; onAnalyze: () => Promise<void> }) { return <InsightShell title="Business Growth Dashboard" description={clientPlatform.workspaceDescription}><section className="workspace-empty-state"><span>+</span><h3>Your first executive review is ready to begin.</h3><p>Ellis AI Studio will prepare a concise view of business health, friction priorities, growth opportunities, and the work moving your business forward.</p><button className="button button-dark" disabled={state === "running"} onClick={() => void onAnalyze()}>{state === "running" ? "Preparing your review…" : "Prepare Business Review"}<i>→</i></button>{state === "error" ? <p className="workspace-inline-error">We couldn’t prepare this view right now. Please try again shortly.</p> : null}</section></InsightShell>; }
type ViewProps = { insights: ClientBusinessInsights; onRefresh: () => Promise<void>; running: boolean };
function InsightShell({ title, description, actions, children }: { title: string; description: string; actions?: ReactNode; children: ReactNode }) { return <div className="workspace-content"><section className="workspace-welcome compact"><div><p className="workspace-kicker">Ellis AI Studio</p><h2>{title}</h2><p>{description}</p></div>{actions}</section>{children}</div>; }
function InsightActions({ onRefresh, running }: { onRefresh: () => Promise<void>; running: boolean }) { return <div className="insight-actions"><button className="button button-dark" onClick={() => void onRefresh()} disabled={running}>{running ? "Updating…" : "Refresh Research"}<i>→</i></button></div>; }
function InsightList({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <article className="workspace-panel insight-list"><h3>{title}</h3>{items.length ? <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p>{empty}</p>}</article>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article><p>{label}</p><b>{value}</b><small>{detail}</small></article>; }
function InsightLoading() { return <section className="workspace-empty-state"><span>·</span><h3>Preparing your executive view.</h3><p>Gathering your latest client-ready business insights.</p></section>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
