import { useState, type FormEvent } from "react";

import { submitClientOnboarding } from "~/server/client-onboarding";

const goals = ["Generate more leads", "Increase booked appointments", "Improve Google rankings", "Recover missed leads", "Improve operations", "Increase reviews"];
const software = ["Google Workspace", "Gmail", "Google Calendar", "Google Drive", "Stripe", "QuickBooks", "Jobber", "Housecall Pro", "ServiceTitan", "Zapier", "Slack"];

export function ClientOnboardingPage() {
  const [form, setForm] = useState({ companyName: "", ownerName: "", email: "", phone: "", address: "", websiteUrl: "", googleBusinessProfileUrl: "", serviceAreas: "", servicesOffered: "", goals: [] as string[], currentSoftware: [] as string[] });
  const [state, setState] = useState<"idle" | "submitting" | "complete" | "error">("idle");
  const [error, setError] = useState("");
  const toggle = (field: "goals" | "currentSoftware", value: string) => setForm((current) => ({ ...current, [field]: current[field].includes(value) ? current[field].filter((item) => item !== value) : [...current[field], value] }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setState("submitting"); try { await submitClientOnboarding({ data: { ...form, serviceAreas: split(form.serviceAreas), servicesOffered: split(form.servicesOffered) } }); setState("complete"); } catch (reason) { setError(reason instanceof Error ? reason.message : "We couldn’t save your onboarding details. Please try again."); setState("error"); } };
  if (state === "complete") return <main className="conversion-shell wrap onboarding-stage"><p className="eyebrow">Ellis AI Studio</p><h1>Preparing your business intelligence.</h1><p className="onboarding-lede">Thank you. We have your business profile and are preparing the executive foundation for your project.</p><a className="button button-dark" href="/workspace">Return to Workspace <span className="arrow">→</span></a></main>;
  return <main className="conversion-shell wrap onboarding-stage"><header className="conversion-header"><a className="wordmark" href="/"><span>ELLIS</span><small>AI STUDIO</small></a><p className="onboarding-progress">Client onboarding · 01</p></header><section className="conversion-heading"><p className="eyebrow">Welcome</p><h1>Tell us about your business.</h1><p>We’ll use this information to prepare a focused executive foundation for your engagement. You can update it anytime.</p></section><form className="onboarding-form" onSubmit={submit}><section><p className="eyebrow">Business information</p><div className="onboarding-fields"><Field label="Company name" value={form.companyName} onChange={(companyName) => setForm((value) => ({ ...value, companyName }))} required /><Field label="Owner" value={form.ownerName} onChange={(ownerName) => setForm((value) => ({ ...value, ownerName }))} required /><Field label="Business email" type="email" value={form.email} onChange={(email) => setForm((value) => ({ ...value, email }))} required /><Field label="Phone" value={form.phone} onChange={(phone) => setForm((value) => ({ ...value, phone }))} /><Field label="Address" value={form.address} onChange={(address) => setForm((value) => ({ ...value, address }))} /><Field label="Website" type="url" placeholder="https://yourcompany.com" value={form.websiteUrl} onChange={(websiteUrl) => setForm((value) => ({ ...value, websiteUrl }))} /><Field label="Google Business Profile" type="url" placeholder="Optional" value={form.googleBusinessProfileUrl} onChange={(googleBusinessProfileUrl) => setForm((value) => ({ ...value, googleBusinessProfileUrl }))} /><Field label="Service areas" placeholder="City, county, or region" value={form.serviceAreas} onChange={(serviceAreas) => setForm((value) => ({ ...value, serviceAreas }))} /><Field label="Services offered" placeholder="Separate services with commas" value={form.servicesOffered} onChange={(servicesOffered) => setForm((value) => ({ ...value, servicesOffered }))} /></div></section><ChoiceGroup title="Business goals" values={goals} selected={form.goals} onToggle={(value) => toggle("goals", value)} /><ChoiceGroup title="Current software" values={software} selected={form.currentSoftware} onToggle={(value) => toggle("currentSoftware", value)} />{error ? <p className="form-error" role="alert">{error}</p> : null}<button className="button button-dark onboarding-submit" disabled={state === "submitting"}>{state === "submitting" ? "Saving your business profile…" : "Complete onboarding"}<span className="arrow">→</span></button></form></main>;
}

function Field({ label, value, onChange, type = "text", placeholder, required }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string; required?: boolean }) { return <label>{label}<input type={type} value={value} placeholder={placeholder} required={required} onChange={(event) => onChange(event.target.value)} /></label>; }
function ChoiceGroup({ title, values, selected, onToggle }: { title: string; values: string[]; selected: string[]; onToggle: (value: string) => void }) { return <section className="onboarding-choices"><p className="eyebrow">{title}</p><div>{values.map((value) => <button className={selected.includes(value) ? "is-selected" : ""} type="button" key={value} onClick={() => onToggle(value)}>{selected.includes(value) ? "✓ " : ""}{value}</button>)}</div></section>; }
function split(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
