import { useEffect, useState, type FormEvent, type ReactNode } from "react";

import proposal from "~/data/mock-client-conversion.json";
import { confirmCheckout, getWorkspaceAccess, startCheckout } from "~/server/client-payments";

type FlowStage = "proposal" | "agreement" | "payment" | "welcome" | "workspace";
const storageKey = "ellis-client-conversion-state";

type FlowState = { accepted?: boolean; agreed?: boolean; paid?: boolean; proposalId?: string };

function readState(): FlowState { if (typeof window === "undefined") return {}; try { return JSON.parse(window.sessionStorage.getItem(storageKey) ?? "{}"); } catch { return {}; } }
function updateState(next: FlowState) { window.sessionStorage.setItem(storageKey, JSON.stringify({ ...readState(), ...next })); }
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
function route(stage: FlowStage) { return stage === "proposal" ? `/proposal/${proposal.proposalId}` : stage === "agreement" ? `/agreement/${proposal.proposalId}` : stage === "payment" ? `/payment/${proposal.proposalId}` : stage === "welcome" ? "/welcome" : "/workspace"; }

export function ProposalFlowPage() { const cancelled = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("payment") === "cancelled"; return <FlowShell stage="proposal" eyebrow="Implementation proposal" title={proposal.projectName} intro={`Prepared for ${proposal.clientName} · ${proposal.businessName}`}>{cancelled ? <section className="conversion-summary conversion-notice"><p className="eyebrow">Payment cancelled</p><p>Your deposit was not processed. You can return to payment whenever you’re ready.</p><a className="button button-dark" href={route("payment")}>Try Again <span className="arrow">→</span></a></section> : null}<section className="conversion-summary"><p>{proposal.executiveSummary}</p></section><DetailGrid><Detail title="Problems identified"><List items={proposal.problems} /></Detail><Detail title="Recommended solution"><p>{proposal.solution}</p></Detail><Detail title="Deliverables"><List items={proposal.deliverables} /></Detail><Detail title="Timeline"><p>{proposal.timeline}</p></Detail></DetailGrid><section className="conversion-investment"><div><p className="eyebrow">Investment</p><h2>{money(proposal.projectTotal)}</h2><p>{proposal.paymentTerms}</p></div><div><p className="eyebrow">Next step</p><p>Accept this proposal to review the service agreement and reserve your implementation start.</p><a className="button button-dark" href={route("agreement")} onClick={() => updateState({ accepted: true })}>Accept Proposal <span className="arrow">→</span></a></div></section></FlowShell>; }

export function AgreementFlowPage() { const [name, setName] = useState(""); const [agreed, setAgreed] = useState(false); const submit = (event: FormEvent) => { event.preventDefault(); if (!name.trim() || !agreed) return; updateState({ accepted: true, agreed: true }); window.location.assign(route("payment")); }; return <FlowShell stage="agreement" eyebrow="Service agreement" title="Confirm your engagement" intro={`${proposal.projectName} · ${proposal.businessName}`}><section className="conversion-summary agreement-copy"><p><b>Scope.</b> Ellis AI Studio will provide the approved implementation services described in this engagement, including the deliverables listed in the proposal.</p><p><b>Payment terms.</b> {proposal.paymentTerms}</p><p><b>Timeline.</b> {proposal.timeline}. Delivery timing depends on timely client feedback and access approvals.</p></section><form className="conversion-form" onSubmit={submit}><label>Client name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Your full name" required /></label><label>Date<input value={new Intl.DateTimeFormat("en-US", { dateStyle: "long" }).format(new Date())} readOnly /></label><label className="conversion-check"><input type="checkbox" checked={agreed} onChange={(event) => setAgreed(event.target.checked)} /><span>I agree to the Service Agreement.</span></label><button className="button button-dark" disabled={!name.trim() || !agreed}>Continue to Payment <span className="arrow">→</span></button></form></FlowShell>; }

export function PaymentFlowPage() { const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const pay = async () => { setSubmitting(true); setError(""); try { const result = await startCheckout({ data: { proposalId: proposal.proposalId } }); if (result.alreadyPaid) { window.location.assign(route("welcome")); return; } if (!result.checkoutUrl) throw new Error("Stripe did not return a secure checkout URL."); window.location.assign(result.checkoutUrl); } catch (reason) { setError(reason instanceof Error ? reason.message : "We could not start secure payment. Please try again."); setSubmitting(false); } }; return <FlowShell stage="payment" eyebrow="Project deposit" title="Confirm your project start" intro="Your deposit reserves implementation time with Ellis AI Studio."><section className="conversion-payment-summary"><p><span>Project total</span><b>{money(proposal.projectTotal)}</b></p><p><span>Deposit due today</span><b>{money(proposal.deposit)}</b></p><p><span>Remaining balance</span><b>{money(proposal.remainingBalance)}</b></p></section><div className="conversion-form payment-form"><label>Cardholder name<input disabled placeholder="Secure payment is completed through Stripe Checkout" /></label><label>Card number<input disabled placeholder="•••• •••• •••• ••••" /></label><div><label>Expiry<input disabled placeholder="MM / YY" /></label><label>Security code<input disabled placeholder="CVC" /></label></div>{error ? <p className="conversion-error" role="alert">{error}</p> : null}<button className="button button-dark" onClick={pay} type="button" disabled={submitting}>{submitting ? "Opening secure checkout…" : `Pay Deposit · ${money(proposal.deposit)}`} <span className="arrow">→</span></button><small>You’ll be redirected to Stripe’s secure payment page. Ellis AI Studio never receives your card details.</small></div></FlowShell>; }

export function PaymentSuccessPage() { const [state, setState] = useState<"loading" | "error">("loading"); useEffect(() => { const sessionId = new URLSearchParams(window.location.search).get("session_id"); if (!sessionId) { window.location.assign(route("proposal")); return; } confirmCheckout({ data: { sessionId } }).then((result) => { sessionStorage.setItem(storageKey, JSON.stringify({ ...readState(), paid: result.paid, proposalId: result.proposalId })); window.location.assign(route("welcome")); }).catch(() => setState("error")); }, []); return <FlowShell stage="payment" eyebrow="Confirming payment" title={state === "loading" ? "Finalizing your project start" : "We couldn’t confirm payment"} intro={state === "loading" ? "Please keep this page open while we verify your deposit." : "Your payment may still be processing. Return to your proposal and try again if needed."}>{state === "error" ? <section className="conversion-summary"><a className="button button-dark" href={route("proposal")}>Return to Proposal <span className="arrow">→</span></a></section> : <section className="conversion-summary"><p className="conversion-loading">Confirming your Stripe payment securely…</p></section>}</FlowShell>; }

export function WelcomeFlowPage() { return <FlowShell stage="welcome" eyebrow="Project activated" title="Deposit Received" intro="Thank you for choosing Ellis AI Studio. Your project has officially started."><section className="conversion-summary"><p>We’ll coordinate your first project milestone and request only the business connections needed to move the work forward. Your workspace will keep the engagement simple and clear.</p><a className="button button-dark" href={route("workspace")}>Enter Workspace <span className="arrow">→</span></a></section></FlowShell>; }

export function ActivatedWorkspace() { const [access, setAccess] = useState<"loading" | "allowed" | "denied">("loading"); const [clientName, setClientName] = useState(proposal.clientName); useEffect(() => { getWorkspaceAccess({ data: { proposalId: readState().proposalId ?? proposal.proposalId } }).then((result) => { setClientName(result.clientName); setAccess(result.paid ? "allowed" : "denied"); }).catch(() => setAccess("denied")); }, []); if (access === "loading") return <FlowShell stage="workspace" eyebrow="Client workspace" title="Loading your workspace" intro="Verifying your project access."><section className="conversion-summary"><p className="conversion-loading">Preparing your project workspace…</p></section></FlowShell>; if (access === "denied") return <AccessRequired />; return <FlowShell stage="workspace" eyebrow="Client workspace" title={`Welcome, ${clientName}.`} intro="A calm view of the work currently in motion."><section className="conversion-workspace-grid"><Metric title="Project status" value="On track" detail="Growth Systems Implementation" /><Metric title="Current phase" value="Strategy" detail="Implementation plan in review" /><Metric title="Estimated completion" value="August 18" detail="Six-week engagement" /><Metric title="Next meeting" value="July 21 · 2:00 PM" detail="Google Meet" /></section><DetailGrid><Detail title="Action required"><p>Review the implementation direction before the next working session.</p><button className="workspace-text-button">Review project update</button></Detail><Detail title="Recent updates"><List items={["Strategy presentation prepared", "Project timeline confirmed", "First implementation milestone scheduled"]} /></Detail></DetailGrid></FlowShell>; }

function AccessRequired() { return <main className="contact-hero wrap" style={{ minHeight: "72vh", display: "grid", alignContent: "center" }}><p className="eyebrow">Client workspace</p><h1>Activation required.</h1><p className="lede">Your client workspace is activated after the project agreement and deposit are completed.</p><a className="button button-dark" href={route("proposal")}>View Proposal <span className="arrow">→</span></a></main>; }
function FlowShell({ stage, eyebrow, title, intro, children }: { stage: FlowStage; eyebrow: string; title: string; intro: string; children: ReactNode }) { const steps = ["Proposal", "Agreement", "Payment", "Welcome"]; const activeIndex = Math.min(steps.indexOf(stage === "workspace" ? "Welcome" : stage[0].toUpperCase() + stage.slice(1)), steps.length - 1); return <main className="conversion-shell wrap conversion-stage"><header className="conversion-header"><a className="wordmark" href="/"><span>ELLIS</span><small>AI STUDIO</small></a><div className="conversion-progress"><ol aria-label="Client activation progress">{steps.map((step, index) => <li className={index <= activeIndex ? "is-active" : ""} key={step}><span>{index < activeIndex ? "✓" : index + 1}</span>{step}</li>)}</ol><i aria-hidden="true"><em style={{ width: `${((activeIndex + 1) / steps.length) * 100}%` }} /></i></div></header><section className="conversion-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></section>{children}</main>; }
function DetailGrid({ children }: { children: ReactNode }) { return <section className="conversion-detail-grid">{children}</section>; }
function Detail({ title, children }: { title: string; children: ReactNode }) { return <article><div className="conversion-detail-label"><span>{title.slice(0, 1)}</span><p className="eyebrow">{title}</p></div>{children}</article>; }
function List({ items }: { items: readonly string[] }) { return <ul className="conversion-list">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function Metric({ title, value, detail }: { title: string; value: string; detail: string }) { return <article><p>{title}</p><b>{value}</b><small>{detail}</small></article>; }
