import { useMemo, useState } from "react";
import { m } from "framer-motion";

type Answer = "strong" | "mixed" | "friction";
const questions = ["How quickly do you respond to new leads?", "Do you follow up automatically?", "Is your scheduling process manual?", "Do you know where most leads come from?", "Do you lose leads after business hours?", "Can your team see every active opportunity in one place?"] as const;
const labels = [["Within 5 minutes", "Same day", "Usually later"], ["Yes, consistently", "Sometimes", "Not yet"], ["Mostly automated", "A mix", "Yes, fully manual"], ["Yes, clearly", "Partly", "Not reliably"], ["Rarely", "Occasionally", "Often"], ["Yes", "Mostly", "No"]] as const;
const values: Answer[] = ["strong", "mixed", "friction"];
const penalties: Record<Answer, number> = { strong: 0, mixed: 7, friction: 14 };

export function FrictionScorePreview() {
  const [answers, setAnswers] = useState<Record<number, Answer>>({});
  const answered = Object.keys(answers).length;
  const score = useMemo(() => Math.max(18, 92 - Object.values(answers).reduce((total, answer) => total + penalties[answer], 0)), [answers]);
  const status = score > 72 ? "Low friction" : score > 48 ? "Some friction" : "High friction";
  const circumference = 2 * Math.PI * 48;
  return <section className="score-preview"><div className="wrap"><div className="score-preview-heading"><div><p className="eyebrow">Business friction score</p><h2>See where friction may be slowing growth.</h2><p>Answer a few quick questions for a directional preview. This demonstration stays on your device and is never stored.</p></div><div className="score-progress" aria-label={`${answered} of ${questions.length} questions answered`}><strong>{answered}</strong><span>of {questions.length} answered</span></div></div><div className="score-preview-grid"><div className="score-questions">{questions.map((question, index) => <fieldset className="score-question" key={question}><legend><span>0{index + 1}</span>{question}</legend><div className="score-options">{labels[index].map((label, answerIndex) => { const answer = values[answerIndex]; const active = answers[index] === answer; return <button type="button" className={active ? "is-selected" : ""} aria-pressed={active} onClick={() => setAnswers((current) => ({ ...current, [index]: answer }))} key={label}>{label}</button>; })}</div></fieldset>)}</div><aside className="score-panel"><div className="score-ring"><svg viewBox="0 0 112 112" aria-hidden="true"><circle className="score-ring-track" cx="56" cy="56" r="48"/><m.circle className="score-ring-value" cx="56" cy="56" r="48" initial={false} animate={{ strokeDashoffset: circumference - (score / 100) * circumference }} transition={{ duration: .5, ease: [0.16, 1, 0.3, 1] }}/></svg><m.strong key={score} initial={{ opacity: .35, y: 4 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .3 }}>{score}</m.strong><span>/ 100</span></div><p className="score-status">{status}</p><p className="score-note">A higher score signals a smoother customer journey. Answer each question to make this preview more specific.</p><div className="score-legend"><span><i className="legend-good"/> Healthy</span><span><i className="legend-mid"/> Review</span><span><i className="legend-low"/> Friction</span></div></aside></div><div className="score-preview-cta"><div><p className="eyebrow">Want the full analysis?</p><h3>Find the constraints worth fixing first.</h3></div><a href="/contact" className="button button-dark">Get My Free Friction Audit <span className="arrow" aria-hidden="true">→</span></a></div></div></section>;
}
