import { BrandLogo } from "./brand-logo";
import type { ReactNode } from "react";
import "~/styles/brand.css";
import "~/styles/studio-sections.css";

export const bookingUrl = "https://calendar.app.google/YytWSVvdNyPhCBK58";
const services = [["Growth Systems", "Create a measurable path from attention to qualified conversations."], ["Lead Recovery System", "Respond, follow up, and convert more of the demand you already earn."], ["Website Systems", "Turn your website into a clearer, more trusted conversion experience."], ["AI Automation Systems", "Improve operational efficiency with useful, governed automation."], ["Content Engine", "Build a repeatable content system around buyer questions and business outcomes."], ["Business Intelligence", "Make growth decisions with evidence, opportunity analysis, and clear priorities."]];
const process = ["Discovery", "Business Intelligence", "Growth Strategy", "System Design", "Implementation", "Optimization", "Continuous Growth"];
function Nav() { return <header className="site-nav"><a className="brand-link" href="/"><BrandLogo variant="icon" className="brand-logo brand-logo-nav" /></a><nav aria-label="Primary navigation"><a href="/services">Services</a><a href="/process">Process</a><a href="/portfolio">Portfolio</a><a href="/about">About</a><a href="/contact">Contact</a></nav><a className="button nav-cta" href={bookingUrl} target="_blank" rel="noreferrer">Book a Growth Strategy Call</a></header>; }
function Footer() { return <footer className="site-footer"><div className="wrap"><div><span>© {new Date().getFullYear()} Ellis AI Studio</span></div><div><a href="/services">Services</a><a href="/process">Process</a><a href="/portfolio">Portfolio</a><a href="/contact">Contact</a></div></div></footer>; }
export function PublicPage({ children }: { children: ReactNode }) { return <div className="site-shell"><Nav /><main>{children}</main><Footer /></div>; }
export function GrowthHome() { return <PublicPage><section className="hero"><div className="hero-orbit" aria-hidden="true"/><div className="wrap hero-content"><p className="eyebrow">AI-powered growth systems for service businesses</p><h1>Build a growth system that earns more customers.</h1><p className="lede">Ellis designs and builds AI-powered systems that help service businesses acquire more customers, convert more leads, and operate more efficiently.</p><div className="actions"><a className="button" href={bookingUrl} target="_blank" rel="noreferrer">Book a Growth Strategy Call</a><a className="button button-secondary" href="/services">Explore Growth Opportunities</a></div></div></section><section className="section"><div className="wrap"><div className="section-heading"><p className="eyebrow">Business outcomes first</p><h2>Growth becomes easier to measure—and easier to repeat.</h2></div><div className="service-grid">{[["Acquire qualified demand", "Build clearer paths from attention to meaningful conversations."],["Convert more leads", "Create responsive, trusted journeys that make the next step easy."],["Operate efficiently", "Reduce manual follow-up and make proven systems repeatable."]].map(([t,d],i)=><article className="service-card" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section><section className="section section-tint"><div className="wrap"><div className="section-heading"><p className="eyebrow">How we work</p><h2>From business intelligence to continuous growth.</h2></div><div className="process-grid">{process.map((x,i)=><article className="process-step" key={x}><span>0{i+1}</span><h3>{x}</h3><p>Clear priorities, accountable progress, and a measurable next step.</p></article>)}</div></div></section><section className="portfolio-intro"><div className="wrap portfolio-intro-grid"><div><p className="eyebrow">Portfolio</p><h2>See how clearer systems can make a business easier to choose.</h2></div><a className="button" href="/portfolio">Explore Portfolio</a></div></section><section className="callout"><div className="wrap"><div><p className="eyebrow">Start with the right conversation</p><h2>Let’s identify the next growth opportunity for your business.</h2></div><a className="button button-light" href={bookingUrl} target="_blank" rel="noreferrer">Book a Growth Strategy Call</a></div></section></PublicPage>; }
export function StandardPage({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: ReactNode }) { return <PublicPage><section className="hero"><div className="wrap hero-content"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{intro}</p></div></section><section className="section"><div className="wrap">{children}</div></section><section className="callout"><div className="wrap"><div><p className="eyebrow">Next step</p><h2>Discuss your business goals with Ellis AI Studio.</h2></div><a className="button button-light" href={bookingUrl} target="_blank" rel="noreferrer">Book a Growth Strategy Call</a></div></section></PublicPage>; }
export { services, process };
