import { useState, type FormEvent } from "react";

const services = [["Website Development", "Professional websites designed to generate more calls, leads, and bookings."], ["Business Automation", "Automate repetitive tasks so you can spend more time running your business."], ["AI Receptionist", "Answer calls and customer questions even when you’re unavailable."], ["CRM Setup", "Organize customers, jobs, and estimates in one place."], ["Online Booking", "Allow customers to request quotes and schedule appointments online."], ["Custom Solutions", "Need something unique? We’ll build a solution that fits your business."]];
const industries = ["Roofing", "HVAC", "Plumbing", "Electrical", "Cleaning", "Landscaping", "Contractors", "Auto Repair", "Dentists", "Med Spas", "Gyms"];
const steps = [["Discovery", "We learn about your business and understand what you’re trying to improve."], ["Plan", "We recommend the right solution for your business."], ["Build", "We design, develop, test, and launch everything."], ["Support", "Need updates later? We’re here when you need us."]];

export function MarketingPage() { return <div className="site-shell">
  <header className="site-nav"><a className="wordmark" href="#home">ELLIS <span>AI STUDIO</span></a><nav aria-label="Primary navigation"><a href="#home">Home</a><a href="#services">Services</a><a href="#industries">Industries</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="button nav-cta" href="#contact">Book a Free Consultation</a></header>
  <main>
    <section className="hero" id="home"><div className="hero-orbit" aria-hidden="true"/><div className="wrap hero-content"><p className="eyebrow">Websites, automation &amp; AI tools</p><h1>Technology Built for Service Businesses</h1><p className="lede">We help service businesses build better websites, automate repetitive work, improve customer communication, and simplify everyday operations.</p><div className="actions"><a className="button" href="#contact">Book a Free Consultation <span aria-hidden="true">→</span></a><a className="button button-secondary" href="#services">View Services</a></div></div></section>
    <section className="section" id="services"><div className="wrap"><div className="section-heading"><p className="eyebrow">What we build</p><h2>Practical technology for the way your business works.</h2></div><div className="service-grid">{services.map(([title, description], index) => <article className="service-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="section section-tint" id="industries"><div className="wrap"><div className="section-heading"><p className="eyebrow">Industries</p><h2>Who We Help</h2><p>We build tools that fit the day-to-day realities of service businesses.</p></div><div className="industry-grid">{industries.map((industry) => <article key={industry}>{industry}</article>)}<article className="industry-more">…and many other service businesses.</article></div></div></section>
    <section className="section" id="how-it-works"><div className="wrap"><div className="section-heading"><p className="eyebrow">How it works</p><h2>A clear process from first conversation to long-term support.</h2></div><div className="process-grid">{steps.map(([title, description], index) => <article className="process-step" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="section section-tint" id="about"><div className="wrap about"><p className="eyebrow">About Ellis AI Studio</p><h2>Technology should make running your business easier.</h2><p>Ellis AI Studio builds practical technology for service businesses. Whether you need a website, automation, AI assistant, CRM, or custom workflow, we build solutions designed around the way your business operates.</p></div></section>
    <section className="fit-note"><div className="wrap"><p className="eyebrow">Custom-fit solutions</p><h2>Every business is different.</h2><p>We’ll recommend the right solution after learning about your goals.</p></div></section>
    <section className="callout"><div className="wrap"><div><p className="eyebrow">Ready to get started?</p><h2>Let’s build something that makes your business easier to run.</h2></div><a className="button button-light" href="#contact">Book a Free Consultation <span aria-hidden="true">→</span></a></div></section>
    <section className="section" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">Contact</p><h2>Schedule a Free Consultation</h2><p className="lede">Tell us what you would like to improve. We’ll be in touch to talk through the right next step.</p></div><InquiryForm /></div></section>
  </main>
  <footer className="site-footer"><div className="wrap"><span>© {new Date().getFullYear()} Ellis AI Studio</span><div><a href="#services">Services</a><a href="#industries">Industries</a><a href="#about">About</a><a href="#contact">Contact</a></div></div></footer>
</div>; }

function InquiryForm() { const [message, setMessage] = useState(""); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const subject = encodeURIComponent(`Free Consultation — ${form.get("business")}`); const body = encodeURIComponent(`Name: ${form.get("name")}\nBusiness: ${form.get("business")}\nEmail: ${form.get("email")}\nPhone: ${form.get("phone")}\nWebsite: ${form.get("website") || "Not provided"}\n\nWhat they need help with:\n${form.get("message")}`); setMessage("Opening your email app to send your consultation request."); window.location.href = `mailto:hello@ellisaistudio.com?subject=${subject}&body=${body}`; } return <form className="inquiry" onSubmit={submit}><label>Name<input name="name" required autoComplete="name" /></label><label>Business Name<input name="business" required autoComplete="organization" /></label><label>Email<input name="email" required type="email" autoComplete="email" /></label><label>Phone<input name="phone" required type="tel" autoComplete="tel" /></label><label className="full">Website <small>Optional</small><input name="website" type="url" placeholder="https://" autoComplete="url" /></label><label className="full">What would you like help with?<textarea name="message" required rows={5} /></label><button className="button" type="submit">Schedule Consultation <span aria-hidden="true">→</span></button><p className="form-note" role="status">{message}</p></form>; }
