import { BrandLogo } from "./brand-logo";
import "~/styles/brand.css";

const bookingUrl = "https://calendar.app.google/YytWSVvdNyPhCBK58";

const services = [["Website Development", "Professional websites designed to generate more calls, leads, and bookings."], ["Business Automation", "Automate repetitive tasks so you can spend more time running your business."], ["AI Receptionist", "Answer calls and customer questions even when you’re unavailable."], ["CRM Setup", "Organize customers, jobs, and estimates in one place."], ["Online Booking", "Allow customers to request quotes and schedule appointments online."], ["Custom Solutions", "Need something unique? We’ll build a solution that fits your business."]];
const industries = ["Roofing", "HVAC", "Plumbing", "Electrical", "Cleaning", "Landscaping", "Contractors", "Auto Repair", "Dentists", "Med Spas", "Gyms"];
const steps = [["Discovery", "We learn about your business and understand what you’re trying to improve."], ["Plan", "We recommend the right solution for your business."], ["Build", "We design, develop, test, and launch everything."], ["Support", "Need updates later? We’re here when you need us."]];

export function MarketingPage() {
  return <div className="site-shell">
    <header className="site-nav"><a className="brand-link" href="#home"><BrandLogo variant="icon" className="brand-logo brand-logo-nav" /></a><nav aria-label="Primary navigation"><a href="#home">Home</a><a href="#services">Services</a><a href="#industries">Industries</a><a href="#about">About</a><a href={bookingUrl} target="_blank" rel="noreferrer">Contact</a></nav><a className="button nav-cta" href={bookingUrl} target="_blank" rel="noreferrer">Book a Free Consultation</a></header>
    <main>
      <section className="hero" id="home"><div className="hero-orbit" aria-hidden="true"/><div className="wrap hero-content"><p className="eyebrow">Websites, automation &amp; AI tools</p><h1>Technology Built for Service Businesses</h1><p className="lede">We help service businesses build better websites, automate repetitive work, improve customer communication, and simplify everyday operations.</p><div className="actions"><a className="button" href={bookingUrl} target="_blank" rel="noreferrer">Book a Free Consultation <span aria-hidden="true">→</span></a><a className="button button-secondary" href="#services">View Services</a></div></div></section>
      <section className="section" id="services"><div className="wrap"><div className="section-heading"><p className="eyebrow">What we build</p><h2>Practical technology for the way your business works.</h2></div><div className="service-grid">{services.map(([title, description], index) => <article className="service-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
      <section className="section section-tint" id="industries"><div className="wrap"><div className="section-heading"><p className="eyebrow">Industries</p><h2>Who We Help</h2><p>We build tools that fit the day-to-day realities of service businesses.</p></div><div className="industry-grid">{industries.map((industry) => <article key={industry}>{industry}</article>)}<article className="industry-more">…and many other service businesses.</article></div></div></section>
      <section className="section" id="how-it-works"><div className="wrap"><div className="section-heading"><p className="eyebrow">How it works</p><h2>A clear process from first conversation to long-term support.</h2></div><div className="process-grid">{steps.map(([title, description], index) => <article className="process-step" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
      <section className="section section-tint" id="about"><div className="wrap about"><p className="eyebrow">About Ellis AI Studio</p><h2>Technology should make running your business easier.</h2><p>Ellis AI Studio builds practical technology for service businesses. Whether you need a website, automation, AI assistant, CRM, or custom workflow, we build solutions designed around the way your business operates.</p></div></section>
      <section className="fit-note"><div className="wrap"><p className="eyebrow">Custom-fit solutions</p><h2>Every business is different.</h2><p>We’ll recommend the right solution after learning about your goals.</p></div></section>
      <section className="callout"><div className="wrap"><div><p className="eyebrow">Ready to get started?</p><h2>Let’s build something that makes your business easier to run.</h2></div><a className="button button-light" href={bookingUrl} target="_blank" rel="noreferrer">Book a Free Consultation <span aria-hidden="true">→</span></a></div></section>
      <section className="section" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">Contact</p><h2>Schedule a Free Consultation</h2><p className="lede">Tell us what you would like to improve. We’ll be in touch to talk through the right next step.</p></div><InquiryForm /></div></section>
    </main>
    <footer className="site-footer"><div className="wrap"><div className="footer-brand"><a href="#home"><BrandLogo className="brand-logo brand-logo-footer" /></a><span>© {new Date().getFullYear()} Ellis AI Studio</span></div><div><a href="#services">Services</a><a href="#industries">Industries</a><a href="#about">About</a><a href={bookingUrl} target="_blank" rel="noreferrer">Contact</a></div></div></footer>
  </div>;
}

function InquiryForm() {
  return <div className="inquiry"><p>Choose a time that works for you, and we’ll come prepared to discuss your business goals.</p><a className="button" href={bookingUrl} target="_blank" rel="noreferrer">Schedule Your Free Consultation <span aria-hidden="true">→</span></a></div>;
}
