import { useEffect, useMemo, useState, type FormEvent } from "react";
import { BrandLogo } from "./brand-logo";
import northStarHero from "~/assets/northstar/northstar-hero.png";
import { consultationUrl, industries, isInteractiveDemo, portfolioProjects, type PortfolioProject } from "~/data/portfolio";
import "~/styles/portfolio.css";
import "~/styles/portfolio-media.css";
import "~/styles/portfolio-coming-soon.css";
import "~/styles/northstar-air.css";
import "~/styles/northstar-motion.css";
import "~/styles/northstar-hero-polish.css";

export function PortfolioPage() {
  const [search, setSearch] = useState("");
  const [industry, setIndustry] = useState("All");
  const [activeDemo, setActiveDemo] = useState<string | null>(null);

  useEffect(() => setActiveDemo(new URLSearchParams(window.location.search).get("demo")), []);

  const selectedProject = portfolioProjects.find((project) => project.slug === activeDemo);
  const projects = useMemo(() => portfolioProjects.filter((project) => (industry === "All" || project.industry === industry) && `${project.company} ${project.industry} ${project.style}`.toLowerCase().includes(search.toLowerCase())), [industry, search]);

  if (selectedProject) return isInteractiveDemo(selectedProject.slug) ? <DemoWebsite project={selectedProject} /> : <ComingSoonDemo project={selectedProject} />;

  return <main className="portfolio-shell">
    <header className="portfolio-nav"><a href="/" className="portfolio-brand"><BrandLogo variant="icon" className="portfolio-brand-icon" /><span>ELLIS AI STUDIO</span></a><a href="/" className="portfolio-return">← Back to studio</a></header>
    <section className="portfolio-hero"><div className="portfolio-wrap"><p className="portfolio-kicker">Selected work</p><h1>Crafted to make service businesses impossible to overlook.</h1><p>Explore interactive, fictional demo websites built to show the range of quality, originality, and practical thinking Ellis AI Studio can bring to your business.</p></div></section>
    <section className="portfolio-controls" aria-label="Portfolio filters"><div className="portfolio-wrap"><div className="portfolio-controls-top"><div><p className="portfolio-kicker">Browse by industry</p><h2>Featured projects</h2></div><label className="portfolio-search"><span className="sr-only">Search projects</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search industry or style" /></label></div><div className="portfolio-filters" aria-label="Industry filters">{industries.map((item) => <button key={item} className={item === industry ? "is-active" : ""} onClick={() => setIndustry(item)}>{item}</button>)}</div></div></section>
    <section className="portfolio-grid-section"><div className="portfolio-wrap"><div className="portfolio-grid">{projects.map((project) => <ProjectCard key={project.slug} project={project} />)}</div>{projects.length === 0 && <div className="portfolio-empty"><p>No demos in this category yet.</p><button onClick={() => { setIndustry("All"); setSearch(""); }}>View all projects</button></div>}</div></section>
    <section className="portfolio-closing"><div className="portfolio-wrap"><p className="portfolio-kicker">Your business, considered</p><h2>Good design should make the next customer action feel obvious.</h2><a href={consultationUrl} target="_blank" rel="noreferrer">Book Your Free Consultation <span>→</span></a></div></section>
  </main>;
}

function ProjectCard({ project }: { project: PortfolioProject }) {
  const isLive = isInteractiveDemo(project.slug);
  return <article className={`project-card project-card-${project.slug}`} style={{ "--project-accent": project.accent, "--project-soft": project.accentSoft } as React.CSSProperties}>
    <div className="project-preview"><img src={project.photo} alt={`Fictional ${project.industry.toLowerCase()} project for ${project.company}`} loading="lazy" /><div className="preview-browser"><span /><span /><span /></div><div className="preview-identity">{project.company}</div><div className="preview-scene"><i /><i /><i /></div><p>{project.tagline}</p></div>
    <div className="project-card-body"><div className="project-card-meta"><span>{project.industry}</span><span>{project.style}</span></div><h3>{project.company}</h3><p>{project.slug === "northstar-air" ? "Deployment Test — a calm, conversion-focused HVAC experience designed around urgent service, seasonal plans, and clear scheduling." : project.description}</p><div className="project-feature-list">{project.features.map((feature) => <span key={feature}>{feature}</span>)}</div><div className="project-card-bottom"><small>Estimated build time <strong>{project.buildTime}</strong></small><a href={`/portfolio?demo=${project.slug}`} aria-label={`${isLive ? "View interactive demo" : "View coming soon"} for ${project.company}`}>{isLive ? <>View Interactive Demo <span>→</span></> : <>Coming Soon <span>→</span></>}</a></div></div>
  </article>;
}

function ComingSoonDemo({ project }: { project: PortfolioProject }) {
  return <main className="coming-soon-site" style={{ "--coming-accent": project.accent, "--coming-soft": project.accentSoft } as React.CSSProperties}>
    <div className="coming-soon-notice">Concept website created by Ellis AI Studio for demonstration purposes only.</div>
    <nav className="coming-soon-nav"><a href="/portfolio">Back to portfolio</a><span>ELLIS AI STUDIO / CONCEPT LIBRARY</span></nav>
    <section className="coming-soon-hero"><p>{project.industry} concept</p><h1>Interactive Demo<br /><em>Coming Soon</em></h1><p className="coming-soon-copy">We are developing a distinctive {project.industry.toLowerCase()} experience for <strong>{project.company}</strong> - a fictional concept that will demonstrate a custom visual system, conversion strategy, and responsive interactions.</p><div><a href={consultationUrl} target="_blank" rel="noreferrer">Book a Consultation <span>→</span></a><a href="/portfolio">Explore more concepts</a></div></section>
    <section className="coming-soon-detail"><div><span>01</span><h2>Designed for the work that matters.</h2></div><p>Each Ellis AI Studio concept is intentionally built around its industry, customer decisions, and brand personality - never a recycled template or a real client claim.</p><dl><div><dt>{project.style}</dt><dd>creative direction</dd></div><div><dt>{project.buildTime}</dt><dd>typical timeline</dd></div><div><dt>{project.features.length}</dt><dd>core journeys</dd></div></dl></section>
    <footer className="coming-soon-footer"><span>{project.company} is a fictional demonstration.</span><a href="https://ellisaistudio.com">Return to Ellis AI Studio</a></footer>
  </main>;
}

function DemoWebsite({ project }: { project: PortfolioProject }) {
  const [notice, setNotice] = useState("");
  const submitDemo = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setNotice("Thanks — this demo request was received. A real website can route this directly to your team."); };
  const style = { "--demo-accent": project.accent, "--demo-soft": project.accentSoft } as React.CSSProperties;
  const isEditorial = project.slug === "ridgeway-roofing";
  const isLume = project.slug === "lume-aesthetics";
  const isField = project.slug === "field-and-form";
  const isNorthStar = project.slug === "northstar-air";
  const heroTitle = isNorthStar ? "Comfort You Can Count On." : project.tagline;
  const templateIndex = portfolioProjects.findIndex((item) => item.slug === project.slug);
  const navLinks = demoNavigation(project.slug);

  return <main className={`demo-site demo-${project.slug} demo-template-${templateIndex + 1}`} style={style}>
    <div className="demo-notice">Demo Website created by Ellis AI Studio for demonstration purposes.</div>
    <nav className="demo-nav"><a href="/portfolio" className="demo-back">← Portfolio</a><a href="#home" className="demo-wordmark">{project.company}</a><div className="demo-links">{navLinks.map(([label, href]) => <a href={href} key={label}>{label}</a>)}</div><a className="demo-book" href="#quote">{project.industry === "Restaurants" ? "Reserve" : project.industry === "Fitness" ? "Start trial" : project.industry === "Dentists" ? "Book visit" : "Get a quote"}</a></nav>
    <section className={`demo-hero ${isEditorial ? "demo-hero-editorial" : ""} ${isLume ? "demo-hero-lume" : ""} ${isField ? "demo-hero-field" : ""}`} id="home"><div className="demo-hero-art" aria-hidden="true"><img src={isNorthStar ? northStarHero : project.photo} alt="" /><i /><i /><i /></div><div className="demo-hero-copy"><p>{project.location}</p><h1>{heroTitle}</h1>{isNorthStar && <><p className="northstar-hero-subtitle">Premium heating, cooling, maintenance, and emergency service designed around comfort and reliability.</p><div className="northstar-hero-trust" aria-label="NorthStar service credentials"><span>24/7 emergency care</span><span>Licensed &amp; insured</span><span>4.9★ homeowner rating</span></div></>}<div className="demo-hero-actions"><a href="#quote">{isNorthStar ? "Schedule Service" : "Request a quote"}</a><a href={isNorthStar ? "#plans" : "#services"}>{isNorthStar ? "Free Estimate" : "Explore services"}</a></div></div><dl>{project.stats.map(([value, label]) => <div key={label}><dt>{value}</dt><dd>{label}</dd></div>)}</dl></section>
    {isNorthStar ? <NorthStarBody /> : isEditorial ? <EditorialBody project={project} /> : isLume ? <LumeBody project={project} /> : isField ? <FieldBody project={project} /> : <IndustryBody project={project} />}
    <section className="demo-faq" id="faq"><div><p className="demo-label">FAQ</p><h2>Questions, answered clearly.</h2></div><div className="demo-faq-list"><details open><summary>What happens after I reach out?</summary><p>We follow up with a clear next step, a helpful conversation, and no pressure.</p></details><details><summary>Do you offer flexible scheduling?</summary><p>Yes. This demo shows how a business can make availability and booking easy to understand.</p></details><details><summary>Can I get a tailored recommendation?</summary><p>Absolutely. Every service business has its own priorities, and the right experience should reflect them.</p></details></div></section>
    <section className="demo-contact" id="contact"><div className="demo-contact-copy"><p className="demo-label">Contact</p><h2>Let’s make the next step easy.</h2><p>Tell us a little about what you need. This fully working demo form confirms a submission without sending any data.</p><a className="demo-map" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(project.location)}`} target="_blank" rel="noreferrer"><span>Google Maps</span><strong>{project.location}</strong><i /></a></div><form className="demo-quote-form" id="quote" onSubmit={submitDemo}><label>Name<input required name="name" autoComplete="name" /></label><label>Email<input required name="email" type="email" autoComplete="email" /></label><label>What can we help with?<select name="service" defaultValue=""><option value="" disabled>Select a service</option><option>New project</option><option>Maintenance</option><option>Consultation</option></select></label><button type="submit">Send demo request <span>→</span></button><p role="status">{notice}</p></form></section>
    <section className="demo-final-cta"><p>Like this style?</p><h2>We’ll customize this foundation to fit your business, branding, services, and goals.</h2><div><a href={consultationUrl} target="_blank" rel="noreferrer">Book a Free Consultation <span>→</span></a><a className="demo-proposal" href="#quote">Request a Proposal <span>→</span></a></div></section>
    <footer className="demo-footer"><span>{project.company}</span><span>Demo Website created by Ellis AI Studio for demonstration purposes.</span></footer>
  </main>;
}

function demoNavigation(slug: string): [string, string][] {
  const navigation: Record<string, [string, string][]> = {
    "northstar-air": [["Comfort desk", "#services"], ["Membership", "#about"], ["Service areas", "#gallery"], ["Help", "#faq"], ["Contact", "#contact"]],
    "ridgeway-roofing": [["Our standard", "#about"], ["Projects", "#gallery"], ["Roofing", "#services"], ["Reviews", "#reviews"], ["Inspection", "#contact"]],
    "lume-aesthetics": [["The ritual", "#services"], ["Our practice", "#about"], ["Journal", "#gallery"], ["Guests", "#reviews"], ["Visit", "#contact"]],
    "field-and-form": [["Spaces", "#gallery"], ["The studio", "#about"], ["Seasonal care", "#services"], ["Stories", "#reviews"], ["Inquire", "#contact"]],
    "copperline-plumbing": [["Emergency", "#services"], ["Repair routes", "#services"], ["Our promise", "#gallery"], ["Answers", "#faq"], ["Dispatch", "#contact"]],
    "current-electric": [["System check", "#services"], ["Capabilities", "#services"], ["Safety", "#gallery"], ["FAQ", "#faq"], ["Projects", "#contact"]],
    "brightwell-clean": [["Plans", "#services"], ["Standards", "#about"], ["Spaces", "#gallery"], ["Feedback", "#reviews"], ["Estimate", "#contact"]],
    "morrow-paint": [["Color", "#services"], ["Process", "#services"], ["Rooms", "#gallery"], ["Stories", "#reviews"], ["Consult", "#contact"]],
    "stone-and-beam": [["Method", "#about"], ["Work", "#gallery"], ["Build types", "#services"], ["Client stories", "#reviews"], ["Plan", "#contact"]],
    "apex-garage": [["Visualizer", "#services"], ["Repairs", "#about"], ["Door styles", "#gallery"], ["Safety", "#faq"], ["Schedule", "#contact"]],
    "canopy-tree": [["Assessment", "#services"], ["Stewardship", "#about"], ["Canopy work", "#gallery"], ["FAQ", "#faq"], ["Request visit", "#contact"]],
    "ivory-dental": [["First visit", "#services"], ["Care", "#services"], ["Our space", "#gallery"], ["Patients", "#reviews"], ["Book", "#contact"]],
    "harbor-law": [["Confidential intake", "#services"], ["Practice areas", "#services"], ["Perspective", "#gallery"], ["FAQ", "#faq"], ["Consult", "#contact"]],
    "ledgerline": [["Advisory", "#about"], ["Services", "#services"], ["Insights", "#gallery"], ["Client notes", "#reviews"], ["Talk", "#contact"]],
    "arc-fitness": [["Schedule", "#services"], ["Training", "#about"], ["The club", "#gallery"], ["Member notes", "#reviews"], ["Try Arc", "#contact"]],
    "redline-auto": [["Inspection", "#services"], ["Service bays", "#services"], ["The shop", "#gallery"], ["Drivers", "#reviews"], ["Book", "#contact"]],
    "sable-table": [["Reserve", "#services"], ["Tonight", "#about"], ["The room", "#gallery"], ["Guests", "#reviews"], ["Private dining", "#contact"]],
    "provenance-realty": [["Search", "#services"], ["Featured homes", "#gallery"], ["Guidance", "#about"], ["Stories", "#reviews"], ["Private showing", "#contact"]],
  };
  return navigation[slug] ?? [["About", "#about"], ["Services", "#services"], ["Gallery", "#gallery"], ["Contact", "#contact"]];
}

function NorthStarBody() { const [position, setPosition] = useState(52); return <><section className="northstar-trust" aria-label="NorthStar Air service benefits">{["24/7 Emergency", "Licensed & Insured", "4.9 Customer Rating", "Financing Available"].map((item) => <span key={item}>{item}</span>)}</section><section className="northstar-services" id="services"><div><p className="demo-label">Home comfort, considered</p><h2>Every system. One calm call.</h2></div><div>{["Heating", "Cooling", "Heat pumps", "Indoor air quality", "Maintenance"].map((service, index) => <a href="#quote" key={service}><small>0{index + 1}</small><strong>{service}</strong><span>Explore</span></a>)}</div></section><section className="northstar-proof"><div><p className="demo-label">Why homeowners choose NorthStar</p><h2>Reliable comfort is a system, not a promise.</h2></div><dl>{[["18", "years local"], ["2,400+", "systems installed"], ["24/7", "emergency response"], ["98%", "customer satisfaction"]].map(([value, label]) => <div key={label}><dt>{value}</dt><dd>{label}</dd></div>)}</dl></section><section className="northstar-compare"><div><p className="demo-label">Before & after</p><h2>From inconsistent to effortless.</h2><p>A simple comparison interaction demonstrates how clear visual proof can make a service story more persuasive.</p></div><div className="northstar-slider" style={{"--compare-position": `${position}%`} as React.CSSProperties}><div className="northstar-before"><span>Before</span></div><div className="northstar-after"><span>After</span></div><input aria-label="Compare before and after home comfort" type="range" min="0" max="100" value={position} onChange={(event) => setPosition(Number(event.target.value))} /></div></section><section className="northstar-plans" id="plans"><div><p className="demo-label">Seasonal maintenance</p><h2>A plan for every kind of home.</h2></div><div className="northstar-plan-grid">{[["Essential", "$15/mo", "Two seasonal tune-ups"], ["Complete", "$24/mo", "Priority scheduling + repairs"], ["Signature", "$39/mo", "Whole-home comfort coverage"]].map(([name, price, detail]) => <article key={name}><p>{name}</p><strong>{price}</strong><span>{detail}</span><a href="#quote">Choose plan</a></article>)}</div></section><section className="northstar-area"><p className="demo-label">Service area</p><div><h2>Care, wherever home is.</h2><p>Austin · West Lake Hills · Lakeway · Cedar Park · Round Rock · Dripping Springs</p></div><a href="#quote">Check my address</a></section><section className="northstar-reviews" id="reviews"><p className="demo-label">Fictional customer reviews</p><div><blockquote>“The whole experience felt precise, considerate, and unexpectedly easy.”</blockquote><blockquote>“Clear options, a kind technician, and a home that finally feels right.”</blockquote><blockquote>“The kind of service you remember for the right reasons.”</blockquote></div></section></>; }

function MinimalBody({ project }: { project: PortfolioProject }) { return <><section className="demo-about demo-split" id="about"><div><p className="demo-label">About {project.company}</p><h2>{project.tagline}</h2></div><p>{project.company} is a fictional {project.industry.toLowerCase()} business built around responsive service, expert guidance, and a better customer experience. This demo shows how industry-specific messaging can make the right next step feel clear.</p></section><section className="demo-services demo-card-rail" id="services">{project.features.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>A service experience shaped specifically for the way this {project.industry.toLowerCase()} team works.</p></article>)}</section><Gallery project={project} /><Review project={project} /></>; }
function IndustryBody({ project }: { project: PortfolioProject }) {
  const features = project.features;
  const block = (title: string, copy: string, variant: string) => <section className={`industry-module ${variant}`}><p className="demo-label">{title}</p><h2>{copy}</h2></section>;
  const cards = (title: string, variant: string) => <section className={`industry-cards ${variant}`} id="services"><p className="demo-label">{title}</p><div>{features.map((feature, index) => <article key={feature}><span>0{index + 1}</span><h3>{feature}</h3><p>Designed around the real decisions customers make before they reach out.</p><a href="#quote">Explore <span>→</span></a></article>)}</div></section>;
  switch (project.slug) {
    case "northstar-air": return <><section className="service-command" id="services"><div><p>24/7 home comfort desk</p><h2>What needs attention today?</h2><div className="command-actions"><a href="#quote">My AC or heat</a><a href="#quote">Improve air quality</a><a href="#quote">Plan a replacement</a></div></div><aside><strong>60 min</strong><span>target arrival window</span></aside></section>{block("Membership", "A comfort plan that keeps the season from becoming an emergency.", "membership-band")}<Gallery project={project} /><Review project={project} /></>;
    case "copperline-plumbing": return <><section className="emergency-rail" id="services"><p>Water where it should not be?</p><a href="#quote">Start emergency request <span>→</span></a><small>Licensed plumbers · calm, clear next steps</small></section>{cards("Choose your route", "plumbing-routes")}<section className="service-proof"><span>01</span><p>Upfront options before work begins. No mystery. No pressure.</p></section><Gallery project={project} /></>;
    case "current-electric": return <><section className="electric-dashboard" id="services"><div><span>LIVE SYSTEM CHECK</span><h2>Make the next upgrade the right one.</h2><a href="#quote">Start your project</a></div><ul><li>Panel capacity</li><li>Smart home readiness</li><li>Safety priorities</li></ul></section>{block("Precision work", "Every circuit deserves a clear plan.", "electric-statement")}{cards("Capabilities", "electric-cards")}<Review project={project} /></>;
    case "brightwell-clean": return <><section className="clean-plan" id="services"><div><p className="demo-label">Build a cleaning rhythm</p><h2>One visit or a beautifully reliable routine.</h2></div><div><button>Weekly</button><button>Every two weeks</button><button>Move-in reset</button><a href="#quote">See my estimate</a></div></section><Gallery project={project} />{block("The Brightwell standard", "Thoughtful details, room by room.", "clean-standard")}<Review project={project} /></>;
    case "morrow-paint": return <><section className="paint-swatch" id="services"><p>Color changes everything.</p><h2>Find the feeling your room has been missing.</h2><div>{["Clarity", "Warmth", "Depth", "Light"].map((tone) => <span key={tone}>{tone}</span>)}</div></section>{cards("From idea to finish", "paint-cards")}<Gallery project={project} /><section className="paint-quote"><p>Have a room in mind?</p><a href="#quote">Book a color consultation</a></section></>;
    case "stone-and-beam": return <><section className="build-timeline" id="about"><p className="demo-label">The project method</p><ol><li><span>01</span>Listen to the house</li><li><span>02</span>Plan every trade</li><li><span>03</span>Build with intention</li></ol></section><Gallery project={project} />{cards("What we build", "build-cards")}<Review project={project} /></>;
    case "apex-garage": return <><section className="garage-config" id="services"><div><p>DESIGN YOUR ENTRY</p><h2>A door that works hard and looks even better.</h2></div><div><span>01 / STYLE</span><span>02 / MATERIAL</span><span>03 / SMART ACCESS</span><a href="#quote">Start visualizer</a></div></section>{block("Fast when it matters", "Repair requests move from click to dispatch.", "garage-service")}<Gallery project={project} /></>;
    case "canopy-tree": return <><section className="tree-risk" id="services"><div><p className="demo-label">Canopy assessment</p><h2>Know what your trees are telling you.</h2><a href="#quote">Request an arborist visit</a></div><ul><li>Storm damage</li><li>Health &amp; pruning</li><li>Removal planning</li></ul></section><Gallery project={project} />{block("Stewardship", "Big equipment. Deep respect for the landscape.", "tree-statement")}<Review project={project} /></>;
    case "ivory-dental": return <><section className="patient-path" id="services"><p className="demo-label">New patient experience</p><h2>Care can feel easy from the very first click.</h2><div><span>1. Choose a time</span><span>2. Complete forms</span><span>3. Meet your team</span></div><a href="#quote">Book first visit</a></section>{cards("Care made clear", "dental-cards")}<Gallery project={project} /></>;
    case "harbor-law": return <><section className="law-intake" id="services"><span>HARBOR LAW / CONFIDENTIAL INTAKE</span><h2>A direct conversation is the right first step.</h2><a href="#quote">Request a consultation</a></section><section className="law-practices"><p>Practice areas</p>{features.map((feature) => <a href="#quote" key={feature}>{feature} <span>↗</span></a>)}</section><Gallery project={project} /><Review project={project} /></>;
    case "ledgerline": return <><section className="ledger-grid" id="services"><div><span>Forecast</span><strong>Clearer</strong></div><div><span>Tax season</span><strong>Ready</strong></div><div><span>Next decision</span><strong>In view</strong></div></section>{block("Your numbers, working harder", "Advisory built for the choices ahead.", "ledger-statement")}{cards("Ways to work together", "ledger-cards")}<Review project={project} /></>;
    case "arc-fitness": return <><section className="fitness-schedule" id="services"><p>THIS WEEK AT ARC</p><h2>Pick your next hour.</h2><div>{["06:00 / Strength", "12:15 / Sweat", "18:30 / Restore"].map((slot) => <a href="#quote" key={slot}>{slot}<span>Reserve</span></a>)}</div></section>{block("Coached, not crowded", "The energy of a room that wants you to win.", "fitness-statement")}<Gallery project={project} /></>;
    case "redline-auto": return <><section className="auto-inspection" id="services"><p>Digital vehicle inspection</p><h2>See the work before we start it.</h2><div><span>Inspect</span><span>Review</span><span>Approve</span></div><a href="#quote">Book service</a></section>{cards("Service bays", "auto-cards")}<Review project={project} /><Gallery project={project} /></>;
    case "sable-table": return <><section className="restaurant-reserve" id="services"><p>DINNER AT SABLE</p><h2>The table is waiting.</h2><div><a href="#quote">Reserve a table</a><a href="#gallery">Explore the menu</a></div></section><section className="menu-moment"><span>Tonight’s kitchen</span><p>Seasonal plates, precise pours, and a slower kind of evening.</p></section><Gallery project={project} /><Review project={project} /></>;
    case "provenance-realty": return <><section className="listing-search" id="services"><p>Seattle, considered</p><h2>Find the right way home.</h2><div><button>Neighborhood</button><button>Price range</button><button>Home type</button><a href="#quote">Search listings</a></div></section><Gallery project={project} />{block("Private guidance", "A home search shaped around what matters to you.", "realty-statement")}<Review project={project} /></>;
    default: return <MinimalBody project={project} />;
  }
}
function EditorialBody({ project }: { project: PortfolioProject }) { return <><section className="demo-manifesto" id="about"><p>Built for the weather.<br />Made for the long haul.</p><span>01 / Ridgeway standard</span></section><Gallery project={project} /><section className="demo-services demo-editorial-services" id="services">{["Roof inspections", "Replacement", "Storm response"].map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><a href="#quote">Learn more →</a></article>)}</section><Review project={project} /></>; }
function LumeBody({ project }: { project: PortfolioProject }) { return <><section className="demo-ritual" id="services"><p className="demo-label">The Lume ritual</p><h2>Care that makes room for you.</h2><div>{["Arrive", "Restore", "Radiate"].map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>A considered, unhurried step in the guest experience.</p></article>)}</div></section><Review project={project} /><section className="demo-about demo-lume-about" id="about"><p className="demo-label">A thoughtful practice</p><h2>Good care starts with being heard.</h2><p>For this fictional med spa, soft visual rhythm and service clarity work together to create a premium booking experience.</p></section><Gallery project={project} /></>; }
function FieldBody({ project }: { project: PortfolioProject }) { return <><Gallery project={project} /><section className="demo-field-story" id="about"><div><span>F</span><h2>Made for the way you want to live outside.</h2></div><p>Field &amp; Form is a fictional studio that turns the natural character of a site into a daily place to gather, rest, and grow.</p></section><section className="demo-services demo-field-services" id="services">{["Garden design", "Seasonal care", "Outdoor living"].map((item) => <article key={item}><h3>{item}</h3><p>Thoughtful work, made to settle beautifully into its surroundings.</p></article>)}</section><Review project={project} /></>; }
function Gallery({ project }: { project: PortfolioProject }) { return <section className="demo-gallery" id="gallery" data-project={project.slug}><div className="demo-gallery-heading"><p className="demo-label">Gallery</p><h2>Work with a point of view.</h2></div><div className="demo-gallery-grid">{["A closer look", "Built around people", "The details matter"].map((caption, index) => <figure key={caption} className={`gallery-${index + 1}`}><div><img src={project.photo} alt={`Fictional ${project.industry.toLowerCase()} photography for ${project.company}`} loading="lazy" /><i /><i /><i /></div><figcaption>{caption}</figcaption></figure>)}</div></section>; }
function Review({ project }: { project: PortfolioProject }) { return <section className="demo-review" id="reviews"><p>“{project.quote}”</p><span>— Fictional customer review</span></section>; }
