/**
 * Generated by scripts/capture-demos.mjs — do not edit by hand.
 *
 * Records the date each "before" frame was actually shot from the live site.
 * `null` means the capture has not succeeded yet and the image on disk is the
 * placeholder, so the UI says "pending capture" instead of claiming a
 * screenshot it does not have.
 */
export const capturedBefore: Record<string, string | null> = {
  "berkshire-hathaway": null,
  "craigslist": null,
  "ryanair": null,
  "usps": null,
  "yahoo": null,
  "jcpenney": null,
};
